<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [SPAM] Re: [mod_python] connection to host server broken
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5BSPAM%5D%20Re%3A%20%5Bmod_python%5D%20connection%20to%20host%20server%20broken&In-Reply-To=284175.5100.qm%40web38709.mail.mud.yahoo.com">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="023359.html">
   <LINK REL="Next"  HREF="023367.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[SPAM] Re: [mod_python] connection to host server broken</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>Jim Gallacher</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5BSPAM%5D%20Re%3A%20%5Bmod_python%5D%20connection%20to%20host%20server%20broken&In-Reply-To=284175.5100.qm%40web38709.mail.mud.yahoo.com"
       TITLE="[SPAM] Re: [mod_python] connection to host server broken">jpg at jgassociates.ca
       </A><BR>
    <I>Tue Mar 27 13:38:29 EST 2007</I>
    <P><UL>
        <LI>Previous message: <A HREF="023359.html">[SPAM] Re: [mod_python] connection to host server broken
</A></li>
        <LI>Next message: <A HREF="023367.html">[mod_python] connection to host server broken
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#23360">[ date ]</a>
              <a href="thread.html#23360">[ thread ]</a>
              <a href="subject.html#23360">[ subject ]</a>
              <a href="author.html#23360">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>sikander hayat wrote:
&gt;<i> Hi,
</I>&gt;<i> 
</I>&gt;<i> Thanks for your help. Just wanted to point out that, out of frustation, i installed mod_python 3.2.10 and discarded mod_python 3.3.1 and magically it all works fine !!!
</I>&gt;<i> 
</I>&gt;<i> What I would like to conclude from this is, that there might be some dependency in 3.3.1 that caused havoc...(atleast for me). As pointed out previously, 3.3.1 constantly kept on giving the following errors:
</I>&gt;<i> 
</I>&gt;<i> child pid 28468 exit signal Segmentation fault (11)
</I>&gt;<i> [Tue Mar 27 17:26:14 2007] [notice] child pid 28469 exit signal Segmentation fault (11)
</I>&gt;<i> [Tue Mar 27 17:26:40 2007] [error] [client 134.96.24.83] File does not exist: /opt/lampp/htdocs/favicon.ico
</I>&gt;<i> [Tue Mar 27 17:29:21 2007] [error] [client 134.96.24.83] File does not exist: /opt/lampp/htdocs/favicon.ico
</I>&gt;<i> 
</I>&gt;<i> 
</I>&gt;<i> Why this segmentation error with 3.3.1 
</I>
Obviously we'd like to sort out why 3.3.1 is segfaulting. Did you try 
Graham's suggestion of doing:

  PythonHandler mod_python.testhandler

and still get a segfault? If not, can you either try it, or share the 
contents of you index.py file that caused the problem?

&gt;<i> and also, i had nothing to do with this favicon.ico. I do not have this icon and
</I> &gt; do not intend to make one. Why and which process needs this icon... 
*wondering*

This has nothing to do with mod_python. It's your browser that is 
requesting favicon.ico. You don't have one and apache logs that fact, 
and is standard behaviour for a missing file. If you don't intend to 
create one you better get used to having your error logs clogged with 
this message, as I believe some (all?) modern browsers automatically 
request it.

Jim

&gt;<i> Thanks,
</I>&gt;<i> Sikander
</I>&gt;<i> 
</I>&gt;<i> 
</I>&gt;<i> Graham Dumpleton &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">graham.dumpleton at gmail.com</A>&gt; wrote: On 26/03/07, sikander hayat  wrote:
</I>&gt;&gt;<i> Hi,
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> I am using suse 10.1, Apache 2.2.4, python 2.5 and mod_python 3.3.1.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> The error log is as follows:
</I>&gt;&gt;<i> [Mon Mar 26 10:16:48 2007] [warn] RSA server certificate is a CA certificate
</I>&gt;&gt;<i> (BasicConstraints: CA == TRUE !?)
</I>&gt;&gt;<i> [Mon Mar 26 10:16:48 2007] [warn] RSA server certificate CommonName (CN)
</I>&gt;&gt;<i> `localhost' does NOT match server name!?
</I>&gt;&gt;<i> [Mon Mar 26 10:16:48 2007] [notice] mod_python: Creating 8 session mutexes
</I>&gt;&gt;<i> based on 256 max processes and 0 max threads.
</I>&gt;&gt;<i> [Mon Mar 26 10:16:48 2007] [notice] mod_python: using mutex_directory /tmp
</I>&gt;&gt;<i> [Mon Mar 26 10:16:48 2007] [notice] Apache/2.2.4 (Unix) DAV/2 mod_ssl/2.2.4
</I>&gt;&gt;<i> OpenSSL/0.9.8d mod_python/3.3.1 Python/2.5 PHP/5.2.1
</I>&gt;&gt;<i> mod_apreq2-20051231/2.5.7 m
</I>&gt;&gt;<i> od_perl/2.0.2 Perl/v5.8.7 configured -- resuming normal operations
</I>&gt;&gt;<i> [Mon Mar 26 10:17:04 2007] [error] [client 134.96.24.83] File does not
</I>&gt;&gt;<i> exist: /opt/lampp/htdocs/favicon.ico
</I>&gt;&gt;<i> [Mon Mar 26 10:17:35 2007] [notice] mod_python (pid=3230,
</I>&gt;&gt;<i> interpreter='localhost'): Importing module
</I>&gt;&gt;<i> '/opt/lampp/htdocs/parkweb/index.py'
</I>&gt;&gt;<i> [Mon Mar 26 10:17:35 2007] [notice] mod_python (pid=3231,
</I>&gt;&gt;<i> interpreter='localhost'): Importing module
</I>&gt;&gt;<i> '/opt/lampp/htdocs/parkweb/index.py'
</I>&gt;&gt;<i> [Mon Mar 26 10:17:36 2007] [notice] child pid 3230 exit signal Segmentation
</I>&gt;&gt;<i> fault (11)
</I>&gt;&gt;<i> [Mon Mar 26 10:17:36 2007] [notice] child pid 3231 exit signal Segmentation
</I>&gt;&gt;<i> fault (11)
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> I have recently upgraded to python 2.5. So, to say, i have 2 versions of
</I>&gt;&gt;<i> python on my system. Will try to remove the older one and try again.
</I>&gt;<i> 
</I>&gt;<i> To confirm whether that is necessary, set:
</I>&gt;<i> 
</I>&gt;<i>   PythonHandler mod_python.testhandler
</I>&gt;<i> 
</I>&gt;<i> In the output from that just verify that the sys.path information is
</I>&gt;<i> correct for the version of Python you expect to use. From the above
</I>&gt;<i> log entries there probably isn't a problem with versions as mod_python
</I>&gt;<i> will actually log some warnings if it finds a different version of
</I>&gt;<i> Python than what it was compiled with and that isn't in the log
</I>&gt;<i> entries.
</I>&gt;<i> 
</I>&gt;&gt;<i> ****Why is it loading the module twice ...is that normal ???
</I>&gt;<i> 
</I>&gt;<i> Note how the 'pid' is different for each. This means that there were
</I>&gt;<i> two requests and that they so happened to be handled by different
</I>&gt;<i> Apache child processes.
</I>&gt;<i> 
</I>&gt;&gt;<i> Kindly let me know if something rings a bell.
</I>&gt;<i> 
</I>&gt;<i> Since you are using Python 2.5, it should not be the expat version
</I>&gt;<i> problem as Python 2.5 is supposed to change things to avoid that one.
</I>&gt;<i> I would though still suspect that it is some versioning problem with
</I>&gt;<i> shared libraries. For example, if your web application uses some sort
</I>&gt;<i> of database and you also have PHP loaded and it is using some
</I>&gt;<i> different version of the database client library. This sort of
</I>&gt;<i> mismatch can cause a crash as one library will take precedence over
</I>&gt;<i> the other and if they are not compatible it can crash.
</I>&gt;<i> 
</I>&gt;<i> What you may need to do is start adding debug into your code and the
</I>&gt;<i> framework it uses such that you output a log message before and after
</I>&gt;<i> every module import. For example:
</I>&gt;<i> 
</I>&gt;<i>   from mod_python import apache
</I>&gt;<i> 
</I>&gt;<i>   apache.log_error(__file__  + &quot; #1&quot;)
</I>&gt;<i>   import pyexpat
</I>&gt;<i>   apache.log_error(__file__ + &quot; #2&quot;)
</I>&gt;<i>   import module2
</I>&gt;<i>   apache.log_error(__file__ + &quot; #3&quot;)
</I>&gt;<i> 
</I>&gt;<i> See how many of the messages come out in the Apache error log and slow
</I>&gt;<i> narrow it down to a specific module being importer causing the crash.
</I>&gt;<i> 
</I>&gt;<i> If the module imports aren't the problem but something in handler
</I>&gt;<i> itself, do something similar, logging messages to the Apache log until
</I>&gt;<i> you find exactly what call causes it.
</I>&gt;<i> 
</I>&gt;<i> Graham
</I>&gt;<i> 
</I>&gt;&gt;<i> Thanks,
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Graham Dumpleton  wrote:
</I>&gt;&gt;<i>  On 24/03/07, Jim Gallacher wrote:
</I>&gt;&gt;&gt;<i> sikander hayat wrote:
</I>&gt;&gt;&gt;&gt;<i> Hi all,
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> My apache webserver on linux recently broke down, so i reinstalled it,
</I>&gt;&gt;<i> along with mod_python. Having made the necessary changes in the conf file of
</I>&gt;&gt;<i> apache, i tried some of the simple tests, such as mptest, but i keep on
</I>&gt;&gt;<i> getting the following error.
</I>&gt;&gt;&gt;&gt;<i> Connection to host server ... lost.
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> Why is that, is it because of python or some apache setting.
</I>&gt;&gt;&gt;<i> Or network problems?
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> What do you find in your apache logs?
</I>&gt;&gt;<i> The Apache error log would be a good start, as it looks to me like
</I>&gt;&gt;<i> your Apache child processes are crashing. You may find errors about
</I>&gt;&gt;<i> segmentation violations or similar in the logs. If you do, check that
</I>&gt;&gt;<i> the version of mod_python you are using is the correct one for the
</I>&gt;&gt;<i> version of Python and Apache you are using. Having multiple versions
</I>&gt;&gt;<i> of Python installed can also cause issues.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> BTW, are you using precompiled packages or compiling everything from
</I>&gt;&gt;<i> source code? What operating system are you using?
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Graham
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>  ________________________________
</I>&gt;&gt;<i> Sucker-punch spam with award-winning protection.
</I>&gt;&gt;<i>  Try the free Yahoo! Mail Beta.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;<i> 
</I>&gt;<i> 
</I>&gt;<i>  
</I>&gt;<i> ---------------------------------
</I>&gt;<i> The fish are biting.
</I>&gt;<i>  Get more visitors on your site using Yahoo! Search Marketing.
</I>&gt;<i> 
</I>&gt;<i> 
</I>&gt;<i> ------------------------------------------------------------------------
</I>&gt;<i> 
</I>&gt;<i> _______________________________________________
</I>&gt;<i> Mod_python mailing list
</I>&gt;<i> <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">Mod_python at modpython.org</A>
</I>&gt;<i> <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">http://mailman.modpython.org/mailman/listinfo/mod_python</A>
</I>
</PRE>


<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="023359.html">[SPAM] Re: [mod_python] connection to host server broken
</A></li>
	<LI>Next message: <A HREF="023367.html">[mod_python] connection to host server broken
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#23360">[ date ]</a>
              <a href="thread.html#23360">[ thread ]</a>
              <a href="subject.html#23360">[ subject ]</a>
              <a href="author.html#23360">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script type="text/javascript"><!--
google_ad_client = "pub-9718360309690383";
google_ad_width = 120;
google_ad_height = 600;
google_ad_format = "120x600_as";
google_color_border = "CCCCCC";
google_color_bg = "FFFFFF";
google_color_link = "000000";
google_color_url = "666666";
google_color_text = "333333";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
