<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] Problem to run .py scripts thru apache
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20Problem%20to%20run%20.py%20scripts%20thru%20apache&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="011681.html">
   <LINK REL="Next"  HREF="011683.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[mod_python] Problem to run .py scripts thru apache</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>Ralf Fortnagel</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20Problem%20to%20run%20.py%20scripts%20thru%20apache&In-Reply-To="
       TITLE="[mod_python] Problem to run .py scripts thru apache">r.fortnagel at 21torr.com
       </A><BR>
    <I>Thu Feb 22 11:41:01 EST 2001</I>
    <P><UL>
        <LI>Previous message: <A HREF="011681.html">[mod_python] mod_python/publisher/solaris truncation problems
</A></li>
        <LI>Next message: <A HREF="011683.html">[mod_python] Problem to run .py scripts thru apache
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#11682">[ date ]</a>
              <a href="thread.html#11682">[ thread ]</a>
              <a href="subject.html#11682">[ subject ]</a>
              <a href="author.html#11682">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hi Folks!

I use Apache/1.3.14 (Win32) mod_python/2.7.1 Python/2.0 on a Win/NT4.0
machine
If i try to start any .py file thru apache, i get following error:

Mod_python error: &quot;PythonHandler test&quot;
Traceback (most recent call last):
  File &quot;c:\programme\python20\lib\mod_python\apache.py&quot;, line 180, in
Dispatch
    object = resolve_object(self.req, module, object_str, silent)
  File &quot;c:\programme\python20\lib\mod_python\apache.py&quot;, line 396, in
resolve_object
    raise AttributeError, s
AttributeError: module 'c:\programme\python20\lib\test\__init__.py' contains
no 'handler'

please help me, i don't know what's wrong... :(
--
Ralf Fortnagel                21TORR AGENCY gmbh
<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">r.fortnagel at 21torr.com</A>        Engineering
tel: +49-7121-348-221         Heinestrasse 72
fax: +49-7121-348-259         D-72762 Reutlignen

21TORR - die neue medien leidenschaft
www.21torr.com


</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="011681.html">[mod_python] mod_python/publisher/solaris truncation problems
</A></li>
	<LI>Next message: <A HREF="011683.html">[mod_python] Problem to run .py scripts thru apache
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#11682">[ date ]</a>
              <a href="thread.html#11682">[ thread ]</a>
              <a href="subject.html#11682">[ subject ]</a>
              <a href="author.html#11682">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script type="text/javascript"><!--
google_ad_client = "pub-9718360309690383";
google_ad_width = 120;
google_ad_height = 600;
google_ad_format = "120x600_as";
google_color_border = "CCCCCC";
google_color_bg = "FFFFFF";
google_color_link = "000000";
google_color_url = "666666";
google_color_text = "333333";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
