<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] Apache Fails to load mod_python.so with
	Permissiondenied error under SELinux
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20Apache%20Fails%20to%20load%20mod_python.so%20with%0A%09Permissiondenied%20error%20under%20SELinux&In-Reply-To=004f01c86441%246e292060%240200a8c0%40TMSMAIN">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="024786.html">
   <LINK REL="Next"  HREF="024788.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[mod_python] Apache Fails to load mod_python.so with
	Permissiondenied error under SELinux</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>Scott Bratcher</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20Apache%20Fails%20to%20load%20mod_python.so%20with%0A%09Permissiondenied%20error%20under%20SELinux&In-Reply-To=004f01c86441%246e292060%240200a8c0%40TMSMAIN"
       TITLE="[mod_python] Apache Fails to load mod_python.so with
	Permissiondenied error under SELinux">scott at 3floors.com
       </A><BR>
    <I>Thu Jan 31 19:28:58 EST 2008</I>
    <P><UL>
        <LI>Previous message: <A HREF="024786.html">[mod_python] Problem getting the Publisher handler to return
	nothing
</A></li>
        <LI>Next message: <A HREF="024788.html">[mod_python] Apache Fails to load mod_python.so with
	Permissiondenied error under SELinux
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#24787">[ date ]</a>
              <a href="thread.html#24787">[ thread ]</a>
              <a href="subject.html#24787">[ subject ]</a>
              <a href="author.html#24787">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Thanks Eric and Tom,

Unresolved however. I did some permissions tests based on your feedback.


I'm chasing this issue as though it is a permissions issue and have  
identified SELinux as the hold-up. I've tried all of these permission  
sets on the modules actual folder and the modules symlinked folder.
I did both directories just in case the permissions trickle down to  
the actual files being loaded by mod_python itself:

# chcon -R -h -u system_u -r object_r -t httpd_sys_content_t /usr/lib/ 
httpd/modules /etc/httpd/modules
# chcon -R -h -u user_u -r object_r -t httpd_sys_content_t /usr/lib/ 
httpd/modules /etc/httpd/modules
# chcon -R -h -u user_u -r object_r -t httpd_modules_t /usr/lib/httpd/ 
modules /etc/httpd/modules
# chcon -R -h -u system_u -r object_r -t httpd_modules_t /usr/lib/ 
httpd/modules /etc/httpd/modules ((( This one is the original  
permission of all apache modules)))
# chcon -R -h -u system_u -r object_r -t lib_t /usr/lib/httpd/ 
modules /etc/httpd/modules
# chcon -R -h -u system_u -r object_r -t shlib_t /usr/lib/httpd/ 
modules /etc/httpd/modules
# chcon -R -h -u system_u -r object_r -t textrel_shlib_t /usr/lib/ 
httpd/modules /etc/httpd/modules

All gave this error:
----------
# service httpd start
Starting httpd: httpd: Syntax error on line 210 of /etc/httpd/conf/ 
httpd.conf: Syntax error on line 6 of /etc/httpd/conf.d/python.conf:  
Cannot load /etc/httpd/modules/mod_python.so into server: /etc/httpd/ 
modules/mod_python.so: cannot restore segment prot after reloc:  
Permission denied
                                                            [FAILED]
----------

---&gt; This is the only one that gave me a different error.
----------
# chcon -R -h -u system_u -t textrel_shlib_t /usr/lib/httpd/modules / 
etc/httpd/modules
# service httpd start
Starting httpd: httpd: Syntax error on line 148 of /etc/httpd/conf/ 
httpd.conf: Cannot load /etc/httpd/modules/mod_auth_basic.so into  
server: /etc/httpd/modules/mod_auth_basic.so: cannot open shared  
object file: Permission denied
                                                            [FAILED]
----------


****AGAIN I MUST NOTE: All is solved by turning off SELinux and/or  
All is solved by not loading mod_python. All other modules loaded  
just fine with their original permissions which matched mod_python  
exactly.




Scott



On Jan 31, 2008, at 1:42 PM, Tom Stambaugh wrote:

&gt;<i> The incantation that I use (for solving different problems, though)  
</I>&gt;<i> is:
</I>&gt;<i>
</I>&gt;<i> chcon -R -h -t httpd_sys_content_t &lt;filename&gt;
</I>&gt;<i>
</I>&gt;<i> I think the &quot;-R&quot; makes it recurse to all children, and I think the
</I>&gt;<i> &quot;httpd_sys_content_t&quot; is more permissive (though that could be  
</I>&gt;<i> mistaken).
</I>&gt;<i> The -h causes it to apply to sym links.
</I>&gt;<i>
</I>&gt;<i> Afterwords, I get:
</I>&gt;<i>
</I>&gt;<i> #ls -lZ adminuser
</I>&gt;<i> -rw-rw-r--  zeetix   zeetix   user_u:object_r:httpd_sys_content_t  
</I>&gt;<i> &lt;filename&gt;
</I>&gt;<i>
</I>&gt;<i> I use Fedora core3/core4 linux, so YMMV.
</I>&gt;<i>
</I>&gt;<i> Thx,
</I>&gt;<i> Tom
</I>&gt;<i>
</I>&gt;<i> ----- Original Message -----
</I>&gt;<i> From: &quot;Scott Bratcher&quot; &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">scott at 3floors.com</A>&gt;
</I>&gt;<i> To: &quot;Eric Brunson&quot; &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">brunson at brunson.com</A>&gt;
</I>&gt;<i> Cc: &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">mod_python at modpython.org</A>&gt;
</I>&gt;<i> Sent: Thursday, January 31, 2008 1:47 PM
</I>&gt;<i> Subject: Re: [mod_python] Apache Fails to load mod_python.so with
</I>&gt;<i> Permissiondenied error under SELinux
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;<i> Thanks Eric,
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> &quot;setenforce 0&quot; THIS WORKED. Apache started right up
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Below are the results of my attempts as you suggested. I think we are
</I>&gt;&gt;<i> onto the problem because with SELinux enforced it loads right up.
</I>&gt;&gt;<i> However, the chcon command failed to clear up the problem. I'm new to
</I>&gt;&gt;<i> SELinux. Is there another possible SELinux related permission  
</I>&gt;&gt;<i> that  may be
</I>&gt;&gt;<i> the solution? It's just mod_python that is giving this problem  even
</I>&gt;&gt;<i> though all of the others share the same t permission httpd_module.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> # ls -Zd modules
</I>&gt;&gt;<i> drwxr-xr-x  root root system_u:object_r:httpd_modules_t modules/
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> So I changed the permissions:
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> # chcon -t texrel_shlib_t /etc/httpd/modules/mod_python.so
</I>&gt;&gt;<i> # service httpd start
</I>&gt;&gt;<i> Starting httpd: httpd: Syntax error on line 210 of /etc/httpd/conf/
</I>&gt;&gt;<i> httpd.conf: Syntax error on line 6 of /etc/httpd/conf.d/python.conf:
</I>&gt;&gt;<i> Cannot load /etc/httpd/modules/mod_python.so into server: /etc/httpd/
</I>&gt;&gt;<i> modules/mod_python.so: cannot restore segment prot after reloc:
</I>&gt;&gt;<i> Permission denied
</I>&gt;&gt;<i>                                                            [FAILED]
</I>&gt;&gt;<i> # ls -Z /etc/httpd/modules/mod_python.so
</I>&gt;&gt;<i> -rwxr-xr-x  root root system_u:object_r:textrel_shlib_t /etc/httpd/
</I>&gt;&gt;<i> modules/mod_python.so*
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> I also tried changing the permissions of the 2.5 site-packages to the
</I>&gt;&gt;<i> same permissions as the previously working 2.4 site-packages,  
</I>&gt;&gt;<i> plus  the
</I>&gt;&gt;<i> other listed below, and the still Apache Failure occurs.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> # ls -Zd /usr/local/lib/python2.5/site-packages/ /usr/lib/python2.4/
</I>&gt;&gt;<i> site-packages/
</I>&gt;&gt;<i> drwxr-xr-x  root root system_u:object_r:lib_t           /usr/lib/
</I>&gt;&gt;<i> python2.4/site-packages/
</I>&gt;&gt;<i> drwxr-xr-x  root root user_u:object_r:lib_t             /usr/local/
</I>&gt;&gt;<i> lib/python2.5/site-packages/
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> system_u:object_r:lib_t
</I>&gt;&gt;<i> system_u:object_r:textrel_shlib_t
</I>&gt;&gt;<i> user_u:object_r:textrel_shlib_t
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> If you have other tips I'd appreciate any help you can offer.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Scott
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> On Jan 31, 2008, at 10:13 AM, Eric Brunson wrote:
</I>&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> Scott Bratcher wrote:
</I>&gt;&gt;&gt;&gt;<i> Hello all,
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> THE PROBLEM:
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> Starting Apache results in this error:
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> # service httpd start
</I>&gt;&gt;&gt;&gt;<i> Starting httpd: httpd: Syntax error on line 210 of /etc/httpd/conf/
</I>&gt;&gt;&gt;&gt;<i> httpd.conf: Syntax error on line 6 of /etc/httpd/conf.d/  
</I>&gt;&gt;&gt;&gt;<i> python.conf:
</I>&gt;&gt;&gt;&gt;<i> Cannot load /etc/httpd/modules/mod_python.so into  server:
</I>&gt;&gt;&gt;&gt;<i> /etc/httpd/modules/mod_python.so: cannot restore segment  prot  
</I>&gt;&gt;&gt;&gt;<i> after
</I>&gt;&gt;&gt;&gt;<i> reloc: Permission denied
</I>&gt;&gt;&gt;&gt;<i>                                                            [FAILED]
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> This error message is often related to selinux permissions.
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> A quick check to see if that is the problem is to disable  
</I>&gt;&gt;&gt;<i> selinux  with
</I>&gt;&gt;&gt;<i> the command (as root) &quot;setenforce 0&quot;.  If the module then  loads
</I>&gt;&gt;&gt;<i> correctly, it can be fixed permanently with the command:
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> chcon -t texrel_shlib_t /etc/httpd/modules/mod_python.so
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> Then, re-enable selinux with &quot;setenforce 1&quot;.
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> If disabling selinux does not fix the problem, then more   
</I>&gt;&gt;&gt;<i> investigation
</I>&gt;&gt;&gt;<i> is required.
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> Hope that helps,
</I>&gt;&gt;&gt;<i> e.
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> USING:
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> RHEL5 / SELinux
</I>&gt;&gt;&gt;&gt;<i> Apache 2.2
</I>&gt;&gt;&gt;&gt;<i> Python 2.5.1
</I>&gt;&gt;&gt;&gt;<i> mod_pythonn 3.3.1
</I>&gt;&gt;&gt;&gt;<i> httpd.conf (not .htaccess)
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> TESTED THUS FAR:
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> .so file exists with same permissions as other modules
</I>&gt;&gt;&gt;&gt;<i> # ls -Z /etc/httpd/modules/mod_python.so
</I>&gt;&gt;&gt;&gt;<i> -rwxr-xr-x  root root system_u:object_r:httpd_modules_t /etc/httpd/
</I>&gt;&gt;&gt;&gt;<i> modules/mod_python.so*
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> If I comment out:
</I>&gt;&gt;&gt;&gt;<i> &quot;#LoadModule python_module modules/mod_python.so&quot;
</I>&gt;&gt;&gt;&gt;<i> and other related python lines Apache starts just fine without
</I>&gt;&gt;&gt;&gt;<i> mod_python.
</I>&gt;&gt;&gt;&gt;<i> # service httpd start
</I>&gt;&gt;&gt;&gt;<i> Starting httpd:                                            [  OK  ]
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> _______________________________________________
</I>&gt;&gt;<i> Mod_python mailing list
</I>&gt;&gt;<i> <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">Mod_python at modpython.org</A>
</I>&gt;&gt;<i> <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">http://mailman.modpython.org/mailman/listinfo/mod_python</A>
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>
</PRE>


<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="024786.html">[mod_python] Problem getting the Publisher handler to return
	nothing
</A></li>
	<LI>Next message: <A HREF="024788.html">[mod_python] Apache Fails to load mod_python.so with
	Permissiondenied error under SELinux
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#24787">[ date ]</a>
              <a href="thread.html#24787">[ thread ]</a>
              <a href="subject.html#24787">[ subject ]</a>
              <a href="author.html#24787">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script type="text/javascript"><!--
google_ad_client = "pub-9718360309690383";
google_ad_width = 120;
google_ad_height = 600;
google_ad_format = "120x600_as";
google_color_border = "CCCCCC";
google_color_bg = "FFFFFF";
google_color_link = "000000";
google_color_url = "666666";
google_color_text = "333333";
//--></script>
<script type="text/javascript"
  src="DISABLEhttp://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
