<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] problem creating an instance and debugging
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20problem%20creating%20an%20instance%20and%20debugging&In-Reply-To=20030703161120.58394.qmail%40web13908.mail.yahoo.com">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="013933.html">
   <LINK REL="Next"  HREF="013935.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[mod_python] problem creating an instance and debugging</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>Gregory (Grisha) Trubetskoy</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20problem%20creating%20an%20instance%20and%20debugging&In-Reply-To=20030703161120.58394.qmail%40web13908.mail.yahoo.com"
       TITLE="[mod_python] problem creating an instance and debugging">grisha at modpython.org
       </A><BR>
    <I>Thu Jul  3 13:31:54 EST 2003</I>
    <P><UL>
        <LI>Previous message: <A HREF="013933.html">[mod_python] problem creating an instance and debugging
</A></li>
        <LI>Next message: <A HREF="013935.html">[mod_python] problem creating an instance and debugging
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#13934">[ date ]</a>
              <a href="thread.html#13934">[ thread ]</a>
              <a href="subject.html#13934">[ subject ]</a>
              <a href="author.html#13934">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>

On Thu, 3 Jul 2003, Daniel Rubin wrote:

&gt;<i> An error is happening in the xmlrpc.py program, and this isn't making
</I>&gt;<i> it's own stack dump or errors written to the apache logs on the server.
</I>&gt;<i> So I can't debug what the nature of the error that is happening in the
</I>&gt;<i> remotely called function.
</I>
So, tell me if I understand this correctly (I'm not familiar with
xmlrpc.py) -

Xmlrpc.py is a CGI script which reports its errors by writing them to
stderr. Something happens when you run it under mod_python, and you don't
know what it is because stderr goes nowhere.

As far as I know, stderr output may end up in your error log, but I don't
think that's guaranteed and may be dependent on how your httpd was
compiled.  I think there is really no solution to this other than to tweak
xmlrpc into raising its exception or using mod_python's log_error to
report it.

HTH,

Grisha
</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="013933.html">[mod_python] problem creating an instance and debugging
</A></li>
	<LI>Next message: <A HREF="013935.html">[mod_python] problem creating an instance and debugging
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#13934">[ date ]</a>
              <a href="thread.html#13934">[ thread ]</a>
              <a href="subject.html#13934">[ subject ]</a>
              <a href="author.html#13934">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-42971867-2', 'modpython.org');
  ga('send', 'pageview');
</script>

</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
