<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> R: [mod_python] Serius problem in mod_python-3.2.2b
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=R%3A%20%5Bmod_python%5D%20Serius%20problem%20in%20mod_python-3.2.2b&In-Reply-To=BC53C974C3B9E542BC0A9BD4C5B1168A0B763D%40NEWMAIL.manord.com">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="019355.html">
   <LINK REL="Next"  HREF="019358.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>R: [mod_python] Serius problem in mod_python-3.2.2b</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>Graham Dumpleton</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=R%3A%20%5Bmod_python%5D%20Serius%20problem%20in%20mod_python-3.2.2b&In-Reply-To=BC53C974C3B9E542BC0A9BD4C5B1168A0B763D%40NEWMAIL.manord.com"
       TITLE="R: [mod_python] Serius problem in mod_python-3.2.2b">grahamd at dscpl.com.au
       </A><BR>
    <I>Wed Oct 19 06:38:21 EDT 2005</I>
    <P><UL>
        <LI>Previous message: <A HREF="019355.html">R: [mod_python] Serius problem in mod_python-3.2.2b
</A></li>
        <LI>Next message: <A HREF="019358.html">R: [mod_python] Serius problem in mod_python-3.2.2b
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#19356">[ date ]</a>
              <a href="thread.html#19356">[ thread ]</a>
              <a href="subject.html#19356">[ subject ]</a>
              <a href="author.html#19356">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>
On 19/10/2005, at 8:04 PM, Manera, Villiam wrote:

&gt;<i> Is not a import problem, I have now tried the workaround from Graham 
</I>&gt;<i> Dumpleton:
</I>&gt;<i>
</I>&gt;<i> name = os.path.splitext(os.path.split(__file__)[1])[0]&#160; instead 
</I>&gt;<i> __name__ and it work fine.
</I>&gt;<i>
</I>&gt;<i> I use __name__ inside my appplications not for import scope, but for 
</I>&gt;<i> check autentication of module and so on...
</I>&gt;<i>
</I>&gt;<i> I this will be the new behaviour I may fix all my programs (375) that 
</I>&gt;<i> used &#160;__name__&#160;
</I>&gt;<i>
</I>&gt;<i> May I start to fix my programs 
</I>&gt;<i> with&#160;&#160;os.path.splitext(os.path.split(__file__)[1])[0]&#160; instead 
</I>&gt;<i> __name__&#160; ?
</I>
You shouldn't really use module name for authentication in this way. The
reason is that with mod_python.publisher, you could have index.py
present in two different directories. In 3.2 these will truly be two
distinct modules albeit they still use the same basename of &quot;index&quot;. If
your authentication is based purely on module name (basename), you
wouldn't be able to define different authorisation credentials for these
two different files. You would perhaps be better off basing any
authentication mechanism on URL or physical file location.

Graham

&gt;<i> &#160;-----Messaggio originale-----
</I>&gt;<i> Da: Nicolas Lehuen [mailto:<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">nicolas.lehuen at gmail.com</A>]
</I>&gt;<i> Inviato: mercoled&#236; 19 ottobre 2005 11.05
</I>&gt;<i> A: Manera, Villiam
</I>&gt;<i> Cc: <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">mod_python at modpython.org</A>
</I>&gt;<i> Oggetto: Re: [mod_python] Serius problem in mod_python-3.2.2b
</I>&gt;<i>
</I>&gt;&gt;<i> No, it's not a bug, it's a feature. In the new publisher, published 
</I>&gt;&gt;<i> module are no longer stored in sys.modules and the __name__ attribute 
</I>&gt;&gt;<i> of the module is based on the filename.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Why is this a problem to you ? Giving the published module a simpler 
</I>&gt;&gt;<i> name is not that complicated, but I need to understand why it's 
</I>&gt;&gt;<i> important. Especially, if it is because you expect to be able to 
</I>&gt;&gt;<i> import the module by name from another module, tell me because things 
</I>&gt;&gt;<i> will change in the future mod_python releases.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Regards,
</I>&gt;&gt;<i> Nicolas
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> 2005/10/19, Manera, Villiam &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">vmanera at manord.com</A>&gt;: I Installed the 
</I>&gt;&gt;<i> beta from mod_python-3.2.2b.win32-py2.4.exe
</I>&gt;&gt;&gt;<i> Apache has started well
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> In my login program, the first checked, I use the python variable
</I>&gt;&gt;&gt;<i> __name__&#160;&#160;and this is the problem:
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> In early mod_python version the value was as
</I>&gt;&gt;&gt;<i> expetded:--&gt;cgi-mpy_login&lt;---Module name
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> In this beta:--&gt;D_discoE_script_cgi_cgi_mpy_cgi_mpy_login_py 
</I>&gt;&gt;&gt;<i> &lt;---Module
</I>&gt;&gt;&gt;<i> name
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> Why mod python change the python variable __name__ ?????
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> I hope this is a bug
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> Villiam
</I>&gt;&gt;&gt;<i> Italy
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> _______________________________________________
</I>&gt;&gt;&gt;<i> Mod_python mailing list
</I>&gt;&gt;&gt;<i> <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">Mod_python at modpython.org</A>
</I>&gt;&gt;&gt;<i> <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">http://mailman.modpython.org/mailman/listinfo/mod_python</A>
</I>&gt;<i> _______________________________________________
</I>&gt;<i> Mod_python mailing list
</I>&gt;<i> <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">Mod_python at modpython.org</A>
</I>&gt;<i> <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">http://mailman.modpython.org/mailman/listinfo/mod_python</A>
</I>

</PRE>















<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="019355.html">R: [mod_python] Serius problem in mod_python-3.2.2b
</A></li>
	<LI>Next message: <A HREF="019358.html">R: [mod_python] Serius problem in mod_python-3.2.2b
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#19356">[ date ]</a>
              <a href="thread.html#19356">[ thread ]</a>
              <a href="subject.html#19356">[ subject ]</a>
              <a href="author.html#19356">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script type="text/javascript"><!--
google_ad_client = "pub-9718360309690383";
google_ad_width = 120;
google_ad_height = 600;
google_ad_format = "120x600_as";
google_color_border = "CCCCCC";
google_color_bg = "FFFFFF";
google_color_link = "000000";
google_color_url = "666666";
google_color_text = "333333";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
