<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] mod_python servlet failing on non-existent code
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20mod_python%20servlet%20failing%20on%20non-existent%20code&In-Reply-To=411CC1B8.4030409%40earthlink.net">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="016053.html">
   <LINK REL="Next"  HREF="016055.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[mod_python] mod_python servlet failing on non-existent code</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>Gregory (Grisha) Trubetskoy</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20mod_python%20servlet%20failing%20on%20non-existent%20code&In-Reply-To=411CC1B8.4030409%40earthlink.net"
       TITLE="[mod_python] mod_python servlet failing on non-existent code">grisha at modpython.org
       </A><BR>
    <I>Fri Aug 13 11:08:18 EDT 2004</I>
    <P><UL>
        <LI>Previous message: <A HREF="016053.html">[mod_python] mod_python servlet failing on non-existent code
</A></li>
        <LI>Next message: <A HREF="016055.html">[mod_python] mod_python servlet failing on non-existent code
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#16054">[ date ]</a>
              <a href="thread.html#16054">[ thread ]</a>
              <a href="subject.html#16054">[ subject ]</a>
              <a href="author.html#16054">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>

On Fri, 13 Aug 2004, Chris Curvey wrote:

&gt;<i> I'm hacking my way through a proof-of-concept with mod_python servlets, and 
</I>&gt;<i> I'm coming across something strange.  When I hit my page, I'm getting an 
</I>&gt;<i> error message returned in a browser (&quot;unpack tuple of wrong size&quot;).   The 
</I>&gt;<i> strange part is that the line listed in the browser doesn't exist in my code 
</I>&gt;<i> anymore.  (I changed that line as part of the debugging process.)
</I>
This is not unusual - Python caches locations of lines so when a module is 
reloaded oftentimes the traceback will refer to the source code as it was 
in the original file. The only way to get around this is to restart the 
server.

&gt;<i> So I figured that maybe I was having a problem with mod_python caching 
</I>&gt;<i> classes, and I restarted apache just as &quot;httpd -X&quot;.  I hit the page again, 
</I>&gt;<i> and the same error message shows up in the browser, but the HTML that I want 
</I>&gt;<i> shows up in the window where I started httpd.
</I>
Are you writing your output to stdout (using &quot;print&quot;) or stderr for some 
reason?

Grisha
</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="016053.html">[mod_python] mod_python servlet failing on non-existent code
</A></li>
	<LI>Next message: <A HREF="016055.html">[mod_python] mod_python servlet failing on non-existent code
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#16054">[ date ]</a>
              <a href="thread.html#16054">[ thread ]</a>
              <a href="subject.html#16054">[ subject ]</a>
              <a href="author.html#16054">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-42971867-2', 'modpython.org');
  ga('send', 'pageview');
</script>

</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
