<tt>
Hello,&lt;br&gt;I'm&nbsp;not&nbsp;convinced&nbsp;that&nbsp;this&nbsp;is&nbsp;a&nbsp;specific&nbsp;mod_python&nbsp;problem&nbsp;but&nbsp;I'm&nbsp;not&nbsp;sure&nbsp;exactly&nbsp;how&nbsp;to&nbsp;explain&nbsp;it&nbsp;in&nbsp;generic&nbsp;terms&nbsp;so&nbsp;hopefully&nbsp;someone&nbsp;here&nbsp;can&nbsp;point&nbsp;me&nbsp;in&nbsp;the&nbsp;right&nbsp;direction.&lt;br&gt;I&nbsp;have&nbsp;a&nbsp;python&nbsp;script&nbsp;which&nbsp;calls&nbsp;<br>
urllib2.urlopen&nbsp;to&nbsp;open&nbsp;a&nbsp;url&nbsp;on&nbsp;a&nbsp;remote&nbsp;server&nbsp;(google).&nbsp;It&nbsp;works&nbsp;fine&nbsp;from&nbsp;the&nbsp;command&nbsp;line&nbsp;but&nbsp;when&nbsp;I&nbsp;run&nbsp;it&nbsp;from&nbsp;a&nbsp;mod_python.psp&nbsp;page&nbsp;I&nbsp;get:&lt;br&gt;&lt;pre&gt;HTTPError:&nbsp;HTTP&nbsp;Error&nbsp;403:&nbsp;Forbidden&lt;/pre&gt;Clearly&nbsp;this&nbsp;is&nbsp;something&nbsp;to&nbsp;do&nbsp;with&nbsp;the&nbsp;permissions&nbsp;of&nbsp;the&nbsp;apache&nbsp;user&nbsp;vs&nbsp;my&nbsp;shell&nbsp;user&nbsp;but&nbsp;what&nbsp;is&nbsp;the&nbsp;safest&nbsp;way&nbsp;to&nbsp;allow&nbsp;this&nbsp;script&nbsp;to&nbsp;run?<br>
&lt;br&gt;&lt;br&gt;Regards,&lt;br&gt;Emlyn.&lt;br&gt;&lt;br&gt;<br>

</tt>
