<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] Python codecs bug
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20Python%20codecs%20bug&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="009807.html">
   <LINK REL="Next"  HREF="009814.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
<table border=0 width="100%"><tr><td valign="top">
   <H1>[mod_python] Python codecs bug</H1>
    <B>Geert Jansen</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20Python%20codecs%20bug&In-Reply-To="
       TITLE="[mod_python] Python codecs bug">geertj at boskant.nl
       </A><BR>
    <I>Thu Mar 27 16:54:43 EST 2003</I>
    <P><UL>
        <LI>Previous message: <A HREF="009807.html">[mod_python] Import site failed
</A></li>
        <LI>Next message: <A HREF="009814.html">[mod_python] Import site failed
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#9803">[ date ]</a>
              <a href="thread.html#9803">[ thread ]</a>
              <a href="subject.html#9803">[ subject ]</a>
              <a href="author.html#9803">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hi,

recently, a bug in the Python codecs subsystem has been discovered that
can affect mod_python programs. I have a confirmed report that this bug fixes
the vague &quot;Cannot unmarshal code object in restricted execution mode&quot; error
that was discussed on this list:

  <A HREF="http://mail.python.org/pipermail/python-list/2002-June/109233.html">http://mail.python.org/pipermail/python-list/2002-June/109233.html</A>

The bug is described in detail here:

  <A HREF="http://sourceforge.net/tracker/index.php?func=detail&amp;aid=663074&amp;group_id=5470&amp;atid=105470">http://sourceforge.net/tracker/index.php?func=detail&amp;aid=663074&amp;group_id=5470&amp;atid=105470</A>

The Python 2.3 CVS has been fixed. A backport of this fix to Python 2.2.2 is
available from my website at:

  <A HREF="http://draco.boskant.nl/requirements.dsp">http://draco.boskant.nl/requirements.dsp</A>

the patch has been submitted to the Python crew.

I thought you'd might be interested...

Greetings,
Geert Jansen

</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="009807.html">[mod_python] Import site failed
</A></li>
	<LI>Next message: <A HREF="009814.html">[mod_python] Import site failed
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#9803">[ date ]</a>
              <a href="thread.html#9803">[ thread ]</a>
              <a href="subject.html#9803">[ subject ]</a>
              <a href="author.html#9803">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-42971867-2', 'modpython.org');
  ga('send', 'pageview');
</script>

</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
