From graham.dumpleton at gmail.com  Mon May  5 06:52:22 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Mon May  5 06:52:28 2008
Subject: [mod_python] Post of image data
In-Reply-To: <e1ebd8c50805050313h692c3013k99bb28305a7c9d9e@mail.gmail.com>
References: <45E36921B695A14FA56A34F29424A1EC011F9D5F@Apollo.neatreceipts.local>
	<88e286470804281504k4183e8d7y77f71d6a7bd209b5@mail.gmail.com>
	<e1ebd8c50805050313h692c3013k99bb28305a7c9d9e@mail.gmail.com>
Message-ID: <88e286470805050352o4d6359d8ia5773be5031f1f55@mail.gmail.com>

Please use reply-all and keep discussion on mod_python list.

Anyway, I don't understand what you are asking. Do you simply mean how
do you return a custom response?

Did you go through the other parts of the tutorial at:

  http://webpython.codepoint.net/

including the other bits about mod_python.publisher such as the hello
world example, which showed how responses are returned?

Graham

2008/5/5 liyangmin <liyangmin@gmail.com>:
> thanks a lot .  it helps a lot .
> I have another question as below:
> using req.form.getfirst()  method I can  read form data from a  request.
> but How can i change the from data and  response  to the user?
>
> for example : I am using the template:
>
> <form action="show" method="POST">
> <center><input name="path_name" type="text" value=""/> </center>
> <center><input name="show_button" type="submit" value=""/></center>
>  </form
>
> 2008/4/29 Graham Dumpleton <graham.dumpleton@gmail.com>:
>
>
> > You don't say whether you are using raw mod_python handlers or
> > mod_python.publisher.
> >
> > For mod_python.publisher, see:
> >
> >  http://webpython.codepoint.net/mod_python_publisher_forms
> >
> > Graham
> >
> > 2008/4/29 Jon McKamey <jmcKamey@neatreceipts.com>:
> >
> >
> >
> > >
> > >
> > >
> > >
> > > Hey folks,
> > >
> > > I'm working on a project using mod_python, and for the most part I'm
> pretty
> > > happy with it, it rocks.  However I'm having some problems getting raw
> data
> > > via POST and a form.  The thread at
> > > http://www.modpython.org/pipermail/mod_python/2007-December/024547.html
> > > helped a lot, but I can't seem to get the last piece in place.
> > >
> > >
> > >
> > > If anyone can drop a simple example of an HTML page to go with the rest
> of
> > > that example, it would be a huge help.  I'm sure there is something
> simple
> > > with the HTML form ACTION or METHOD that I'm missing, but I just can't
> get
> > > an example to work.
> > >
> > >
> > >
> > > Thanks in advance for the help
> > >
> > >
> > >
> > > -jmck
> > >
> > >
> > >
> > >
> > > _______________________________________________
> > >  Mod_python mailing list
> > >  Mod_python@modpython.org
> > >  http://mailman.modpython.org/mailman/listinfo/mod_python
> > >
> > >
> > _______________________________________________
> > Mod_python mailing list
> > Mod_python@modpython.org
> > http://mailman.modpython.org/mailman/listinfo/mod_python
> >
>
>
>
> --
> Yangmin Li
> SoftWare College of Buaa
>
From liyangmin at gmail.com  Mon May  5 10:52:31 2008
From: liyangmin at gmail.com (liyangmin)
Date: Mon May  5 10:52:41 2008
Subject: [mod_python] Post of image data
In-Reply-To: <88e286470805050352o4d6359d8ia5773be5031f1f55@mail.gmail.com>
References: <45E36921B695A14FA56A34F29424A1EC011F9D5F@Apollo.neatreceipts.local>
	<88e286470804281504k4183e8d7y77f71d6a7bd209b5@mail.gmail.com>
	<e1ebd8c50805050313h692c3013k99bb28305a7c9d9e@mail.gmail.com>
	<88e286470805050352o4d6359d8ia5773be5031f1f55@mail.gmail.com>
Message-ID: <e1ebd8c50805050752u5889c98cg9161eb0f091056d3@mail.gmail.com>

thanks for the reply.

if I have the psp file as below,named index.psp:

<html><body>
<h2><%= message %></h2>
</body></html>

and the index.py:

def index(req):
    vars={"message":"hello python"}
    return psp.PSP(req, "index.psp", vars=vars)

I can deal with this case: but how about this one,how can I fill the
form data in the response:

<html><body>
<h2><%= message %></h2>
<form action="index" method="POST">
<center><input name="title" type="text" value="" /></center>
<br />
<center><input name="button" type="submit" value=""/></center>
</form
</body></html>

thanks a lot







2008/5/5 Graham Dumpleton <graham.dumpleton@gmail.com>:

> Please use reply-all and keep discussion on mod_python list.
>
> Anyway, I don't understand what you are asking. Do you simply mean how
> do you return a custom response?
>
> Did you go through the other parts of the tutorial at:
>
>  http://webpython.codepoint.net/
>
> including the other bits about mod_python.publisher such as the hello
> world example, which showed how responses are returned?
>
> Graham
>
> 2008/5/5 liyangmin <liyangmin@gmail.com>:
> > thanks a lot .  it helps a lot .
> > I have another question as below:
> > using req.form.getfirst()  method I can  read form data from a  request.
> > but How can i change the from data and  response  to the user?
> >
> > for example : I am using the template:
> >
> > <form action="show" method="POST">
> > <center><input name="path_name" type="text" value=""/> </center>
> > <center><input name="show_button" type="submit" value=""/></center>
> >  </form
> >
> > 2008/4/29 Graham Dumpleton <graham.dumpleton@gmail.com>:
> >
> >
> > > You don't say whether you are using raw mod_python handlers or
> > > mod_python.publisher.
> > >
> > > For mod_python.publisher, see:
> > >
> > >  http://webpython.codepoint.net/mod_python_publisher_forms
> > >
> > > Graham
> > >
> > > 2008/4/29 Jon McKamey <jmcKamey@neatreceipts.com>:
> > >
> > >
> > >
> > > >
> > > >
> > > >
> > > >
> > > > Hey folks,
> > > >
> > > > I'm working on a project using mod_python, and for the most part I'm
> > pretty
> > > > happy with it, it rocks.  However I'm having some problems getting
> raw
> > data
> > > > via POST and a form.  The thread at
> > > >
> http://www.modpython.org/pipermail/mod_python/2007-December/024547.html
> > > > helped a lot, but I can't seem to get the last piece in place.
> > > >
> > > >
> > > >
> > > > If anyone can drop a simple example of an HTML page to go with the
> rest
> > of
> > > > that example, it would be a huge help.  I'm sure there is something
> > simple
> > > > with the HTML form ACTION or METHOD that I'm missing, but I just
> can't
> > get
> > > > an example to work.
> > > >
> > > >
> > > >
> > > > Thanks in advance for the help
> > > >
> > > >
> > > >
> > > > -jmck
> > > >
> > > >
> > > >
> > > >
> > > > _______________________________________________
> > > >  Mod_python mailing list
> > > >  Mod_python@modpython.org
> > > >  http://mailman.modpython.org/mailman/listinfo/mod_python
> > > >
> > > >
> > > _______________________________________________
> > > Mod_python mailing list
> > > Mod_python@modpython.org
> > > http://mailman.modpython.org/mailman/listinfo/mod_python
> > >
> >
> >
> >
> > --
> > Yangmin Li
> > SoftWare College of Buaa
> >
>



-- 
Yangmin Li
SoftWare College of Buaa
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20080505/2fb3ddce/attachment.html
From John.Calixto at watchguard.com  Tue May  6 14:01:22 2008
From: John.Calixto at watchguard.com (John Calixto)
Date: Tue May  6 14:01:34 2008
Subject: [mod_python] just authenhandler
Message-ID: <1D4AF0FA9FFEEE44AF46F697C8A2A5140315BB4B@VS02SE.wgti.net>

Hi folks,

I'm trying to write an Apache handler just for authentication.  I have a
Python module that basically aggregates several user databases and
checks a username+password against the superset of users.

I can't seem to get any of the standard content handlers to process
things normally post-authentication.  Is there some example of an
authentication-only setup?  I'm interested in both the mod_python
handler implementation and the apache configuration.

With my current configuration, my Apache log shows:

... [error] [client 192.168.130.126] Attempt to serve directory:
/var/www/

If I disable my mod_python configuration from the <Directory /var/www/>
stanza, then mod_dir and/or mod_autoindex act normally.

Here's what I have now:


NameVirtualHost *
<VirtualHost *>
	ServerAdmin webmaster@localhost
	
	DocumentRoot /var/www/
	<Directory />
		Options FollowSymLinks
		AllowOverride None
	</Directory>
	<Directory /var/www/>
		Options Indexes FollowSymLinks MultiViews
		AllowOverride None
		Order allow,deny
		allow from all
		SetHandler mod_python
		PythonHandlerModule apacheauth
		PythonPath "sys.path+['/home/user/customauth']"
		PythonDebug On
		AuthType apacheauth
		Require customauth::valid-user
	</Directory>

	ErrorLog /var/log/apache2/error.log
	LogLevel debug
	CustomLog /var/log/apache2/access.log combined
	ServerSignature On

</VirtualHost>


========================================================================

from mod_python import apache
import authenticators
import base64

AUTHTYPE = 'apacheauth'
AUTHNAME = 'filez'
authen = authenticators.authen_shadow

def authenhandler(req):
    req.ap_auth_type = AUTHTYPE
    auth_header = req.headers_in.get('Authorization')
    req.log_error("auth_header [%s]" % auth_header, apache.APLOG_DEBUG)
    if auth_header:
        decoded = base64.b64decode(auth_header.split()[-1])
        username, password = decoded.split(':')
        if authen(username, password):
            req.log_error("authenticated!", apache.APLOG_DEBUG)
            req.user = username
            return apache.OK
    req.log_error("not authenticated!", apache.APLOG_DEBUG)
    req.err_headers_out['WWW-Authenticate'] = 'Basic realm="%s"' %
AUTHNAME
    return apache.HTTP_UNAUTHORIZED

def authzhandler(req):
    if req.user:
        req.log_error("authz handler user %s" % req.user,
apache.APLOG_INFO)
        return apache.OK
    return apache.HTTP_UNAUTHORIZED


========================================================================

Any pointers would be greatly appreciated.

Thanks,

John

From hauva at arska.org  Tue May  6 14:37:27 2008
From: hauva at arska.org (Ari Makela)
Date: Tue May  6 14:38:51 2008
Subject: [mod_python] just authenhandler
In-Reply-To: <1D4AF0FA9FFEEE44AF46F697C8A2A5140315BB4B@VS02SE.wgti.net>
References: <1D4AF0FA9FFEEE44AF46F697C8A2A5140315BB4B@VS02SE.wgti.net>
Message-ID: <20080506183723.GD27837@bowmore>

On Tue, May 06, 2008 at 11:01:22AM -0700, John Calixto wrote:

> I can't seem to get any of the standard content handlers to process
> things normally post-authentication.  Is there some example of an
> authentication-only setup?  I'm interested in both the mod_python
> handler implementation and the apache configuration.

> With my current configuration, my Apache log shows:
> 
> ... [error] [client 192.168.130.126] Attempt to serve directory:
> /var/www/
> 
> If I disable my mod_python configuration from the <Directory /var/www/>
> stanza, then mod_dir and/or mod_autoindex act normally.

I had the exact same problem when I needed an authenhandler which 
would do both NTLM authentication and some backup authentication 
for people who have not authenticated for the Windows network - like me 
as a linux user.

This works for me:

        <Location /pyauthtest >
                AuthType                Py
                Options                 Indexes ExecCGI
                PythonAuthenHandler     pyauthhandler
                PythonDebug             On
                PythonOption            Groups Foo,Bar,Baz
                PythonOption            ServerRoot  /var/www/instance
                require                 valid-user
        </Location>

I'm sorry but I cannot show the python code without the permission of 
my employer.

-- 
Ari Makela                                               late autumn -
hauva@arska.org                           	a single chair waiting
http://arska.org/hauva/           		for someone yet to come 
							 -- Arima Akito
From John.Calixto at watchguard.com  Tue May  6 14:52:53 2008
From: John.Calixto at watchguard.com (John Calixto)
Date: Tue May  6 14:53:04 2008
Subject: [mod_python] just authenhandler
In-Reply-To: <20080506183723.GD27837@bowmore>
References: <1D4AF0FA9FFEEE44AF46F697C8A2A5140315BB4B@VS02SE.wgti.net>
	<20080506183723.GD27837@bowmore>
Message-ID: <1D4AF0FA9FFEEE44AF46F697C8A2A5140315BB90@VS02SE.wgti.net>

> This works for me:
> 
>         <Location /pyauthtest >
>                 AuthType                Py
>                 Options                 Indexes ExecCGI
>                 PythonAuthenHandler     pyauthhandler
>                 PythonDebug             On
>                 PythonOption            Groups Foo,Bar,Baz
>                 PythonOption            ServerRoot  /var/www/instance
>                 require                 valid-user
>         </Location>
> 

Thanks Ari.

Do you also have a <Directory> stanza in your apache config?  Or are you
doing some magic with the ServerRoot value to effectively build up an
index yourself?

John

From John.Calixto at watchguard.com  Tue May  6 15:36:15 2008
From: John.Calixto at watchguard.com (John Calixto)
Date: Tue May  6 15:36:27 2008
Subject: [mod_python] just authenhandler SOLVED
References: <1D4AF0FA9FFEEE44AF46F697C8A2A5140315BB4B@VS02SE.wgti.net>
	<20080506183723.GD27837@bowmore> 
Message-ID: <1D4AF0FA9FFEEE44AF46F697C8A2A5140315BBC0@VS02SE.wgti.net>

> > This works for me:
> > 
> >         <Location /pyauthtest >
> >                 AuthType                Py
> >                 Options                 Indexes ExecCGI
> >                 PythonAuthenHandler     pyauthhandler
> >                 PythonDebug             On
> >                 PythonOption            Groups Foo,Bar,Baz
> >                 PythonOption            ServerRoot  
> /var/www/instance
> >                 require                 valid-user
> >         </Location>
> > 
> 
> Thanks Ari.
> 
> Do you also have a <Directory> stanza in your apache config?  
> Or are you doing some magic with the ServerRoot value to 
> effectively build up an index yourself?
> 
> John


OK, I found something that works for me.  Ari's configuration prompted
me to try removing the SetHandler directive.  By using just the
PythonAuthenHandler and PythonAuthzHandler directives, I got the desired
effect.  It makes sense - I just didn't understand how Set/AddHandler
interacted with the rest of mod_python.

Here's my final, working configuration:


<VirtualHost *>
	ServerAdmin webmaster@localhost
	
	DocumentRoot /var/www/
	<Directory />
		Options FollowSymLinks
		AllowOverride None
	</Directory>
	<Directory /var/www/>
		Options Indexes FollowSymLinks MultiViews
		AllowOverride None
		Order allow,deny
		allow from all

            # Notice no SetHandler directive!
		AuthType customauth
		PythonAuthenHandler apacheauth
		PythonAuthzHandler apacheauth
		PythonPath "sys.path+['/home/user/customauth']"
		PythonDebug On
		Require customauth::valid-user
	</Directory>

	ErrorLog /var/log/apache2/error.log
	LogLevel debug

	CustomLog /var/log/apache2/access.log combined
	ServerSignature On

</VirtualHost>


=================================================================


from mod_python import apache
import authenticators
import base64

AUTHTYPE = 'customauth'
AUTHNAME = 'Custom Auth'
authen = authenticators.authen_shadow

def authenhandler(req):
    req.ap_auth_type = AUTHTYPE
    auth_header = req.headers_in.get('Authorization')
    if auth_header:
        decoded = base64.b64decode(auth_header.split()[-1])
        username, password = decoded.split(':')
        if authen(username, password):
            req.log_error("authenticated!", apache.APLOG_DEBUG)
            req.user = username
            return apache.OK
    req.log_error("not authenticated!", apache.APLOG_DEBUG)
    req.err_headers_out['WWW-Authenticate'] = 'Basic realm="%s"' %
AUTHNAME
    return apache.HTTP_UNAUTHORIZED

def authzhandler(req):
    if req.user:
        # do any extra checking against groups, requires, etc.
        req.log_error("authorized user %s" % req.user,
apache.APLOG_DEBUG)
        return apache.OK
    return apache.HTTP_UNAUTHORIZED


=================================================================

Maybe I missed it in the documentation, but it would be really nice to
have something stating the interaction between AddHandler/SetHandler,
and mod_python.

Thanks for reading,

John

From graham.dumpleton at gmail.com  Tue May  6 19:14:16 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Tue May  6 19:14:22 2008
Subject: [mod_python] just authenhandler SOLVED
In-Reply-To: <1D4AF0FA9FFEEE44AF46F697C8A2A5140315BBC0@VS02SE.wgti.net>
References: <1D4AF0FA9FFEEE44AF46F697C8A2A5140315BB4B@VS02SE.wgti.net>
	<20080506183723.GD27837@bowmore>
	<1D4AF0FA9FFEEE44AF46F697C8A2A5140315BBC0@VS02SE.wgti.net>
Message-ID: <88e286470805061614gbc5e74dpe4dff2087ea9ed4a@mail.gmail.com>

The AddHandler/SetHandler only apply to the actual content handler and
has nothing to do with other phases of processing. Read:

  http://www.dscpl.com.au/wiki/ModPython/Articles/SetHandlerVersusAddHandler

In short, only use SetHandler with mod_python if defining PythonHandler.

Because mod_python isn't a standalone system, you also need to
understand how Apache works. Since SetHandler/AddHandler are
implemented by core Apache modules and not mod_python, you also need
to read Apache documentation for those directives.

Graham

2008/5/7 John Calixto <John.Calixto@watchguard.com>:
> > > This works for me:
>  > >
>  > >         <Location /pyauthtest >
>  > >                 AuthType                Py
>  > >                 Options                 Indexes ExecCGI
>  > >                 PythonAuthenHandler     pyauthhandler
>  > >                 PythonDebug             On
>  > >                 PythonOption            Groups Foo,Bar,Baz
>  > >                 PythonOption            ServerRoot
>  > /var/www/instance
>  > >                 require                 valid-user
>  > >         </Location>
>  > >
>  >
>  > Thanks Ari.
>  >
>  > Do you also have a <Directory> stanza in your apache config?
>  > Or are you doing some magic with the ServerRoot value to
>  > effectively build up an index yourself?
>  >
>  > John
>
>
>  OK, I found something that works for me.  Ari's configuration prompted
>  me to try removing the SetHandler directive.  By using just the
>  PythonAuthenHandler and PythonAuthzHandler directives, I got the desired
>  effect.  It makes sense - I just didn't understand how Set/AddHandler
>  interacted with the rest of mod_python.
>
>  Here's my final, working configuration:
>
>
>  <VirtualHost *>
>         ServerAdmin webmaster@localhost
>
>         DocumentRoot /var/www/
>         <Directory />
>                 Options FollowSymLinks
>                 AllowOverride None
>         </Directory>
>         <Directory /var/www/>
>                 Options Indexes FollowSymLinks MultiViews
>                 AllowOverride None
>                 Order allow,deny
>                 allow from all
>
>             # Notice no SetHandler directive!
>                 AuthType customauth
>                 PythonAuthenHandler apacheauth
>                 PythonAuthzHandler apacheauth
>                 PythonPath "sys.path+['/home/user/customauth']"
>                 PythonDebug On
>                 Require customauth::valid-user
>         </Directory>
>
>         ErrorLog /var/log/apache2/error.log
>         LogLevel debug
>
>         CustomLog /var/log/apache2/access.log combined
>         ServerSignature On
>
>  </VirtualHost>
>
>
>  =================================================================
>
>
>  from mod_python import apache
>  import authenticators
>  import base64
>
>  AUTHTYPE = 'customauth'
>  AUTHNAME = 'Custom Auth'
>  authen = authenticators.authen_shadow
>
>  def authenhandler(req):
>     req.ap_auth_type = AUTHTYPE
>     auth_header = req.headers_in.get('Authorization')
>     if auth_header:
>         decoded = base64.b64decode(auth_header.split()[-1])
>         username, password = decoded.split(':')
>         if authen(username, password):
>             req.log_error("authenticated!", apache.APLOG_DEBUG)
>             req.user = username
>             return apache.OK
>     req.log_error("not authenticated!", apache.APLOG_DEBUG)
>     req.err_headers_out['WWW-Authenticate'] = 'Basic realm="%s"' %
>  AUTHNAME
>     return apache.HTTP_UNAUTHORIZED
>
>  def authzhandler(req):
>     if req.user:
>         # do any extra checking against groups, requires, etc.
>         req.log_error("authorized user %s" % req.user,
>  apache.APLOG_DEBUG)
>         return apache.OK
>     return apache.HTTP_UNAUTHORIZED
>
>
>  =================================================================
>
>  Maybe I missed it in the documentation, but it would be really nice to
>  have something stating the interaction between AddHandler/SetHandler,
>  and mod_python.
>
>  Thanks for reading,
>
>  John
>
>  _______________________________________________
>  Mod_python mailing list
>  Mod_python@modpython.org
>  http://mailman.modpython.org/mailman/listinfo/mod_python
>
From John.Calixto at watchguard.com  Tue May  6 19:20:55 2008
From: John.Calixto at watchguard.com (John Calixto)
Date: Tue May  6 19:21:06 2008
Subject: [mod_python] just authenhandler SOLVED
In-Reply-To: <88e286470805061614gbc5e74dpe4dff2087ea9ed4a@mail.gmail.com>
References: <1D4AF0FA9FFEEE44AF46F697C8A2A5140315BB4B@VS02SE.wgti.net>
	<20080506183723.GD27837@bowmore>
	<1D4AF0FA9FFEEE44AF46F697C8A2A5140315BBC0@VS02SE.wgti.net>
	<88e286470805061614gbc5e74dpe4dff2087ea9ed4a@mail.gmail.com>
Message-ID: <1D4AF0FA9FFEEE44AF46F697C8A2A5140315BC74@VS02SE.wgti.net>

> 
> The AddHandler/SetHandler only apply to the actual content handler and
> has nothing to do with other phases of processing. Read:
> 
>   
> http://www.dscpl.com.au/wiki/ModPython/Articles/SetHandlerVers
> usAddHandler
> 


Thanks Graham!  That's precisely what I needed to fill in the gaps in my
understanding.



From emyr.thomas at gmail.com  Thu May  8 07:22:29 2008
From: emyr.thomas at gmail.com (Emyr Thomas)
Date: Thu May  8 07:22:56 2008
Subject: [mod_python] Re: Re: Problem with mod_proxy + inputfilter +
	headers_in
References: <e79469d0704190821x12a0ffa9ve94e9d13e37898e6@mail.gmail.com><88e286470704191453o5b0b3c08u77b14064c1f58950@mail.gmail.com><fv4l0s$5ee$1@ger.gmane.org><88e286470804281402r6c51f2ccxc5ac9ffb69c446d@mail.gmail.com><88e286470804281409g238ccec9vc142fba258e8105e@mail.gmail.com><8fb874820804290215l71dcd9afjd39f86f683d4e34b@mail.gmail.com>
	<88e286470804290326s691ebceas83223500c968bc29@mail.gmail.com>
Message-ID: <fvunpq$7bi$1@ger.gmane.org>

"Graham Dumpleton" 
<graham.dumpleton@gmail.com> wrote in message 
news:88e286470804290326s691ebceas83223500c968bc29@mail.gmail.com...
> I never understood why
> tramline was even implemented in mod_python as mod_python input/output
> filters aren't that efficient. You would be much better off doing it
> as a special purpose C module for Apache, and most likely such a thing
> does exist if one looked hard enough.

So I'm thinking I might have a crack at rewriting tramline as a C module.
Any advice and pointers to helpful docs would be gratefully received as I've 
never really written anything in C before :-S

Thanks

--Emyr 



From graham.dumpleton at gmail.com  Thu May  8 07:36:07 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Thu May  8 07:36:16 2008
Subject: [mod_python] Re: Re: Problem with mod_proxy + inputfilter +
	headers_in
In-Reply-To: <fvunpq$7bi$1@ger.gmane.org>
References: <e79469d0704190821x12a0ffa9ve94e9d13e37898e6@mail.gmail.com>
	<88e286470704191453o5b0b3c08u77b14064c1f58950@mail.gmail.com>
	<fv4l0s$5ee$1@ger.gmane.org>
	<88e286470804281402r6c51f2ccxc5ac9ffb69c446d@mail.gmail.com>
	<88e286470804281409g238ccec9vc142fba258e8105e@mail.gmail.com>
	<8fb874820804290215l71dcd9afjd39f86f683d4e34b@mail.gmail.com>
	<88e286470804290326s691ebceas83223500c968bc29@mail.gmail.com>
	<fvunpq$7bi$1@ger.gmane.org>
Message-ID: <88e286470805080436w3de60fa2vfd68f718678e4479@mail.gmail.com>

2008/5/8 Emyr Thomas <emyr.thomas@gmail.com>:
> "Graham Dumpleton"
> <graham.dumpleton@gmail.com> wrote in message
> news:88e286470804290326s691ebceas83223500c968bc29@mail.gmail.com...
>> I never understood why
>> tramline was even implemented in mod_python as mod_python input/output
>> filters aren't that efficient. You would be much better off doing it
>> as a special purpose C module for Apache, and most likely such a thing
>> does exist if one looked hard enough.
>
> So I'm thinking I might have a crack at rewriting tramline as a C module.
> Any advice and pointers to helpful docs would be gratefully received as I've
> never really written anything in C before :-S

Start out with:

http://www.projectcomputing.com/resources/apacheFilterFAQ/

Graham
From dougfritz at gmail.com  Thu May  8 13:48:21 2008
From: dougfritz at gmail.com (Doug Fritz)
Date: Thu May  8 13:48:32 2008
Subject: [mod_python] mod_python Session
Message-ID: <6DE5A829-7D0A-442F-A286-235B73FB0D5C@gmail.com>

creating a session request

     session = Session.Session(req)

Is causing my app to just hang, it is not creating a failure it is  
just stuck in an infinite loop.  I have isolated the problem to this  
line, but there is little documentation on the session code  
available.  At one point I had set the timeout to be rather long, and  
am curious if that is causing the issue?  This was previously working  
well.  I have tried restarting and rebooting the server to clear any  
session data in memory.  Is there a way to hard reset the session  
data?  Any thoughts would greatly appreciated.

thanks,
doug
From graham.dumpleton at gmail.com  Thu May  8 17:30:50 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Thu May  8 17:30:56 2008
Subject: [mod_python] mod_python Session
In-Reply-To: <6DE5A829-7D0A-442F-A286-235B73FB0D5C@gmail.com>
References: <6DE5A829-7D0A-442F-A286-235B73FB0D5C@gmail.com>
Message-ID: <88e286470805081430lcce158dv33b9dda1ad981641@mail.gmail.com>

Search the past mailing list archives:

  http://www.google.com/search?q=session+deadlock&q=site%3Awww.modpython.org

This has come up many times before.

Someone with more time may be able to explain more if that doesn't help.

Graham

2008/5/9 Doug Fritz <dougfritz@gmail.com>:
> creating a session request
>
>     session = Session.Session(req)
>
>  Is causing my app to just hang, it is not creating a failure it is just
> stuck in an infinite loop.  I have isolated the problem to this line, but
> there is little documentation on the session code available.  At one point I
> had set the timeout to be rather long, and am curious if that is causing the
> issue?  This was previously working well.  I have tried restarting and
> rebooting the server to clear any session data in memory.  Is there a way to
> hard reset the session data?  Any thoughts would greatly appreciated.
>
>  thanks,
>  doug
>  _______________________________________________
>  Mod_python mailing list
>  Mod_python@modpython.org
>  http://mailman.modpython.org/mailman/listinfo/mod_python
>
From davidj411 at gmail.com  Fri May  9 14:27:07 2008
From: davidj411 at gmail.com (David Jackson)
Date: Fri May  9 14:29:05 2008
Subject: [mod_python] mod_python installation failure on apache
Message-ID: <491b0d8f0805091127v28583a91md9133edd28702ab6@mail.gmail.com>

I followed the directions at
http://www.modpython.org/live/current/doc-html/inst-testing.html
and get contents of the script mptest.py , not the results as if it had run.


if i run the mptest.py script from the command line, i get this import
error.

C:\apache\htdocs\py>mptest.py
Traceback (most recent call last):
  File "C:\apache\htdocs\py\mptest.py", line 1, in <module>
    from mod_python import apache
  File "C:\Python25\lib\site-packages\mod_python\apache.py", line 30, in
<module>
    import _apache
ImportError: No module named _apache

I have rebooted and restarted apache. It looks like the script
apache.py mis-typed "apache" as "_apache" ?
if i swap the contents of the mptest.py with something simple like

print "hello"

the entire line shows up in the browser as

print "hello"


  *system settings:*
General information
Apache version Apache/2.2.8 (Win32) mod_python/3.3.1 Python/2.5.2
Apache threaded MPM Yes, maximum 64 threads / process
Apache forked MPM No (single process MPM)
Apache server root C:/apache
Apache document root C:/apache/htdocs
Apache error log C:/apache\logs/error.log (view last 100 lines)
Python sys.version 2.5.2 (r252:60911, Feb 21 2008, 13:11:45) [MSC v.1310 32
bit (Intel)]
Python sys.path C:\WINDOWS\system32\python25.zip
C:\Python25\Lib
C:\Python25\DLLs
C:\Python25\Lib\lib-tk
C:\apache
C:\apache\bin
C:\Python25
C:\Python25\lib\site-packages
C:\Python25\lib\site-packages\win32
C:\Python25\lib\site-packages\win32\lib
C:\Python25\lib\site-packages\Pythonwin
 Python interpreter name dsg-vyvo2o2ijzo.domainname.usa
mod_python.publisher available Yes
mod_python.psp available Yes
 Request input headers
Key Value
Accept image/gif, image/x-xbitmap, image/jpeg, image/pjpeg,
application/x-shockwave-flash, application/x-ms-application,
application/x-ms-xbap, application/vnd.ms-xpsdocument, application/xaml+xml,
application/x-silverlight, application/vnd.ms-excel,
application/vnd.ms-powerpoint, application/msword, */*
Accept-Language en-us
UA-CPU x86
Accept-Encoding gzip, deflate
User-Agent Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR
2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022)
Host localhost
Connection Keep-Alive
 Request environment
Key Value
GATEWAY_INTERFACE CGI/1.1
SERVER_PROTOCOL HTTP/1.1
REQUEST_METHOD GET
QUERY_STRING
REQUEST_URI /mpinfo
SCRIPT_NAME /mpinfo
HTTP_ACCEPT image/gif, image/x-xbitmap, image/jpeg, image/pjpeg,
application/x-shockwave-flash, application/x-ms-application,
application/x-ms-xbap, application/vnd.ms-xpsdocument, application/xaml+xml,
application/x-silverlight, application/vnd.ms-excel,
application/vnd.ms-powerpoint, application/msword, */*
HTTP_ACCEPT_LANGUAGE en-us
HTTP_UA_CPU x86
HTTP_ACCEPT_ENCODING gzip, deflate
HTTP_USER_AGENT Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR
2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022)
HTTP_HOST localhost
HTTP_CONNECTION Keep-Alive
PATH
C:\Path;C:\Temp\path\scripts;C:\Path\3rdparty\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;c:\Program
Files\Microsoft SQL Server\90\Tools\binn\;C:\Program Files\Common
Files\Roxio Shared\DLLShared\;C:\Program Files\Common Files\Roxio
Shared\DLLShared\;C:\Program Files\Common Files\Roxio
Shared\9.0\DLLShared\;C:\WINDOWS\system32\WindowsPowerShell\v1.0
SystemRoot C:\WINDOWS
COMSPEC C:\WINDOWS\system32\cmd.exe
PATHEXT .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.PSC1
WINDIR C:\WINDOWS
SERVER_SIGNATURE
SERVER_SOFTWARE Apache/2.2.8 (Win32) mod_python/3.3.1 Python/2.5.2
SERVER_NAME localhost
SERVER_ADDR 127.0.0.1
SERVER_PORT 80
REMOTE_ADDR 127.0.0.1
DOCUMENT_ROOT C:/apache/htdocs
SERVER_ADMIN djackson@dsolutionsgroup.com
SCRIPT_FILENAME C:/apache/htdocs/mpinfo
REMOTE_PORT 1354
 Request configuration
Key Value
 Request options
Key Value
 Request notes
Key Value
python_init_ran 1
 Server configuration
Key Value
 Server options
Key Value
 Server configuration tree
Listen 80
ServerAdmin djackson@dsolutionsgroup.com
DocumentRoot "C:/apache/htdocs"
    Options FollowSymLinks
   AllowOverride None
   Order deny,allow
   Deny from all
    AddHandler mod_python .py
   PythonHandler mptest
   PythonDebug On
    SetHandler mod_python
   PythonHandler mod_python.testhandler
    Options Indexes FollowSymLinks
   AllowOverride None
   Order allow,deny
   Allow from all
DirectoryIndex index.html
    Order allow,deny
   Deny from all
   Satisfy All
ErrorLog "logs/error.log"
LogLevel warn
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\""
combined
LogFormat "%h %l %u %t \"%r\" %>s %b" common
CustomLog "logs/access.log" common
ScriptAlias /cgi-bin/ "C:/apache/cgi-bin/"
    AllowOverride None
   Options None
   Order allow,deny
   Allow from all
DefaultType text/plain
TypesConfig conf/mime.types
AddType application/x-compress .Z
AddType application/x-gzip .gz .tgz
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20080509/adc55ba9/attachment.html
From davidj411 at gmail.com  Fri May  9 14:40:16 2008
From: davidj411 at gmail.com (David Jackson)
Date: Fri May  9 14:40:25 2008
Subject: [mod_python] [SPAM] Re: mod_python installation failure on apache
In-Reply-To: <491b0d8f0805091127v28583a91md9133edd28702ab6@mail.gmail.com>
References: <491b0d8f0805091127v28583a91md9133edd28702ab6@mail.gmail.com>
Message-ID: <491b0d8f0805091140u3b86e398l415e8218ade644c@mail.gmail.com>

more info, the apache module does not seem to exist in mod_python.
is that what this means?

import mod_python
>>> dir (mod_python)
['__all__', '__builtins__', '__doc__', '__file__', '__name__', '__path__',
'version']

>>> print mod_python.version
3.3.1

On Fri, May 9, 2008 at 2:27 PM, David Jackson <davidj411@gmail.com> wrote:

> I followed the directions at
> http://www.modpython.org/live/current/doc-html/inst-testing.html
> and get contents of the script mptest.py , not the results as if it had
> run.
>
> if i run the mptest.py script from the command line, i get this import
> error.
>
> C:\apache\htdocs\py>mptest.py
> Traceback (most recent call last):
>   File "C:\apache\htdocs\py\mptest.py", line 1, in <module>
>     from mod_python import apache
>   File "C:\Python25\lib\site-packages\mod_python\apache.py", line 30, in
> <module>
>     import _apache
> ImportError: No module named _apache
>
> I have rebooted and restarted apache. It looks like the script
> apache.py mis-typed "apache" as "_apache" ?
> if i swap the contents of the mptest.py with something simple like
>
> print "hello"
>
> the entire line shows up in the browser as
>
> print "hello"
>
>
>   *system settings:*
> General information
> Apache version Apache/2.2.8 (Win32) mod_python/3.3.1 Python/2.5.2
> Apache threaded MPM Yes, maximum 64 threads / process
> Apache forked MPM No (single process MPM)
> Apache server root C:/apache
> Apache document root C:/apache/htdocs
> Apache error log C:/apache\logs/error.log (view last 100 lines)
> Python sys.version 2.5.2 (r252:60911, Feb 21 2008, 13:11:45) [MSC v.1310 32
> bit (Intel)]
> Python sys.path C:\WINDOWS\system32\python25.zip
> C:\Python25\Lib
> C:\Python25\DLLs
> C:\Python25\Lib\lib-tk
> C:\apache
> C:\apache\bin
> C:\Python25
> C:\Python25\lib\site-packages
> C:\Python25\lib\site-packages\win32
> C:\Python25\lib\site-packages\win32\lib
> C:\Python25\lib\site-packages\Pythonwin
>  Python interpreter name dsg-vyvo2o2ijzo.domainname.usa
> mod_python.publisher available Yes
> mod_python.psp available Yes
>  Request input headers
> Key Value
> Accept image/gif, image/x-xbitmap, image/jpeg, image/pjpeg,
> application/x-shockwave-flash, application/x-ms-application,
> application/x-ms-xbap, application/vnd.ms-xpsdocument, application/xaml+xml,
> application/x-silverlight, application/vnd.ms-excel,
> application/vnd.ms-powerpoint, application/msword, */*
> Accept-Language en-us
> UA-CPU x86
> Accept-Encoding gzip, deflate
> User-Agent Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR
> 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022)
> Host localhost
> Connection Keep-Alive
>  Request environment
> Key Value
> GATEWAY_INTERFACE CGI/1.1
> SERVER_PROTOCOL HTTP/1.1
> REQUEST_METHOD GET
> QUERY_STRING
> REQUEST_URI /mpinfo
> SCRIPT_NAME /mpinfo
> HTTP_ACCEPT image/gif, image/x-xbitmap, image/jpeg, image/pjpeg,
> application/x-shockwave-flash, application/x-ms-application,
> application/x-ms-xbap, application/vnd.ms-xpsdocument, application/xaml+xml,
> application/x-silverlight, application/vnd.ms-excel,
> application/vnd.ms-powerpoint, application/msword, */*
> HTTP_ACCEPT_LANGUAGE en-us
> HTTP_UA_CPU x86
> HTTP_ACCEPT_ENCODING gzip, deflate
> HTTP_USER_AGENT Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR
> 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022)
> HTTP_HOST localhost
> HTTP_CONNECTION Keep-Alive
> PATH
> C:\Path;C:\Temp\path\scripts;C:\Path\3rdparty\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;c:\Program
> Files\Microsoft SQL Server\90\Tools\binn\;C:\Program Files\Common
> Files\Roxio Shared\DLLShared\;C:\Program Files\Common Files\Roxio
> Shared\DLLShared\;C:\Program Files\Common Files\Roxio
> Shared\9.0\DLLShared\;C:\WINDOWS\system32\WindowsPowerShell\v1.0
> SystemRoot C:\WINDOWS
> COMSPEC C:\WINDOWS\system32\cmd.exe
> PATHEXT .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.PSC1
> WINDIR C:\WINDOWS
> SERVER_SIGNATURE
> SERVER_SOFTWARE Apache/2.2.8 (Win32) mod_python/3.3.1 Python/2.5.2
> SERVER_NAME localhost
> SERVER_ADDR 127.0.0.1
> SERVER_PORT 80
> REMOTE_ADDR 127.0.0.1
> DOCUMENT_ROOT C:/apache/htdocs
> SERVER_ADMIN djackson@dsolutionsgroup.com
> SCRIPT_FILENAME C:/apache/htdocs/mpinfo
> REMOTE_PORT 1354
>  Request configuration
> Key Value
>  Request options
> Key Value
>  Request notes
> Key Value
> python_init_ran 1
>  Server configuration
> Key Value
>  Server options
> Key Value
>  Server configuration tree
> Listen 80
> ServerAdmin djackson@dsolutionsgroup.com
> DocumentRoot "C:/apache/htdocs"
>     Options FollowSymLinks
>    AllowOverride None
>    Order deny,allow
>    Deny from all
>     AddHandler mod_python .py
>    PythonHandler mptest
>    PythonDebug On
>     SetHandler mod_python
>    PythonHandler mod_python.testhandler
>     Options Indexes FollowSymLinks
>    AllowOverride None
>    Order allow,deny
>    Allow from all
> DirectoryIndex index.html
>     Order allow,deny
>    Deny from all
>    Satisfy All
> ErrorLog "logs/error.log"
> LogLevel warn
> LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\""
> combined
> LogFormat "%h %l %u %t \"%r\" %>s %b" common
> CustomLog "logs/access.log" common
> ScriptAlias /cgi-bin/ "C:/apache/cgi-bin/"
>     AllowOverride None
>    Options None
>    Order allow,deny
>    Allow from all
> DefaultType text/plain
> TypesConfig conf/mime.types
> AddType application/x-compress .Z
> AddType application/x-gzip .gz .tgz
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20080509/be0088af/attachment-0001.html
From gzlist at googlemail.com  Fri May  9 15:41:33 2008
From: gzlist at googlemail.com (Martin (gzlist))
Date: Fri May  9 15:41:39 2008
Subject: [mod_python] [SPAM] Re: mod_python installation failure on apache
In-Reply-To: <491b0d8f0805091140u3b86e398l415e8218ade644c@mail.gmail.com>
References: <491b0d8f0805091127v28583a91md9133edd28702ab6@mail.gmail.com>
	<491b0d8f0805091140u3b86e398l415e8218ade644c@mail.gmail.com>
Message-ID: <d80792120805091241g4db1371axfaf9b58fb9249d7e@mail.gmail.com>

> On Fri, May 9, 2008 at 2:27 PM, David Jackson <davidj411@gmail.com> wrote:
> > I followed the directions at
> http://www.modpython.org/live/current/doc-html/inst-testing.html
> > and get contents of the script mptest.py , not the results as if it had
> run.

I think people often have this problem, for one reason or another.
Have you searched the mailing list archives?

An even simpler test to see if you've got the basic installation right
is to add to your httpd.conf file:

# with the module imported further up:
#LoadModule python_module modules/mod_python.so
<Location /mpinfo>
	SetHandler mod_python
	PythonHandler mod_python.testhandler
	Order deny,allow
	Deny from all
	Allow from 127.0
</Location>

Restart, then visit http://localhost/mpinfo as see if you get the page.

> > if i run the mptest.py script from the command line, i get this import
> error.
> >
> > C:\apache\htdocs\py>mptest.py
> > Traceback (most recent call last):
> >   File "C:\apache\htdocs\py\mptest.py", line 1, in
> <module>
> >     from mod_python import apache
> >   File
> "C:\Python25\lib\site-packages\mod_python\apache.py", line
> 30, in <module>
> >     import _apache
> > ImportError: No module named _apache
> >
> > I have rebooted and restarted apache. It looks like the script apache.py
> mis-typed "apache" as "_apache" ?

No, _apache is the C module mod_python needs to interface with the
http server. It only exists when running from within the httpd, you
can't run scripts independently from the command line.

On 09/05/2008, David Jackson <davidj411@gmail.com> wrote:
> more info, the apache module does not seem to exist in mod_python.
> is that what this means?
>
> import mod_python
> >>> dir (mod_python)
> ['__all__', '__builtins__', '__doc__', '__file__', '__name__', '__path__',
> 'version']

This is normal, modules need not import their sub-modules by default:

>>> import xml
>>> "dom" in dir(xml)
False
>>> import xml.dom
>>> "dom" in dir(xml)
True

Martin
From gzlist at googlemail.com  Fri May  9 17:58:51 2008
From: gzlist at googlemail.com (Martin (gzlist))
Date: Fri May  9 17:58:58 2008
Subject: [mod_python] [SPAM] Re: mod_python installation failure on apache
In-Reply-To: <d80792120805091241g4db1371axfaf9b58fb9249d7e@mail.gmail.com>
References: <491b0d8f0805091127v28583a91md9133edd28702ab6@mail.gmail.com>
	<491b0d8f0805091140u3b86e398l415e8218ade644c@mail.gmail.com>
	<d80792120805091241g4db1371axfaf9b58fb9249d7e@mail.gmail.com>
Message-ID: <d80792120805091458w394d0550v3b723a1e7d377f18@mail.gmail.com>

On 09/05/2008, Martin (gzlist) <gzlist@googlemail.com> wrote:
>  An even simpler test to see if you've got the basic installation right
>  is to add to your httpd.conf file:
>
>  # with the module imported further up:
>  #LoadModule python_module modules/mod_python.so
>  <Location /mpinfo>
>
>         SetHandler mod_python
>         PythonHandler mod_python.testhandler
>
>         Order deny,allow
>         Deny from all
>
>         Allow from 127.0
>  </Location>
>
>  Restart, then visit http://localhost/mpinfo as see if you get the page.

Sorry, didn't mean to suggest this when you've obviously already got
that far from the first email. Got distracted looking at the the
second one and clearly had a brain-collapse.

Looking at the httpd.conf from the bottom of that readout, it seems
(though it's rather hard to tell with the hilarious lack of html
escaping in the info handler) you've got pretty much what the tutorial
asks for. However, I suspect you've got the Directory wrong. You need
to give it as either an absolute path, or relative to the server root
(not document root!).

# WRONG # <Directory /test>
<Directory C:/apache/htdocs/test> # RIGHT #

Attached a from-blank httpd.conf that works for me with ServerRoot as
"C:/Program Files/Apache2.2/" DocumentRoot as "C:/Program
Files/Apache2.2/htdocs" and the script at "C:/Program
Files/Apache2.2/htdocs/test/mptest.py", which might help get going.

Don't know what the tutorial persists with the CGI confusion between
running a script, and fetching a resource, SetHandler really is a
better way.

Martin
-------------- next part --------------

LoadModule authz_host_module modules/mod_authz_host.so
LoadModule mime_module modules/mod_mime.so
LoadModule python_module modules/mod_python.so

Listen 80

ErrorLog logs/error.log

DocumentRoot htdocs

<Directory />
	Options None
	AllowOverride None
	Order deny,allow
	Deny from all
	Allow from 127.0
</Directory>

PythonOption mod_python.importer.path "['htdocs/test']"
PythonDebug On

<Location /mpinfo>
	SetHandler mod_python
	PythonHandler mod_python.testhandler
</Location>

<Location /mptest>
	SetHandler mod_python
	PythonHandler mptest
</Location>

# This is wrong, would give you the script as text
#<Directory /test>
#	AddHandler mod_python .py
#	PythonHandler mptest
#</Directory>

# This is the right way
<Directory htdocs/test>
	AddHandler mod_python .py
	PythonHandler mptest
</Directory>
From John.Calixto at watchguard.com  Fri May  9 18:11:02 2008
From: John.Calixto at watchguard.com (John Calixto)
Date: Fri May  9 18:11:07 2008
Subject: [mod_python] [SPAM] Re: mod_python installation failure on apache
In-Reply-To: <491b0d8f0805091140u3b86e398l415e8218ade644c@mail.gmail.com>
References: <491b0d8f0805091127v28583a91md9133edd28702ab6@mail.gmail.com>
	<491b0d8f0805091140u3b86e398l415e8218ade644c@mail.gmail.com>
Message-ID: <1D4AF0FA9FFEEE44AF46F697C8A2A5140315C409@VS02SE.wgti.net>

> 
> 	I followed the directions at 
> http://www.modpython.org/live/current/doc-html/inst-testing.html
> 	and get contents of the script mptest.py , not the 
> results as if it had run. 

First, it would help to see the actual apache configuration.  You seem
to have pasted stuff a bunch of stuff without the enclosing tags.

Also, just based on what I could intuit from your pasted apache
configuration, it needs fixing:

>   PythonHandler mptest
>   PythonDebug On
>   SetHandler mod_python
>   PythonHandler mod_python.testhandler

See how you have 2 PythonHandlers?



> 	 
> 	if i run the mptest.py script from the command line, i 
> get this import error.
> 	 


It doesn't make sense to run mod_python stuff outside of Apache.

http://www.modpython.org/FAQ/faqw.py?req=all#2.2


John

From gzlist at googlemail.com  Fri May  9 18:39:20 2008
From: gzlist at googlemail.com (Martin (gzlist))
Date: Fri May  9 18:39:27 2008
Subject: [mod_python] [SPAM] Re: mod_python installation failure on apache
In-Reply-To: <1D4AF0FA9FFEEE44AF46F697C8A2A5140315C409@VS02SE.wgti.net>
References: <491b0d8f0805091127v28583a91md9133edd28702ab6@mail.gmail.com>
	<491b0d8f0805091140u3b86e398l415e8218ade644c@mail.gmail.com>
	<1D4AF0FA9FFEEE44AF46F697C8A2A5140315C409@VS02SE.wgti.net>
Message-ID: <d80792120805091539w2e4d0419vfd13b876c0c2c317@mail.gmail.com>

On 09/05/2008, John Calixto <John.Calixto@watchguard.com> wrote:
> >
>  >       I followed the directions at
>  > http://www.modpython.org/live/current/doc-html/inst-testing.html
>  >       and get contents of the script mptest.py , not the
>  > results as if it had run.
>
>
> First, it would help to see the actual apache configuration.  You seem
>  to have pasted stuff a bunch of stuff without the enclosing tags.

That's the dumbness of mod_python/testhandler.py at work. Like a
little lesson in how *not* to do markup: string concat, interpolation
and no escaping. Do view source, and the container directives are
there, pretending to be bits of html.

>  Also, just based on what I could intuit from your pasted apache
>  configuration, it needs fixing:
>
>
>  >   PythonHandler mptest
>  >   PythonDebug On
>  >   SetHandler mod_python
>  >   PythonHandler mod_python.testhandler
>
>
> See how you have 2 PythonHandlers?

Pretty sure that'll be two different containers, just everything in
angle brackets is being eaten in the browser display.

Martin
From lists at sourcefoundry.co.uk  Sun May 11 17:31:23 2008
From: lists at sourcefoundry.co.uk (Brian Lyttle)
Date: Sun May 11 17:31:30 2008
Subject: [mod_python] Make problem on solaris - ld: fatal: library
	-lpython2.5: not found
Message-ID: <ab15610d0805111431v658e083bkb494bdf1ac59278e@mail.gmail.com>

Hi

I'm a mod_python newbie and was following a tutorial at
http://www.8bitb.us/post/django-joyent-accelerator-hard-way/ and
trying to build mod_python-3.3.1 from source. Server OS is Sun/Solaris
and I have Python 2.5.1 with the patch from the tutorial.  Make
results in this error:

ld: fatal: File processing errors. No output written to
build/lib.solaris-2.11-i86pc-2.5/m
od_python/_psp.so
collect2: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
gmake[1]: *** [build] Error 1
gmake[1]: Leaving directory
`/home/brianly/sandbox/djsetup/mod_python-3.3.1/dist'
gmake: *** [do_dso] Error 2

Do I need to install a particular shared library?

I've looked at the previous responses
(http://www.modpython.org/pipermail/mod_python/2007-February/023219.html)
but not sure what to change? My ./configure for the python build
includes --enable-shared

-Brian

Configure output:

[xyz123:~/sandbox/djsetup/mod_python-3.3.1] brianly$ ./configure
--with-apxs=/opt/local/
apache2/bin/apxs --with-python=/opt/local/bin/python
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ANSI C... none needed
checking for ar... ar
checking for a BSD-compatible install... /opt/csw/bin/ginstall -c
checking whether make sets $(MAKE)... yes
checking for main in -lm... yes
checking for an ANSI C-conforming const... yes
checking your blood pressure... a bit high, but we can proceed
configure: checking whether apxs is available...
checking for --with-apxs... /opt/local/apache2/bin/apxs executable, good
checking Apache version... 2.2.8
checking for Apache libexec directory... /opt/local/apache2/modules
checking for Apache include directory... -I/opt/local/apache2/include
checking for gcc on Solaris possible missing _eprintf problem... "done"
checking for --with-python... /opt/local/bin/python
checking Python version... 2.5
checking Python install prefix... /opt/local
checking checking where python libraries are installed...
/opt/local/lib/python2.5
checking for Py_NewInterpreter in -lpython2.5... yes
checking what libraries Python was linked with... -lpython2.5
-lsocket -lnsl -ldl    -lm

checking linker flags used to link Python...
checking where Python include files are... -I/opt/local/include/python2.5
checking for --with-python-src... no
checking for --with-mutex-dir... no
Using MUTEX_DIR /tmp
checking for --with-max-locks... no
Using 8 MAX_LOCKS.
checking for --with-flex... no
checking for flex... /opt/csw/bin/flex
found /opt/csw/bin/flex, we'll use this. Use --with-flex to specify another.
checking flex version... configure: WARNING: Flex version 2.5.4 found.
    Version 2.5.31 or greater is required.  You can generally ignore this
    warning unless you need to regenerate psp_parser.c from psp_parse.l.
    If you do need regenerate psp_parser.c, use --with-flex to specify the
    location of the correct flex version. See the README for more information.
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating Doc/Makefile
config.status: creating src/include/mod_python.h
config.status: creating test/Makefile
config.status: creating test/testconf.py
config.status: creating dist/setup.py
config.status: creating dist/Makefile

Make output (truncated):

building 'mod_python._psp' extension
creating build/temp.solaris-2.11-i86pc-2.5
creating build/temp.solaris-2.11-i86pc-2.5/home
creating build/temp.solaris-2.11-i86pc-2.5/home/brianly
creating build/temp.solaris-2.11-i86pc-2.5/home/brianly/sandbox
creating build/temp.solaris-2.11-i86pc-2.5/home/brianly/sandbox/djsetup
creating build/temp.solaris-2.11-i86pc-2.5/home/brianly/sandbox/djsetup/mod_python-3.3.1
creating build/temp.solaris-2.11-i86pc-2.5/home/brianly/sandbox/djsetup/mod_python-3.3.1/s
rc
gcc -fno-strict-aliasing -DNDEBUG -g -O3 -Wall -Wstrict-prototypes
-fPIC -I/home/brianly/s
andbox/djsetup/mod_python-3.3.1/src/include
-I/opt/local/include/python2.5 -c /home/brianl
y/sandbox/djsetup/mod_python-3.3.1/src/psp_string.c -o
build/temp.solaris-2.11-i86pc-2.5/h
ome/brianly/sandbox/djsetup/mod_python-3.3.1/src/psp_string.o
gcc -fno-strict-aliasing -DNDEBUG -g -O3 -Wall -Wstrict-prototypes
-fPIC -I/home/brianly/s
andbox/djsetup/mod_python-3.3.1/src/include
-I/opt/local/include/python2.5 -c /home/briany
/sandbox/djsetup/mod_python-3.3.1/src/psp_parser.c -o
build/temp.solaris-2.11-i86pc-2.5/ho
me/brianly/sandbox/djsetup/mod_python-3.3.1/src/psp_parser.o
In file included from /opt/local/include/python2.5/Python.h:8,
                 from
/home/brianly/sandbox/djsetup/mod_python-3.3.1/src/include/psp_parse
r.h:23,
                 from psp_parser.l:29:
/opt/local/include/python2.5/pyconfig.h:917:1: warning:
"_FILE_OFFSET_BITS" redefined
In file included from /usr/include/iso/stdarg_c99.h:52,
                 from /usr/include/stdarg.h:51,
                 from
/usr/sfw/lib/gcc/i386-pc-solaris2.11/3.4.3/include/stdio.h:14,
                 from psp_parser.c:20:
/usr/include/sys/feature_tests.h:209:1: warning: this is the location
of the previous defi
nition
psp_parser.c:1436: warning: 'yyunput' defined but not used
gcc -fno-strict-aliasing -DNDEBUG -g -O3 -Wall -Wstrict-prototypes
-fPIC -I/home/brianly/s
andbox/djsetup/mod_python-3.3.1/src/include
-I/opt/local/include/python2.5 -c /home/brianl
y/sandbox/djsetup/mod_python-3.3.1/src/_pspmodule.c -o
build/temp.solaris-2.11-i86pc-2.5/h
ome/brianly/sandbox/djsetup/mod_python-3.3.1/src/_pspmodule.o
In file included from /opt/local/include/python2.5/Python.h:8,
                 from
/home/brianly/sandbox/djsetup/mod_python-3.3.1/src/include/psp_parse
r.h:23,
                 from
/home/brianly/sandbox/djsetup/mod_python-3.3.1/src/_pspmodule.c:26:
/opt/local/include/python2.5/pyconfig.h:917:1: warning:
"_FILE_OFFSET_BITS" redefined
In file included from /usr/include/iso/stdarg_c99.h:52,
                 from /usr/include/stdarg.h:51,
                 from
/usr/sfw/lib/gcc/i386-pc-solaris2.11/3.4.3/include/stdio.h:14,
                 from include/psp_flex.h:24,
                 from
/home/brianly/sandbox/djsetup/mod_python-3.3.1/src/_pspmodule.c:25:
/usr/include/sys/feature_tests.h:209:1: warning: this is the location
of the previous defi
nition
/home/brianly/sandbox/djsetup/mod_python-3.3.1/src/_pspmodule.c:32:
warning: 'yy_init_glob
als' defined but not used
gcc -shared build/temp.solaris-2.11-i86pc-2.5/home/brianly/sandbox/djsetup/mod_python-3.3.
1/src/psp_string.o
build/temp.solaris-2.11-i86pc-2.5/home/brianly/sandbox/djsetup/mod_pyth
on-3.3.1/src/psp_parser.o
build/temp.solaris-2.11-i86pc-2.5/home/brianly/sandbox/djsetup/m
od_python-3.3.1/src/_pspmodule.o -lpython2.5 -o
build/lib.solaris-2.11-i86pc-2.5/mod_pytho
n/_psp.so
ld: fatal: library -lpython2.5: not found
ld: fatal: File processing errors. No output written to
build/lib.solaris-2.11-i86pc-2.5/m
od_python/_psp.so
collect2: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
gmake[1]: *** [build] Error 1
gmake[1]: Leaving directory
`/home/brianly/sandbox/djsetup/mod_python-3.3.1/dist'
gmake: *** [do_dso] Error 2
From graham.dumpleton at gmail.com  Sun May 11 19:39:04 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Sun May 11 19:39:14 2008
Subject: [mod_python] Make problem on solaris - ld: fatal: library
	-lpython2.5: not found
In-Reply-To: <ab15610d0805111431v658e083bkb494bdf1ac59278e@mail.gmail.com>
References: <ab15610d0805111431v658e083bkb494bdf1ac59278e@mail.gmail.com>
Message-ID: <88e286470805111639x2eed520en694e895e23d31d84@mail.gmail.com>

In what directory are libpython2.5.a and libpython2.5.so on your system?

2008/5/12 Brian Lyttle <lists@sourcefoundry.co.uk>:
> Hi
>
>  I'm a mod_python newbie and was following a tutorial at
>  http://www.8bitb.us/post/django-joyent-accelerator-hard-way/ and
>  trying to build mod_python-3.3.1 from source. Server OS is Sun/Solaris
>  and I have Python 2.5.1 with the patch from the tutorial.  Make
>  results in this error:
>
>  ld: fatal: File processing errors. No output written to
>  build/lib.solaris-2.11-i86pc-2.5/m
>  od_python/_psp.so
>  collect2: ld returned 1 exit status
>  error: command 'gcc' failed with exit status 1
>  gmake[1]: *** [build] Error 1
>  gmake[1]: Leaving directory
>  `/home/brianly/sandbox/djsetup/mod_python-3.3.1/dist'
>  gmake: *** [do_dso] Error 2
>
>  Do I need to install a particular shared library?
>
>  I've looked at the previous responses
>  (http://www.modpython.org/pipermail/mod_python/2007-February/023219.html)
>  but not sure what to change? My ./configure for the python build
>  includes --enable-shared
>
>  -Brian
>
>  Configure output:
>
>  [xyz123:~/sandbox/djsetup/mod_python-3.3.1] brianly$ ./configure
>  --with-apxs=/opt/local/
>  apache2/bin/apxs --with-python=/opt/local/bin/python
>  checking for gcc... gcc
>  checking for C compiler default output file name... a.out
>  checking whether the C compiler works... yes
>  checking whether we are cross compiling... no
>  checking for suffix of executables...
>  checking for suffix of object files... o
>  checking whether we are using the GNU C compiler... yes
>  checking whether gcc accepts -g... yes
>  checking for gcc option to accept ANSI C... none needed
>  checking for ar... ar
>  checking for a BSD-compatible install... /opt/csw/bin/ginstall -c
>  checking whether make sets $(MAKE)... yes
>  checking for main in -lm... yes
>  checking for an ANSI C-conforming const... yes
>  checking your blood pressure... a bit high, but we can proceed
>  configure: checking whether apxs is available...
>  checking for --with-apxs... /opt/local/apache2/bin/apxs executable, good
>  checking Apache version... 2.2.8
>  checking for Apache libexec directory... /opt/local/apache2/modules
>  checking for Apache include directory... -I/opt/local/apache2/include
>  checking for gcc on Solaris possible missing _eprintf problem... "done"
>  checking for --with-python... /opt/local/bin/python
>  checking Python version... 2.5
>  checking Python install prefix... /opt/local
>  checking checking where python libraries are installed...
>  /opt/local/lib/python2.5
>  checking for Py_NewInterpreter in -lpython2.5... yes
>  checking what libraries Python was linked with... -lpython2.5
>  -lsocket -lnsl -ldl    -lm
>
>  checking linker flags used to link Python...
>  checking where Python include files are... -I/opt/local/include/python2.5
>  checking for --with-python-src... no
>  checking for --with-mutex-dir... no
>  Using MUTEX_DIR /tmp
>  checking for --with-max-locks... no
>  Using 8 MAX_LOCKS.
>  checking for --with-flex... no
>  checking for flex... /opt/csw/bin/flex
>  found /opt/csw/bin/flex, we'll use this. Use --with-flex to specify another.
>  checking flex version... configure: WARNING: Flex version 2.5.4 found.
>     Version 2.5.31 or greater is required.  You can generally ignore this
>     warning unless you need to regenerate psp_parser.c from psp_parse.l.
>     If you do need regenerate psp_parser.c, use --with-flex to specify the
>     location of the correct flex version. See the README for more information.
>  configure: creating ./config.status
>  config.status: creating Makefile
>  config.status: creating src/Makefile
>  config.status: creating Doc/Makefile
>  config.status: creating src/include/mod_python.h
>  config.status: creating test/Makefile
>  config.status: creating test/testconf.py
>  config.status: creating dist/setup.py
>  config.status: creating dist/Makefile
>
>  Make output (truncated):
>
>  building 'mod_python._psp' extension
>  creating build/temp.solaris-2.11-i86pc-2.5
>  creating build/temp.solaris-2.11-i86pc-2.5/home
>  creating build/temp.solaris-2.11-i86pc-2.5/home/brianly
>  creating build/temp.solaris-2.11-i86pc-2.5/home/brianly/sandbox
>  creating build/temp.solaris-2.11-i86pc-2.5/home/brianly/sandbox/djsetup
>  creating build/temp.solaris-2.11-i86pc-2.5/home/brianly/sandbox/djsetup/mod_python-3.3.1
>  creating build/temp.solaris-2.11-i86pc-2.5/home/brianly/sandbox/djsetup/mod_python-3.3.1/s
>  rc
>  gcc -fno-strict-aliasing -DNDEBUG -g -O3 -Wall -Wstrict-prototypes
>  -fPIC -I/home/brianly/s
>  andbox/djsetup/mod_python-3.3.1/src/include
>  -I/opt/local/include/python2.5 -c /home/brianl
>  y/sandbox/djsetup/mod_python-3.3.1/src/psp_string.c -o
>  build/temp.solaris-2.11-i86pc-2.5/h
>  ome/brianly/sandbox/djsetup/mod_python-3.3.1/src/psp_string.o
>  gcc -fno-strict-aliasing -DNDEBUG -g -O3 -Wall -Wstrict-prototypes
>  -fPIC -I/home/brianly/s
>  andbox/djsetup/mod_python-3.3.1/src/include
>  -I/opt/local/include/python2.5 -c /home/briany
>  /sandbox/djsetup/mod_python-3.3.1/src/psp_parser.c -o
>  build/temp.solaris-2.11-i86pc-2.5/ho
>  me/brianly/sandbox/djsetup/mod_python-3.3.1/src/psp_parser.o
>  In file included from /opt/local/include/python2.5/Python.h:8,
>                  from
>  /home/brianly/sandbox/djsetup/mod_python-3.3.1/src/include/psp_parse
>  r.h:23,
>                  from psp_parser.l:29:
>  /opt/local/include/python2.5/pyconfig.h:917:1: warning:
>  "_FILE_OFFSET_BITS" redefined
>  In file included from /usr/include/iso/stdarg_c99.h:52,
>                  from /usr/include/stdarg.h:51,
>                  from
>  /usr/sfw/lib/gcc/i386-pc-solaris2.11/3.4.3/include/stdio.h:14,
>                  from psp_parser.c:20:
>  /usr/include/sys/feature_tests.h:209:1: warning: this is the location
>  of the previous defi
>  nition
>  psp_parser.c:1436: warning: 'yyunput' defined but not used
>  gcc -fno-strict-aliasing -DNDEBUG -g -O3 -Wall -Wstrict-prototypes
>  -fPIC -I/home/brianly/s
>  andbox/djsetup/mod_python-3.3.1/src/include
>  -I/opt/local/include/python2.5 -c /home/brianl
>  y/sandbox/djsetup/mod_python-3.3.1/src/_pspmodule.c -o
>  build/temp.solaris-2.11-i86pc-2.5/h
>  ome/brianly/sandbox/djsetup/mod_python-3.3.1/src/_pspmodule.o
>  In file included from /opt/local/include/python2.5/Python.h:8,
>                  from
>  /home/brianly/sandbox/djsetup/mod_python-3.3.1/src/include/psp_parse
>  r.h:23,
>                  from
>  /home/brianly/sandbox/djsetup/mod_python-3.3.1/src/_pspmodule.c:26:
>  /opt/local/include/python2.5/pyconfig.h:917:1: warning:
>  "_FILE_OFFSET_BITS" redefined
>  In file included from /usr/include/iso/stdarg_c99.h:52,
>                  from /usr/include/stdarg.h:51,
>                  from
>  /usr/sfw/lib/gcc/i386-pc-solaris2.11/3.4.3/include/stdio.h:14,
>                  from include/psp_flex.h:24,
>                  from
>  /home/brianly/sandbox/djsetup/mod_python-3.3.1/src/_pspmodule.c:25:
>  /usr/include/sys/feature_tests.h:209:1: warning: this is the location
>  of the previous defi
>  nition
>  /home/brianly/sandbox/djsetup/mod_python-3.3.1/src/_pspmodule.c:32:
>  warning: 'yy_init_glob
>  als' defined but not used
>  gcc -shared build/temp.solaris-2.11-i86pc-2.5/home/brianly/sandbox/djsetup/mod_python-3.3.
>  1/src/psp_string.o
>  build/temp.solaris-2.11-i86pc-2.5/home/brianly/sandbox/djsetup/mod_pyth
>  on-3.3.1/src/psp_parser.o
>  build/temp.solaris-2.11-i86pc-2.5/home/brianly/sandbox/djsetup/m
>  od_python-3.3.1/src/_pspmodule.o -lpython2.5 -o
>  build/lib.solaris-2.11-i86pc-2.5/mod_pytho
>  n/_psp.so
>  ld: fatal: library -lpython2.5: not found
>  ld: fatal: File processing errors. No output written to
>  build/lib.solaris-2.11-i86pc-2.5/m
>  od_python/_psp.so
>  collect2: ld returned 1 exit status
>  error: command 'gcc' failed with exit status 1
>  gmake[1]: *** [build] Error 1
>  gmake[1]: Leaving directory
>  `/home/brianly/sandbox/djsetup/mod_python-3.3.1/dist'
>  gmake: *** [do_dso] Error 2
>  _______________________________________________
>  Mod_python mailing list
>  Mod_python@modpython.org
>  http://mailman.modpython.org/mailman/listinfo/mod_python
>
From lists at sourcefoundry.co.uk  Sun May 11 23:33:52 2008
From: lists at sourcefoundry.co.uk (Brian Lyttle)
Date: Sun May 11 23:33:57 2008
Subject: [mod_python] Make problem on solaris - ld: fatal: library
	-lpython2.5: not found
In-Reply-To: <88e286470805111639x2eed520en694e895e23d31d84@mail.gmail.com>
References: <ab15610d0805111431v658e083bkb494bdf1ac59278e@mail.gmail.com>
	<88e286470805111639x2eed520en694e895e23d31d84@mail.gmail.com>
Message-ID: <ab15610d0805112033m17085e82s732a7e5049044645@mail.gmail.com>

On Sun, May 11, 2008 at 7:39 PM, Graham Dumpleton
<graham.dumpleton@gmail.com> wrote:
> In what directory are libpython2.5.a and libpython2.5.so on your system?
>

find /opt/local/ -name libpython2.5.a -type f -print
/opt/local/lib/python2.5/config/libpython2.5.a

find /opt/ -name libpython2.5.so -type f -print
<no results>
find /home/ -name libpython2.5.so -type f -print
/home/brianly/sandbox/djsetup/Python-2.5.1/libpython2.5.so (build directory)

Taking a guess, the makefile is invoking ld and it can't find the .so
file? Do I want to manually copy it somewhere?

-Brian
From lists at sourcefoundry.co.uk  Sun May 11 23:47:23 2008
From: lists at sourcefoundry.co.uk (Brian Lyttle)
Date: Sun May 11 23:47:29 2008
Subject: [mod_python] Make problem on solaris - ld: fatal: library
	-lpython2.5: not found
In-Reply-To: <88e286470805111639x2eed520en694e895e23d31d84@mail.gmail.com>
References: <ab15610d0805111431v658e083bkb494bdf1ac59278e@mail.gmail.com>
	<88e286470805111639x2eed520en694e895e23d31d84@mail.gmail.com>
Message-ID: <ab15610d0805112047p7042ec58x5f0b513d5ea47646@mail.gmail.com>

On Sun, May 11, 2008 at 7:39 PM, Graham Dumpleton
<graham.dumpleton@gmail.com> wrote:
> In what directory are libpython2.5.a and libpython2.5.so on your system?
>

I just notice this in my /opt/local/lib

[xyz123:/opt/local/lib] brianly$ ls
libcrypto.a           libpython2.5.so.1.0*  pkgconfig/
libpython2.5.so@      libssl.a              python2.5/

What's with the .1.0* and .so@ files?

[xyz123:/opt/local/lib] brianly$ ls -las
total 10556
   3 drwxr-xr-x   4 root     root           8 May 11 20:39 ./
   3 drwxr-xr-x   9 root     root           9 May 11 20:48 ../
3591 -rw-r--r--   1 root     root        1.6M May 11 20:39 libcrypto.a
   1 lrwxrwxrwx   1 root     root          19 May 11 20:15
libpython2.5.so -> libpython2.5
.so.1.0*
6153 -r-xr-xr-x   1 root     root        2.9M May 11 20:15 libpython2.5.so.1.0*
 773 -rw-r--r--   1 root     root        257K May 11 20:39 libssl.a
   3 drwxr-xr-x   2 root     root           3 May 11 20:39 pkgconfig/
  29 drwxr-xr-x  21 root     root         597 May 11 20:15 python2.5/

-Brian
From graham.dumpleton at gmail.com  Mon May 12 21:44:47 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Mon May 12 21:44:53 2008
Subject: [mod_python] Make problem on solaris - ld: fatal: library
	-lpython2.5: not found
In-Reply-To: <ab15610d0805112047p7042ec58x5f0b513d5ea47646@mail.gmail.com>
References: <ab15610d0805111431v658e083bkb494bdf1ac59278e@mail.gmail.com>
	<88e286470805111639x2eed520en694e895e23d31d84@mail.gmail.com>
	<ab15610d0805112047p7042ec58x5f0b513d5ea47646@mail.gmail.com>
Message-ID: <88e286470805121844t31dca5cdse7efe6ba4bf136aa@mail.gmail.com>

For startes, in the directory:

  /opt/local/lib/python2.5/config

create a symlink to where the libpython2.5.so file is located. This
will allow mod_python to make use of Python shared library.

For reference, see section 'Lack Of Python Shared Library' of:

  http://code.google.com/p/modwsgi/wiki/InstallationIssues

This documentation is from mod_wsgi, but it is affected by same issue.

Now, this may not help, because your compiler output suggests that required:

  -L/opt/local/lib/python2.5/config

is missing.

The configure script has perhaps got a bit confused because it says:

checking checking where python libraries are installed...
/opt/local/lib/python2.5

Add the symlink, do a 'make distclean', run configure again, and
recompile again to see what happens.

Graham

2008/5/12 Brian Lyttle <lists@sourcefoundry.co.uk>:
> On Sun, May 11, 2008 at 7:39 PM, Graham Dumpleton
>  <graham.dumpleton@gmail.com> wrote:
>
> > In what directory are libpython2.5.a and libpython2.5.so on your system?
>  >
>
>  I just notice this in my /opt/local/lib
>
>  [xyz123:/opt/local/lib] brianly$ ls
>  libcrypto.a           libpython2.5.so.1.0*  pkgconfig/
>  libpython2.5.so@      libssl.a              python2.5/
>
>  What's with the .1.0* and .so@ files?
>
>  [xyz123:/opt/local/lib] brianly$ ls -las
>  total 10556
>    3 drwxr-xr-x   4 root     root           8 May 11 20:39 ./
>    3 drwxr-xr-x   9 root     root           9 May 11 20:48 ../
>  3591 -rw-r--r--   1 root     root        1.6M May 11 20:39 libcrypto.a
>    1 lrwxrwxrwx   1 root     root          19 May 11 20:15
>  libpython2.5.so -> libpython2.5
>  .so.1.0*
>  6153 -r-xr-xr-x   1 root     root        2.9M May 11 20:15 libpython2.5.so.1.0*
>   773 -rw-r--r--   1 root     root        257K May 11 20:39 libssl.a
>    3 drwxr-xr-x   2 root     root           3 May 11 20:39 pkgconfig/
>   29 drwxr-xr-x  21 root     root         597 May 11 20:15 python2.5/
>
>  -Brian
>
>
> _______________________________________________
>  Mod_python mailing list
>  Mod_python@modpython.org
>  http://mailman.modpython.org/mailman/listinfo/mod_python
>
From jmcKamey at neatreceipts.com  Tue May 13 09:27:36 2008
From: jmcKamey at neatreceipts.com (Jon McKamey)
Date: Tue May 13 09:25:49 2008
Subject: [mod_python] mod_pytyon, OSX, and PIL, oh my!
Message-ID: <45E36921B695A14FA56A34F29424A1EC012C6F1A@Apollo.neatreceipts.local>

 

Hey all. This is mod_python PIL integration issues. I tried sending it
to PIL list as well, but I'm not getting any success there.

 

I'm trying to get PIL and mod_python to run on Apache2 on a Mac running
OSX 10.5*  I am to the point where PIL has been rebuilt for the 4 target
processors.   If I run otool on it, I get the list of modules it loads,
and not all of them are built for the 4 processors, some of which appear
to be OS built-in libraries.

 

So, the point I am stuck at:  It's not clear to me how and what to do to
rebuild those modules, and it's not clear to me if it's even safe to
rebuild and replace those modules with 4 processor versions of the
files.  Has anyone reading this done this before?  Is that safe to do?
If not, what are the risks? And if so, can anyone recommend a toolset to
do the rebuilding?  Macports? Download the source and go? Any other
suggestions or advice on this tricky topic?

 

Thanks in advance for any and all help. Mod_python and PIL rocks, and I
can't wait to (finally) get it integrated into Apache.

 

Hack on,

- Jon McKamey

 

 * To give some background, httpd is on OSX is build with 4 target
processors, so everything loaded by it (mod_python, PIL, etc) has to be
built to handle all 4 target processors.  Including all PIL and it's
libraries.

 

 

-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20080513/7591aeb6/attachment.html
From graham.dumpleton at gmail.com  Tue May 13 17:16:59 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Tue May 13 17:17:05 2008
Subject: [mod_python] mod_pytyon, OSX, and PIL, oh my!
In-Reply-To: <45E36921B695A14FA56A34F29424A1EC012C6F1A@Apollo.neatreceipts.local>
References: <45E36921B695A14FA56A34F29424A1EC012C6F1A@Apollo.neatreceipts.local>
Message-ID: <88e286470805131416q3042de7an821395783f58674d@mail.gmail.com>

What are the names/paths of the modules/libraries you are talking
about and what is the output from running 'file' on them? That way we
can see what is and isn't a fat binary.

Also make sure you read:

  http://code.google.com/p/modwsgi/wiki/InstallationOnMacOSX

This is for mod_wsgi, but same issues, even mentions PIL as a problem case.

Graham

2008/5/13 Jon McKamey <jmcKamey@neatreceipts.com>:
>
>
>
>
>
>
> Hey all. This is mod_python PIL integration issues. I tried sending it to
> PIL list as well, but I'm not getting any success there.
>
>
>
> I'm trying to get PIL and mod_python to run on Apache2 on a Mac running OSX
> 10.5*  I am to the point where PIL has been rebuilt for the 4 target
> processors.   If I run otool on it, I get the list of modules it loads, and
> not all of them are built for the 4 processors, some of which appear to be
> OS built-in libraries.
>
>
>
> So, the point I am stuck at:  It's not clear to me how and what to do to
> rebuild those modules, and it's not clear to me if it's even safe to rebuild
> and replace those modules with 4 processor versions of the files.  Has
> anyone reading this done this before?  Is that safe to do?  If not, what are
> the risks? And if so, can anyone recommend a toolset to do the rebuilding?
> Macports? Download the source and go? Any other suggestions or advice on
> this tricky topic?
>
>
>
> Thanks in advance for any and all help. Mod_python and PIL rocks, and I
> can't wait to (finally) get it integrated into Apache.
>
>
>
> Hack on,
>
> - Jon McKamey
>
>
>
>  * To give some background, httpd is on OSX is build with 4 target
> processors, so everything loaded by it (mod_python, PIL, etc) has to be
> built to handle all 4 target processors.  Including all PIL and it's
> libraries.
>
>
>
>
> _______________________________________________
>  Mod_python mailing list
>  Mod_python@modpython.org
>  http://mailman.modpython.org/mailman/listinfo/mod_python
>
>
From davidj411 at gmail.com  Wed May 14 10:37:26 2008
From: davidj411 at gmail.com (David Jackson)
Date: Wed May 14 10:37:34 2008
Subject: [mod_python] [SPAM] Re: mod_python installation failure on apache
In-Reply-To: <d80792120805091539w2e4d0419vfd13b876c0c2c317@mail.gmail.com>
References: <491b0d8f0805091127v28583a91md9133edd28702ab6@mail.gmail.com>
	<491b0d8f0805091140u3b86e398l415e8218ade644c@mail.gmail.com>
	<1D4AF0FA9FFEEE44AF46F697C8A2A5140315C409@VS02SE.wgti.net>
	<d80792120805091539w2e4d0419vfd13b876c0c2c317@mail.gmail.com>
Message-ID: <491b0d8f0805140737l69421544r336e055451f265f6@mail.gmail.com>

SOLUTION: when using the directive <DIRECTORY> on windows with mod_python,
be sure to use the full path (not the relative path) to the folder. this did
work thanks all for the input.

<Directory C:\apache\htdocs\py>
        AddHandler mod_python .py
        PythonHandler mptest
        PythonDebug On
</Directory>


On Fri, May 9, 2008 at 6:39 PM, Martin (gzlist) <gzlist@googlemail.com>
wrote:

> On 09/05/2008, John Calixto <John.Calixto@watchguard.com> wrote:
> > >
> >  >       I followed the directions at
> >  > http://www.modpython.org/live/current/doc-html/inst-testing.html
> >  >       and get contents of the script mptest.py , not the
> >  > results as if it had run.
> >
> >
> > First, it would help to see the actual apache configuration.  You seem
> >  to have pasted stuff a bunch of stuff without the enclosing tags.
>
> That's the dumbness of mod_python/testhandler.py at work. Like a
> little lesson in how *not* to do markup: string concat, interpolation
> and no escaping. Do view source, and the container directives are
> there, pretending to be bits of html.
>
> >  Also, just based on what I could intuit from your pasted apache
> >  configuration, it needs fixing:
> >
> >
> >  >   PythonHandler mptest
> >  >   PythonDebug On
> >  >   SetHandler mod_python
> >  >   PythonHandler mod_python.testhandler
> >
> >
> > See how you have 2 PythonHandlers?
>
> Pretty sure that'll be two different containers, just everything in
> angle brackets is being eaten in the browser display.
>
> Martin
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20080514/aa278697/attachment.html
From davidj411 at gmail.com  Wed May 14 11:38:47 2008
From: davidj411 at gmail.com (David Jackson)
Date: Wed May 14 11:38:55 2008
Subject: [mod_python] how to use mod_python once the initial test is done
Message-ID: <491b0d8f0805140838w725af5a4wb434c0899254547f@mail.gmail.com>

 the form.html and form.py examples at
http://www.modpython.org/live/current/doc-html/tut-pub.html are not working
for me.
the mptest.py overrides them. do i need to remove the mptest directive?


also when i add this stanza to the httpf.conf file, does it need to be
enclosed in the "<DIRECTORY>" directive?
  AddHandler mod_python .py
  PythonHandler mod_python.publisher
  PythonDebug On
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20080514/e528d1b6/attachment.html
From graham.dumpleton at gmail.com  Wed May 14 17:29:23 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Wed May 14 17:29:29 2008
Subject: [mod_python] how to use mod_python once the initial test is done
In-Reply-To: <491b0d8f0805140838w725af5a4wb434c0899254547f@mail.gmail.com>
References: <491b0d8f0805140838w725af5a4wb434c0899254547f@mail.gmail.com>
Message-ID: <88e286470805141429v70a97e1exd680b30c1d729d3c@mail.gmail.com>

2008/5/15 David Jackson <davidj411@gmail.com>:
>  the form.html and form.py examples at
> http://www.modpython.org/live/current/doc-html/tut-pub.html are not working
> for me.
> the mptest.py overrides them. do i need to remove the mptest directive?

Yes, else it will attempt to call in turn all handlers registered with
PythonHandler until termination conditions satisfied.

  http://www.modpython.org/live/current/doc-html/dir-handlers-ph.html

> also when i add this stanza to the httpf.conf file, does it need to be
> enclosed in the "<DIRECTORY>" directive?
>   AddHandler mod_python .py
>   PythonHandler mod_python.publisher
>   PythonDebug On

You might also look at tutorial at:

  http://webpython.codepoint.net/mod_python

Graham
From whatever at fsrz.net  Wed May 14 20:42:05 2008
From: whatever at fsrz.net (Rich Fought)
Date: Wed May 14 20:42:12 2008
Subject: [mod_python] AttributeError: 'mp_request' object has no attribute
	'ssl_var_lookup'
Message-ID: <1210812125.11752.5.camel@gozer-gutsy>

I'm migrating a functioning mod_python handler from Windows (Apache 2.0.63, Python 2.3) to
CentOS 5.1 (Apache 2.2.3, Python 2.4) and am getting a very strange error:

Mod_python error: "PythonFixupHandler myHandler"
Traceback (most recent call last):
  File "/usr/lib/python2.4/site-packages/mod_python/apache.py", line 299, in HandlerDispatch
    result = object(req)

  File "/var/www/mypy/myHandler.py", line 16, in fixuphandler
    ssl_client_dn = req.ssl_var_lookup('SSL_CLIENT_S_DN')

AttributeError: 'mp_request' object has no attribute 'ssl_var_lookup'

I've been searching all afternoon and my Google-fu has failed me.  I haven't been able to determine
why on the CentOS platform the request object suddenly has no ssl_var_lookup attribute.

Any help would be appreciated,

Thanks,
Rich

From graham.dumpleton at gmail.com  Wed May 14 20:47:37 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Wed May 14 20:47:44 2008
Subject: [mod_python] AttributeError: 'mp_request' object has no attribute
	'ssl_var_lookup'
In-Reply-To: <1210812125.11752.5.camel@gozer-gutsy>
References: <1210812125.11752.5.camel@gozer-gutsy>
Message-ID: <88e286470805141747v3359113ch711e403ef5a29ed0@mail.gmail.com>

Your mod_python version is too old, upgrade it to 3.3.1 and you
shouldn't have the problem.

Graham

2008/5/15 Rich Fought <whatever@fsrz.net>:
> I'm migrating a functioning mod_python handler from Windows (Apache 2.0.63, Python 2.3) to
> CentOS 5.1 (Apache 2.2.3, Python 2.4) and am getting a very strange error:
>
> Mod_python error: "PythonFixupHandler myHandler"
> Traceback (most recent call last):
>  File "/usr/lib/python2.4/site-packages/mod_python/apache.py", line 299, in HandlerDispatch
>    result = object(req)
>
>  File "/var/www/mypy/myHandler.py", line 16, in fixuphandler
>    ssl_client_dn = req.ssl_var_lookup('SSL_CLIENT_S_DN')
>
> AttributeError: 'mp_request' object has no attribute 'ssl_var_lookup'
>
> I've been searching all afternoon and my Google-fu has failed me.  I haven't been able to determine
> why on the CentOS platform the request object suddenly has no ssl_var_lookup attribute.
>
> Any help would be appreciated,
>
> Thanks,
> Rich
>
> _______________________________________________
> Mod_python mailing list
> Mod_python@modpython.org
> http://mailman.modpython.org/mailman/listinfo/mod_python
>
From skumar at spikesource.com  Thu May 15 03:58:59 2008
From: skumar at spikesource.com (SatheeshKumar Mohan)
Date: Thu May 15 03:59:03 2008
Subject: [mod_python] test_psp_error, test_import,
	test_psphandler fails - win32
Message-ID: <482BED43.6030104@spikesource.com>

Hi,
I have mod_python installed and apache server servers mptest.py(that 
says hello world).

Apache:
Server version: Apache/2.2.8 (Win32)
Server built:   Mar 30 2008 23:17:06

Python:
2.5.1

Mod_python:
mod_python-3.3.1

The whole things runs on cygwin.

I have edited testconf.py setting values for
HTTPD
TESTHOME
LIBEXECDIR,
MOD_PYTHON_SO

on running python test.py the following tests are failing.. somebody 
help! whats been wrong. how to solve this. why is it failing. what is 
missing in the installation

* Testing file upload with \r char 
E..............................................F..F.F....................
======================================================================
FAIL: test_import (__main__.PerRequestTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 1674, in test_import
    self.fail(`rsp`)
AssertionError: '\n<pre>\nMOD_PYTHON ERROR\n\nProcessId:      
1200\nInterpreter:    \'test_import\'\n\nServerName:     
\'test_import\'\nDocumentRoot:   
\'C:/testcases/mod_python/htdocs\'\n\nURI:            
\'/tests.py\'\nLocation:       None\nDirectory:      
\'C:/testcases/mod_python/htdocs/\'\nFilename:       
\'C:/testcases/mod_python/htdocs/tests.py\'\nPathInfo:       
\'\'\n\nPhase:          \'PythonHandler\'\nHandler:        
\'tests::import_test\'\n\nTraceback (most recent call last):\n\n  File 
"c:\\spikesource\\opt\\spikesource\\share\\python2.5\\Lib\\site-packages\\mod_python\\importer.py", 
line 1537, in HandlerDispatch\n    default=default_handler, arg=req, 
silent=hlist.silent)\n\n  File 
"c:\\spikesource\\opt\\spikesource\\share\\python2.5\\Lib\\site-packages\\mod_python\\importer.py", 
line 1229, in _process_target\n    result = _execute_target(config, req, 
object, arg)\n\n  File 
"c:\\spikesource\\opt\\spikesource\\share\\python2.5\\Lib\\site-packages\\mod_python\\importer.py", 
line 1128, in _execute_target\n    result = object(arg)\n\n  File 
"C:\\testcases\\mod_python\\htdocs\\tests.py", line 1024, in 
import_test\n    assert(map(os.path.normpath, sys.path).count(directory) 
== 1)\n\nAssertionError\n\n\nMODULE CACHE DETAILS\n\nAccessed:       Wed 
May 14 23:42:12 2008\nGeneration:     
0\n\n_mp_a10d030a5fcc032f01749cad7f316362 {\n  FileName:     
\'C:\\\\testcases\\\\mod_python\\\\htdocs\\\\tests.py\'\n  Instance:     
1 [IMPORT]\n  Generation:   1\n  Modified:     Sun Nov 12 19:04:44 
2006\n  Imported:     Wed May 14 23:42:12 2008\n}\n\n</pre>\n'

======================================================================
FAIL: test_psphandler (__main__.PerRequestTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 1847, in test_psphandler
    self.fail(`rsp`)
AssertionError: '\n<pre>\nMOD_PYTHON ERROR\n\nProcessId:      
1200\nInterpreter:    \'test_psphandler\'\n\nServerName:     
\'test_psphandler\'\nDocumentRoot:   
\'C:/testcases/mod_python/htdocs\'\n\nURI:            
\'/psptest.psp\'\nLocation:       None\nDirectory:      
\'C:/testcases/mod_python/htdocs/\'\nFilename:       
\'C:/testcases/mod_python/htdocs/psptest.psp\'\nPathInfo:       
\'\'\n\nPhase:          \'PythonHandler\'\nHandler:        
\'mod_python.psp\'\n\nTraceback (most recent call last):\n\n  File 
"c:\\spikesource\\opt\\spikesource\\share\\python2.5\\Lib\\site-packages\\mod_python\\importer.py", 
line 1537, in HandlerDispatch\n    default=default_handler, arg=req, 
silent=hlist.silent)\n\n  File 
"c:\\spikesource\\opt\\spikesource\\share\\python2.5\\Lib\\site-packages\\mod_python\\importer.py", 
line 1202, in _process_target\n    module = import_module(module_name, 
path=path)\n\n  File 
"c:\\spikesource\\opt\\spikesource\\share\\python2.5\\Lib\\site-packages\\mod_python\\importer.py", 
line 304, in import_module\n    return __import__(module_name, {}, {}, 
[\'*\'])\n\n  File 
"c:\\spikesource\\opt\\spikesource\\share\\python2.5\\Lib\\site-packages\\mod_python\\psp.py", 
line 21, in &lt;module&gt;\n    import apache, Session, util, 
_psp\n\nImportError: No module named _psp\n\n</pre>\n'

======================================================================
FAIL: test_psp_error (__main__.PerRequestTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 1915, in test_psp_error
    self.fail(`rsp`)
AssertionError: '\n<pre>\nMOD_PYTHON ERROR\n\nProcessId:      
1200\nInterpreter:    \'test_psp_error\'\n\nServerName:     
\'test_psp_error\'\nDocumentRoot:   
\'C:/testcases/mod_python/htdocs\'\n\nURI:            
\'/psptest_main.psp\'\nLocation:       NoneThe Apache2.2 service is 
stopping.
The Apache2.2 service has stopped.
in a line at position == readBlockSize
    --> Send + process + receive took 0.000 s
  * Skipping the test for The UNIX-HATERS handbook file upload.
    To make this test, you need to download ugh.pdf from
    http://research.microsoft.com/~daniel/uhh-download.html
    into this script's directory.

  * Testing file upload where length of last line == readBlockSize - 1
    --> Send + process + receive took 0.016 s
  * Testing file upload where length of last line == readBlockSize - 1 
with an extra \r
    --> Send + process + receive took 0.000 s

  * Testing sys.argv definition

-- 
/skumar

From joefazee at gmail.com  Thu May 15 08:02:18 2008
From: joefazee at gmail.com (A. Joseph)
Date: Thu May 15 08:02:25 2008
Subject: [mod_python] I need Mentor
Message-ID: <ea09b3700805150502q64d3f72cld5e7a291c9390c94@mail.gmail.com>

Hi everybody,
   i just started learning Python and i need a mentor, please if you have a
forum where you talk about Python and you can be my mentor, email me, and
tell me what i need to do.


On 5/14/08, David Jackson <davidj411@gmail.com> wrote:
>
>  the form.html and form.py examples at
> http://www.modpython.org/live/current/doc-html/tut-pub.html are not
> working for me.
> the mptest.py overrides them. do i need to remove the mptest directive?
>
>
> also when i add this stanza to the httpf.conf file, does it need to be
> enclosed in the "<DIRECTORY>" directive?
>   AddHandler mod_python .py
>   PythonHandler mod_python.publisher
>   PythonDebug On
>
>
>
> _______________________________________________
> Mod_python mailing list
> Mod_python@modpython.org
> http://mailman.modpython.org/mailman/listinfo/mod_python
>
>


-- 
I develop dynamic website with PHP & MySql, Let me know about your site
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20080515/a90d058b/attachment.html
From davidjanes at blogmatrix.com  Thu May 15 08:26:46 2008
From: davidjanes at blogmatrix.com (David Janes)
Date: Thu May 15 08:26:54 2008
Subject: [mod_python] I need Mentor
In-Reply-To: <ea09b3700805150502q64d3f72cld5e7a291c9390c94@mail.gmail.com>
References: <ea09b3700805150502q64d3f72cld5e7a291c9390c94@mail.gmail.com>
Message-ID: <21e523c20805150526x29c56584p6b86d3249aaf8c07@mail.gmail.com>

Read this: http://www.diveintopython.org/toc/index.htmlGo in a noob, come
out a pro.

Regards, etc...

2008/5/15 A. Joseph <joefazee@gmail.com>:

> Hi everybody,
>    i just started learning Python and i need a mentor, please if you have a
> forum where you talk about Python and you can be my mentor, email me, and
> tell me what i need to do.
>
>
> On 5/14/08, David Jackson <davidj411@gmail.com> wrote:
>>
>>  the form.html and form.py examples at
>> http://www.modpython.org/live/current/doc-html/tut-pub.html are not
>> working for me.
>> the mptest.py overrides them. do i need to remove the mptest directive?
>>
>>
>> also when i add this stanza to the httpf.conf file, does it need to be
>> enclosed in the "<DIRECTORY>" directive?
>>   AddHandler mod_python .py
>>   PythonHandler mod_python.publisher
>>   PythonDebug On
>>
>>
>>
>> _______________________________________________
>> Mod_python mailing list
>> Mod_python@modpython.org
>> http://mailman.modpython.org/mailman/listinfo/mod_python
>>
>>
>
>
> --
> I develop dynamic website with PHP & MySql, Let me know about your site
> _______________________________________________
> Mod_python mailing list
> Mod_python@modpython.org
> http://mailman.modpython.org/mailman/listinfo/mod_python
>
>


-- 
David Janes
Founder, BlogMatrix
http://www.blogmatrix.com
http://www.onaswarm.com
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20080515/1bd2a47e/attachment-0001.html
From paolo at lambrate.inaf.it  Tue May 20 04:12:58 2008
From: paolo at lambrate.inaf.it (Paolo Franzetti)
Date: Tue May 20 04:13:25 2008
Subject: [mod_python] New session
Message-ID: <4832880A.30309@lambrate.inaf.it>

Dear all,

in my application I have the simple line:

current_session = Session.Session(req,timeout=3600)

After having executed this command I can check if the
session is new using the current_session.is_new() functions.

My question is:
is there a way to know if the session is new because the old
session (recovered from a cookie) has expired or because
there was no session to recover ?

Thank you for any suggestion,
Paolo
From graham.dumpleton at gmail.com  Tue May 20 05:25:40 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Tue May 20 05:25:47 2008
Subject: [mod_python] New session
In-Reply-To: <4832880A.30309@lambrate.inaf.it>
References: <4832880A.30309@lambrate.inaf.it>
Message-ID: <88e286470805200225y5a31c27cm563679a7d1991913@mail.gmail.com>

2008/5/20 Paolo Franzetti <paolo@lambrate.inaf.it>:
> Dear all,
>
> in my application I have the simple line:
>
> current_session = Session.Session(req,timeout=3600)
>
> After having executed this command I can check if the
> session is new using the current_session.is_new() functions.
>
> My question is:
> is there a way to know if the session is new because the old
> session (recovered from a cookie) has expired or because
> there was no session to recover ?

Session class uses cookie called 'pysid', so use SignedCookie/Cookie
class to see if there is a cookie called 'pysid'.

It isn't fool proof, but closest you will probably get.

Graham
From rob.shinn at gmail.com  Wed May 21 22:23:09 2008
From: rob.shinn at gmail.com (Rob Shinn)
Date: Wed May 21 22:23:26 2008
Subject: [mod_python] [SPAM] Sample .psp code returns a blank page
Message-ID: <4834D90D.70500@gmail.com>

tried running the sample "Hello, world" PSP script from the 
documentation but it just returns a blank page. I'm running mod_python 
3.2.10 on Apache 2.2.3 running under Ubuntu 7.04 Feisty. Apache 
directives used to load mod_python.psp:

<Directory /var/www-sec/st/>
      AddHandler mod_python .psp .psp_
      PythonHandler mod_python.psp
      PythonDebug On
</Directory>

I also tried using PSP through PublisherHandler. Same thing, the run() 
method of the psp.PSP instance returns nothing:

#!/usr/bin/env python
from mod_python import apache,psp


def handler(req):
    req.content_type = 'text/html'
    template = psp.PSP(req, filename='/var/www/st/test.psp')
    #req.write("%s" % template.run())
    template.run({'what':'hello'})
    req.flush()
    return apache.OK

From graham.dumpleton at gmail.com  Wed May 21 23:44:44 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Wed May 21 23:44:52 2008
Subject: [mod_python] [SPAM] Sample .psp code returns a blank page
In-Reply-To: <4834D90D.70500@gmail.com>
References: <4834D90D.70500@gmail.com>
Message-ID: <88e286470805212044u2ca87e5ue5a7dd2d72fa1d90@mail.gmail.com>

Are you sure it is blank? Are you sure you haven't made a mistake in
any HTML and the browser is treating the whole contents as part of the
markup and therefore not displaying?

Try 'View Source' on the response in the browser.

Graham

2008/5/22 Rob Shinn <rob.shinn@gmail.com>:
> tried running the sample "Hello, world" PSP script from the documentation
> but it just returns a blank page. I'm running mod_python 3.2.10 on Apache
> 2.2.3 running under Ubuntu 7.04 Feisty. Apache directives used to load
> mod_python.psp:
>
> <Directory /var/www-sec/st/>
>     AddHandler mod_python .psp .psp_
>     PythonHandler mod_python.psp
>     PythonDebug On
> </Directory>
>
> I also tried using PSP through PublisherHandler. Same thing, the run()
> method of the psp.PSP instance returns nothing:
>
> #!/usr/bin/env python
> from mod_python import apache,psp
>
>
> def handler(req):
>   req.content_type = 'text/html'
>   template = psp.PSP(req, filename='/var/www/st/test.psp')
>   #req.write("%s" % template.run())
>   template.run({'what':'hello'})
>   req.flush()
>   return apache.OK
>
> _______________________________________________
> Mod_python mailing list
> Mod_python@modpython.org
> http://mailman.modpython.org/mailman/listinfo/mod_python
>
From rob.shinn at gmail.com  Thu May 22 08:22:17 2008
From: rob.shinn at gmail.com (Rob Shinn)
Date: Thu May 22 08:22:23 2008
Subject: [mod_python] [SPAM] Sample .psp code returns a blank page
In-Reply-To: <88e286470805212044u2ca87e5ue5a7dd2d72fa1d90@mail.gmail.com>
References: <4834D90D.70500@gmail.com>
	<88e286470805212044u2ca87e5ue5a7dd2d72fa1d90@mail.gmail.com>
Message-ID: <2f96483c0805220522i10f9d318pf15ae3c956aae1c3@mail.gmail.com>

Yep.  Tried "view source" and it's empty. The PSP code is copied and pasted
from the first example in the docs.  What's weird is that the
PublisherHandler works just fine for non-PSP code.


On Wed, May 21, 2008 at 11:44 PM, Graham Dumpleton <
graham.dumpleton@gmail.com> wrote:

> Are you sure it is blank? Are you sure you haven't made a mistake in
> any HTML and the browser is treating the whole contents as part of the
> markup and therefore not displaying?
>
> Try 'View Source' on the response in the browser.
>
> Graham
>
> 2008/5/22 Rob Shinn <rob.shinn@gmail.com>:
> > tried running the sample "Hello, world" PSP script from the documentation
> > but it just returns a blank page. I'm running mod_python 3.2.10 on Apache
> > 2.2.3 running under Ubuntu 7.04 Feisty. Apache directives used to load
> > mod_python.psp:
> >
> > <Directory /var/www-sec/st/>
> >     AddHandler mod_python .psp .psp_
> >     PythonHandler mod_python.psp
> >     PythonDebug On
> > </Directory>
> >
> > I also tried using PSP through PublisherHandler. Same thing, the run()
> > method of the psp.PSP instance returns nothing:
> >
> > #!/usr/bin/env python
> > from mod_python import apache,psp
> >
> >
> > def handler(req):
> >   req.content_type = 'text/html'
> >   template = psp.PSP(req, filename='/var/www/st/test.psp')
> >   #req.write("%s" % template.run())
> >   template.run({'what':'hello'})
> >   req.flush()
> >   return apache.OK
> >
> > _______________________________________________
> > Mod_python mailing list
> > Mod_python@modpython.org
> > http://mailman.modpython.org/mailman/listinfo/mod_python
> >
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20080522/fcf42e1b/attachment.html
From graham.dumpleton at gmail.com  Thu May 22 08:26:07 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Thu May 22 08:26:13 2008
Subject: [mod_python] [SPAM] Sample .psp code returns a blank page
In-Reply-To: <2f96483c0805220522i10f9d318pf15ae3c956aae1c3@mail.gmail.com>
References: <4834D90D.70500@gmail.com>
	<88e286470805212044u2ca87e5ue5a7dd2d72fa1d90@mail.gmail.com>
	<2f96483c0805220522i10f9d318pf15ae3c956aae1c3@mail.gmail.com>
Message-ID: <88e286470805220526i4e3192d0t8daaf8900ad9690a@mail.gmail.com>

Post the actual PSP code.

2008/5/22 Rob Shinn <rob.shinn@gmail.com>:
> Yep.  Tried "view source" and it's empty. The PSP code is copied and pasted
> from the first example in the docs.  What's weird is that the
> PublisherHandler works just fine for non-PSP code.
>
>
> On Wed, May 21, 2008 at 11:44 PM, Graham Dumpleton
> <graham.dumpleton@gmail.com> wrote:
>>
>> Are you sure it is blank? Are you sure you haven't made a mistake in
>> any HTML and the browser is treating the whole contents as part of the
>> markup and therefore not displaying?
>>
>> Try 'View Source' on the response in the browser.
>>
>> Graham
>>
>> 2008/5/22 Rob Shinn <rob.shinn@gmail.com>:
>> > tried running the sample "Hello, world" PSP script from the
>> > documentation
>> > but it just returns a blank page. I'm running mod_python 3.2.10 on
>> > Apache
>> > 2.2.3 running under Ubuntu 7.04 Feisty. Apache directives used to load
>> > mod_python.psp:
>> >
>> > <Directory /var/www-sec/st/>
>> >     AddHandler mod_python .psp .psp_
>> >     PythonHandler mod_python.psp
>> >     PythonDebug On
>> > </Directory>
>> >
>> > I also tried using PSP through PublisherHandler. Same thing, the run()
>> > method of the psp.PSP instance returns nothing:
>> >
>> > #!/usr/bin/env python
>> > from mod_python import apache,psp
>> >
>> >
>> > def handler(req):
>> >   req.content_type = 'text/html'
>> >   template = psp.PSP(req, filename='/var/www/st/test.psp')
>> >   #req.write("%s" % template.run())
>> >   template.run({'what':'hello'})
>> >   req.flush()
>> >   return apache.OK
>> >
>> > _______________________________________________
>> > Mod_python mailing list
>> > Mod_python@modpython.org
>> > http://mailman.modpython.org/mailman/listinfo/mod_python
>> >
>
>
From rob.shinn at gmail.com  Thu May 22 08:43:00 2008
From: rob.shinn at gmail.com (Rob Shinn)
Date: Thu May 22 08:43:07 2008
Subject: [mod_python] [SPAM] Sample .psp code returns a blank page
In-Reply-To: <88e286470805220526i4e3192d0t8daaf8900ad9690a@mail.gmail.com>
References: <4834D90D.70500@gmail.com>
	<88e286470805212044u2ca87e5ue5a7dd2d72fa1d90@mail.gmail.com>
	<2f96483c0805220522i10f9d318pf15ae3c956aae1c3@mail.gmail.com>
	<88e286470805220526i4e3192d0t8daaf8900ad9690a@mail.gmail.com>
Message-ID: <2f96483c0805220543h3527ea9p4dbc9efffd12c261@mail.gmail.com>

<html>
<%
import time
%>
Hello <%=what%> the time is: <%=time.strftime("%Y-%m-%d, %H:%M:%S")%>
</html>


On Thu, May 22, 2008 at 8:26 AM, Graham Dumpleton <
graham.dumpleton@gmail.com> wrote:

> Post the actual PSP code.
>
> 2008/5/22 Rob Shinn <rob.shinn@gmail.com>:
> > Yep.  Tried "view source" and it's empty. The PSP code is copied and
> pasted
> > from the first example in the docs.  What's weird is that the
> > PublisherHandler works just fine for non-PSP code.
> >
> >
> > On Wed, May 21, 2008 at 11:44 PM, Graham Dumpleton
> > <graham.dumpleton@gmail.com> wrote:
> >>
> >> Are you sure it is blank? Are you sure you haven't made a mistake in
> >> any HTML and the browser is treating the whole contents as part of the
> >> markup and therefore not displaying?
> >>
> >> Try 'View Source' on the response in the browser.
> >>
> >> Graham
> >>
> >> 2008/5/22 Rob Shinn <rob.shinn@gmail.com>:
> >> > tried running the sample "Hello, world" PSP script from the
> >> > documentation
> >> > but it just returns a blank page. I'm running mod_python 3.2.10 on
> >> > Apache
> >> > 2.2.3 running under Ubuntu 7.04 Feisty. Apache directives used to load
> >> > mod_python.psp:
> >> >
> >> > <Directory /var/www-sec/st/>
> >> >     AddHandler mod_python .psp .psp_
> >> >     PythonHandler mod_python.psp
> >> >     PythonDebug On
> >> > </Directory>
> >> >
> >> > I also tried using PSP through PublisherHandler. Same thing, the run()
> >> > method of the psp.PSP instance returns nothing:
> >> >
> >> > #!/usr/bin/env python
> >> > from mod_python import apache,psp
> >> >
> >> >
> >> > def handler(req):
> >> >   req.content_type = 'text/html'
> >> >   template = psp.PSP(req, filename='/var/www/st/test.psp')
> >> >   #req.write("%s" % template.run())
> >> >   template.run({'what':'hello'})
> >> >   req.flush()
> >> >   return apache.OK
> >> >
> >> > _______________________________________________
> >> > Mod_python mailing list
> >> > Mod_python@modpython.org
> >> > http://mailman.modpython.org/mailman/listinfo/mod_python
> >> >
> >
> >
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20080522/2342c5ce/attachment.html
From rob.shinn at gmail.com  Thu May 22 13:48:30 2008
From: rob.shinn at gmail.com (Rob Shinn)
Date: Thu May 22 13:48:38 2008
Subject: [mod_python] [SPAM] Sample .psp code returns a blank page
In-Reply-To: <2f96483c0805220543h3527ea9p4dbc9efffd12c261@mail.gmail.com>
References: <4834D90D.70500@gmail.com>
	<88e286470805212044u2ca87e5ue5a7dd2d72fa1d90@mail.gmail.com>
	<2f96483c0805220522i10f9d318pf15ae3c956aae1c3@mail.gmail.com>
	<88e286470805220526i4e3192d0t8daaf8900ad9690a@mail.gmail.com>
	<2f96483c0805220543h3527ea9p4dbc9efffd12c261@mail.gmail.com>
Message-ID: <2f96483c0805221048w3e6efd0avc0ea1e569ec0127c@mail.gmail.com>

Ok, more help:

This is what I get from python when I try to import apache and psp from
mod_python directly into the Python interpreter:

>>> from mod_python import apache,psp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.5/site-packages/mod_python/apache.py", line 28, in
<module>
    import _apache
ImportError: No module named _apache
>>> from mod_python import psp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.5/site-packages/mod_python/psp.py", line 20, in
<module>
    import apache, Session, util, _psp
  File "/usr/lib/python2.5/site-packages/mod_python/apache.py", line 28, in
<module>
    import _apache
ImportError: No module named _apache
>>>

Something seems broken here.




On Thu, May 22, 2008 at 8:43 AM, Rob Shinn <rob.shinn@gmail.com> wrote:

> <html>
> <%
> import time
> %>
> Hello <%=what%> the time is: <%=time.strftime("%Y-%m-%d, %H:%M:%S")%>
> </html>
>
>
>
> On Thu, May 22, 2008 at 8:26 AM, Graham Dumpleton <
> graham.dumpleton@gmail.com> wrote:
>
>> Post the actual PSP code.
>>
>> 2008/5/22 Rob Shinn <rob.shinn@gmail.com>:
>> > Yep.  Tried "view source" and it's empty. The PSP code is copied and
>> pasted
>> > from the first example in the docs.  What's weird is that the
>> > PublisherHandler works just fine for non-PSP code.
>> >
>> >
>> > On Wed, May 21, 2008 at 11:44 PM, Graham Dumpleton
>> > <graham.dumpleton@gmail.com> wrote:
>> >>
>> >> Are you sure it is blank? Are you sure you haven't made a mistake in
>> >> any HTML and the browser is treating the whole contents as part of the
>> >> markup and therefore not displaying?
>> >>
>> >> Try 'View Source' on the response in the browser.
>> >>
>> >> Graham
>> >>
>> >> 2008/5/22 Rob Shinn <rob.shinn@gmail.com>:
>> >> > tried running the sample "Hello, world" PSP script from the
>> >> > documentation
>> >> > but it just returns a blank page. I'm running mod_python 3.2.10 on
>> >> > Apache
>> >> > 2.2.3 running under Ubuntu 7.04 Feisty. Apache directives used to
>> load
>> >> > mod_python.psp:
>> >> >
>> >> > <Directory /var/www-sec/st/>
>> >> >     AddHandler mod_python .psp .psp_
>> >> >     PythonHandler mod_python.psp
>> >> >     PythonDebug On
>> >> > </Directory>
>> >> >
>> >> > I also tried using PSP through PublisherHandler. Same thing, the
>> run()
>> >> > method of the psp.PSP instance returns nothing:
>> >> >
>> >> > #!/usr/bin/env python
>> >> > from mod_python import apache,psp
>> >> >
>> >> >
>> >> > def handler(req):
>> >> >   req.content_type = 'text/html'
>> >> >   template = psp.PSP(req, filename='/var/www/st/test.psp')
>> >> >   #req.write("%s" % template.run())
>> >> >   template.run({'what':'hello'})
>> >> >   req.flush()
>> >> >   return apache.OK
>> >> >
>> >> > _______________________________________________
>> >> > Mod_python mailing list
>> >> > Mod_python@modpython.org
>> >> > http://mailman.modpython.org/mailman/listinfo/mod_python
>> >> >
>> >
>> >
>>
>
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20080522/166e1319/attachment.html
From rob.shinn at gmail.com  Thu May 22 15:39:10 2008
From: rob.shinn at gmail.com (Rob Shinn)
Date: Thu May 22 15:39:17 2008
Subject: [mod_python] [SPAM] Sample .psp code returns a blank page
In-Reply-To: <2f96483c0805221048w3e6efd0avc0ea1e569ec0127c@mail.gmail.com>
References: <4834D90D.70500@gmail.com>
	<88e286470805212044u2ca87e5ue5a7dd2d72fa1d90@mail.gmail.com>
	<2f96483c0805220522i10f9d318pf15ae3c956aae1c3@mail.gmail.com>
	<88e286470805220526i4e3192d0t8daaf8900ad9690a@mail.gmail.com>
	<2f96483c0805220543h3527ea9p4dbc9efffd12c261@mail.gmail.com>
	<2f96483c0805221048w3e6efd0avc0ea1e569ec0127c@mail.gmail.com>
Message-ID: <2f96483c0805221239y69efcc3fm723490c0d6c618cf@mail.gmail.com>

Ok, just ignore that last one... :(  Sorry, If I had googled, I would have
found that _apache isn't a 'real' module.

I also installed mod_python-3.3.1 from source, and it still doesn't work.  I
figure it must have to be something to do with my Apache configuration?

On Thu, May 22, 2008 at 1:48 PM, Rob Shinn <rob.shinn@gmail.com> wrote:

> Ok, more help:
>
> This is what I get from python when I try to import apache and psp from
> mod_python directly into the Python interpreter:
>
> >>> from mod_python import apache,psp
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python2.5/site-packages/mod_python/apache.py", line 28, in
> <module>
>     import _apache
> ImportError: No module named _apache
> >>> from mod_python import psp
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python2.5/site-packages/mod_python/psp.py", line 20, in
> <module>
>     import apache, Session, util, _psp
>   File "/usr/lib/python2.5/site-packages/mod_python/apache.py", line 28, in
> <module>
>     import _apache
> ImportError: No module named _apache
> >>>
>
> Something seems broken here.
>
>
>
>
>
> On Thu, May 22, 2008 at 8:43 AM, Rob Shinn <rob.shinn@gmail.com> wrote:
>
>> <html>
>> <%
>> import time
>> %>
>> Hello <%=what%> the time is: <%=time.strftime("%Y-%m-%d, %H:%M:%S")%>
>> </html>
>>
>>
>>
>> On Thu, May 22, 2008 at 8:26 AM, Graham Dumpleton <
>> graham.dumpleton@gmail.com> wrote:
>>
>>> Post the actual PSP code.
>>>
>>> 2008/5/22 Rob Shinn <rob.shinn@gmail.com>:
>>> > Yep.  Tried "view source" and it's empty. The PSP code is copied and
>>> pasted
>>> > from the first example in the docs.  What's weird is that the
>>> > PublisherHandler works just fine for non-PSP code.
>>> >
>>> >
>>> > On Wed, May 21, 2008 at 11:44 PM, Graham Dumpleton
>>> > <graham.dumpleton@gmail.com> wrote:
>>> >>
>>> >> Are you sure it is blank? Are you sure you haven't made a mistake in
>>> >> any HTML and the browser is treating the whole contents as part of the
>>> >> markup and therefore not displaying?
>>> >>
>>> >> Try 'View Source' on the response in the browser.
>>> >>
>>> >> Graham
>>> >>
>>> >> 2008/5/22 Rob Shinn <rob.shinn@gmail.com>:
>>> >> > tried running the sample "Hello, world" PSP script from the
>>> >> > documentation
>>> >> > but it just returns a blank page. I'm running mod_python 3.2.10 on
>>> >> > Apache
>>> >> > 2.2.3 running under Ubuntu 7.04 Feisty. Apache directives used to
>>> load
>>> >> > mod_python.psp:
>>> >> >
>>> >> > <Directory /var/www-sec/st/>
>>> >> >     AddHandler mod_python .psp .psp_
>>> >> >     PythonHandler mod_python.psp
>>> >> >     PythonDebug On
>>> >> > </Directory>
>>> >> >
>>> >> > I also tried using PSP through PublisherHandler. Same thing, the
>>> run()
>>> >> > method of the psp.PSP instance returns nothing:
>>> >> >
>>> >> > #!/usr/bin/env python
>>> >> > from mod_python import apache,psp
>>> >> >
>>> >> >
>>> >> > def handler(req):
>>> >> >   req.content_type = 'text/html'
>>> >> >   template = psp.PSP(req, filename='/var/www/st/test.psp')
>>> >> >   #req.write("%s" % template.run())
>>> >> >   template.run({'what':'hello'})
>>> >> >   req.flush()
>>> >> >   return apache.OK
>>> >> >
>>> >> > _______________________________________________
>>> >> > Mod_python mailing list
>>> >> > Mod_python@modpython.org
>>> >> > http://mailman.modpython.org/mailman/listinfo/mod_python
>>> >> >
>>> >
>>> >
>>>
>>
>>
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20080522/93f6b787/attachment.html
From graham.dumpleton at gmail.com  Thu May 22 18:07:07 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Thu May 22 18:07:14 2008
Subject: [mod_python] [SPAM] Sample .psp code returns a blank page
In-Reply-To: <2f96483c0805220809h2baad466t4e6bea109f6cf5b6@mail.gmail.com>
References: <4834D90D.70500@gmail.com>
	<88e286470805212044u2ca87e5ue5a7dd2d72fa1d90@mail.gmail.com>
	<2f96483c0805220522i10f9d318pf15ae3c956aae1c3@mail.gmail.com>
	<88e286470805220526i4e3192d0t8daaf8900ad9690a@mail.gmail.com>
	<2f96483c0805220543h3527ea9p4dbc9efffd12c261@mail.gmail.com>
	<2f96483c0805220809h2baad466t4e6bea109f6cf5b6@mail.gmail.com>
Message-ID: <88e286470805221507s1e5cb1dvd64fa9d64f2c7dd4@mail.gmail.com>

2008/5/23 Rob Shinn <rob.shinn@gmail.com>:
> Oh, one thing that might help:
>
> The PublisherHandler code that I posted actually returns a '0' unless I
> comment out the 'return Apache.OK'.

Read the documentation for mod_python.publisher correctly and you will
see that the value returned is what is returned as the page content.
It shouldn't be a status value. You are mixing up publisher with
normal mod_python request handlers.

Graham

> On Thu, May 22, 2008 at 8:43 AM, Rob Shinn <rob.shinn@gmail.com> wrote:
>>
>> <html>
>> <%
>> import time
>> %>
>> Hello <%=what%> the time is: <%=time.strftime("%Y-%m-%d, %H:%M:%S")%>
>> </html>
>>
>>
>> On Thu, May 22, 2008 at 8:26 AM, Graham Dumpleton
>> <graham.dumpleton@gmail.com> wrote:
>>>
>>> Post the actual PSP code.
>>>
>>> 2008/5/22 Rob Shinn <rob.shinn@gmail.com>:
>>> > Yep.  Tried "view source" and it's empty. The PSP code is copied and
>>> > pasted
>>> > from the first example in the docs.  What's weird is that the
>>> > PublisherHandler works just fine for non-PSP code.
>>> >
>>> >
>>> > On Wed, May 21, 2008 at 11:44 PM, Graham Dumpleton
>>> > <graham.dumpleton@gmail.com> wrote:
>>> >>
>>> >> Are you sure it is blank? Are you sure you haven't made a mistake in
>>> >> any HTML and the browser is treating the whole contents as part of the
>>> >> markup and therefore not displaying?
>>> >>
>>> >> Try 'View Source' on the response in the browser.
>>> >>
>>> >> Graham
>>> >>
>>> >> 2008/5/22 Rob Shinn <rob.shinn@gmail.com>:
>>> >> > tried running the sample "Hello, world" PSP script from the
>>> >> > documentation
>>> >> > but it just returns a blank page. I'm running mod_python 3.2.10 on
>>> >> > Apache
>>> >> > 2.2.3 running under Ubuntu 7.04 Feisty. Apache directives used to
>>> >> > load
>>> >> > mod_python.psp:
>>> >> >
>>> >> > <Directory /var/www-sec/st/>
>>> >> >     AddHandler mod_python .psp .psp_
>>> >> >     PythonHandler mod_python.psp
>>> >> >     PythonDebug On
>>> >> > </Directory>
>>> >> >
>>> >> > I also tried using PSP through PublisherHandler. Same thing, the
>>> >> > run()
>>> >> > method of the psp.PSP instance returns nothing:
>>> >> >
>>> >> > #!/usr/bin/env python
>>> >> > from mod_python import apache,psp
>>> >> >
>>> >> >
>>> >> > def handler(req):
>>> >> >   req.content_type = 'text/html'
>>> >> >   template = psp.PSP(req, filename='/var/www/st/test.psp')
>>> >> >   #req.write("%s" % template.run())
>>> >> >   template.run({'what':'hello'})
>>> >> >   req.flush()
>>> >> >   return apache.OK
>>> >> >
>>> >> > _______________________________________________
>>> >> > Mod_python mailing list
>>> >> > Mod_python@modpython.org
>>> >> > http://mailman.modpython.org/mailman/listinfo/mod_python
>>> >> >
>>> >
>>> >
>>
>
>
From graham.dumpleton at gmail.com  Thu May 22 20:48:07 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Thu May 22 20:48:13 2008
Subject: [mod_python] [SPAM] Sample .psp code returns a blank page
In-Reply-To: <2f96483c0805220543h3527ea9p4dbc9efffd12c261@mail.gmail.com>
References: <4834D90D.70500@gmail.com>
	<88e286470805212044u2ca87e5ue5a7dd2d72fa1d90@mail.gmail.com>
	<2f96483c0805220522i10f9d318pf15ae3c956aae1c3@mail.gmail.com>
	<88e286470805220526i4e3192d0t8daaf8900ad9690a@mail.gmail.com>
	<2f96483c0805220543h3527ea9p4dbc9efffd12c261@mail.gmail.com>
Message-ID: <88e286470805221748i506bf1cdq9f1e424aa7afcfea@mail.gmail.com>

2008/5/22 Rob Shinn <rob.shinn@gmail.com>:
> <html>
> <%
> import time
> %>
> Hello <%=what%> the time is: <%=time.strftime("%Y-%m-%d, %H:%M:%S")%>
> </html>

Which isn't strictly going to produce valid HTML as you are missing
<body> element.

Since I don't have the time to try your code and debug it and no one
else is piping up, I can suggest only two things.

First is that you upgrade to the latest version of mod_python and stop
using the older version. It isn't going to help one bit if you are
using older (potentially buggy version) and also referring to latest
documentation, which may differ.

Secondly, work through tutorials at:

  http://webpython.codepoint.net/mod_python

The examples there at least appear to use correct HTML.

Graham

> On Thu, May 22, 2008 at 8:26 AM, Graham Dumpleton
> <graham.dumpleton@gmail.com> wrote:
>>
>> Post the actual PSP code.
>>
>> 2008/5/22 Rob Shinn <rob.shinn@gmail.com>:
>> > Yep.  Tried "view source" and it's empty. The PSP code is copied and
>> > pasted
>> > from the first example in the docs.  What's weird is that the
>> > PublisherHandler works just fine for non-PSP code.
>> >
>> >
>> > On Wed, May 21, 2008 at 11:44 PM, Graham Dumpleton
>> > <graham.dumpleton@gmail.com> wrote:
>> >>
>> >> Are you sure it is blank? Are you sure you haven't made a mistake in
>> >> any HTML and the browser is treating the whole contents as part of the
>> >> markup and therefore not displaying?
>> >>
>> >> Try 'View Source' on the response in the browser.
>> >>
>> >> Graham
>> >>
>> >> 2008/5/22 Rob Shinn <rob.shinn@gmail.com>:
>> >> > tried running the sample "Hello, world" PSP script from the
>> >> > documentation
>> >> > but it just returns a blank page. I'm running mod_python 3.2.10 on
>> >> > Apache
>> >> > 2.2.3 running under Ubuntu 7.04 Feisty. Apache directives used to
>> >> > load
>> >> > mod_python.psp:
>> >> >
>> >> > <Directory /var/www-sec/st/>
>> >> >     AddHandler mod_python .psp .psp_
>> >> >     PythonHandler mod_python.psp
>> >> >     PythonDebug On
>> >> > </Directory>
>> >> >
>> >> > I also tried using PSP through PublisherHandler. Same thing, the
>> >> > run()
>> >> > method of the psp.PSP instance returns nothing:
>> >> >
>> >> > #!/usr/bin/env python
>> >> > from mod_python import apache,psp
>> >> >
>> >> >
>> >> > def handler(req):
>> >> >   req.content_type = 'text/html'
>> >> >   template = psp.PSP(req, filename='/var/www/st/test.psp')
>> >> >   #req.write("%s" % template.run())
>> >> >   template.run({'what':'hello'})
>> >> >   req.flush()
>> >> >   return apache.OK
>> >> >
>> >> > _______________________________________________
>> >> > Mod_python mailing list
>> >> > Mod_python@modpython.org
>> >> > http://mailman.modpython.org/mailman/listinfo/mod_python
>> >> >
>> >
>> >
>
>
From Dominique.Holzwarth at ch.delarue.com  Fri May 23 09:37:29 2008
From: Dominique.Holzwarth at ch.delarue.com (Dominique.Holzwarth@ch.delarue.com)
Date: Fri May 23 09:42:13 2008
Subject: [mod_python] Question about get_basic_auth_pw()
Message-ID: <5213E58D85BC414998FA553C701E386C0EF281C8A0@SGBD012511.dlrmail.ad.delarue.com>

Hi all

Does anyone have an idea how the function "get_basic_auth_pw()" manages to decrypt the user password stored as MD5 inside the auth-file into its clear text version?
I'm asking cause I maybe have to convert the MD5 passwords into the clear texts passwords myself and wondering how this is possible as normaly those passwords shouldn't be decryptable (i think) and authentication should be done by matching 2 MD5... =)

Would be cool if someone has an idea what could be the trick! :-)

Greetings
Dominique


*****************************************************************************
This e-mail and any files attached are strictly confidential, may be legally
privileged and are intended solely for the addressee. If you are not the
intended recipient please notify the sender immediately by return email and
then delete the e-mail and any attachments immediately.

The views and or opinions expressed in this e-mail are not necessarily the
views of De La Rue plc or any of its subsidiaries and the De La Rue Group
of companies, their directors, officers and employees make no representation
about and accept no liability for its accuracy or completeness.

You should ensure that you have adequate virus protection as the De La Rue
Group of companies do not accept liability for any viruses.

De La Rue plc Registered No.3834125, De La Rue Holdings plc Registered
No 58025 and De La Rue International Limited Registered No 720284 are all
registered in England with their registered office at:
De La Rue House, Jays Close, Viables, Hampshire RG22 4BS
*****************************************************************************
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20080523/85b66c47/attachment.html
From scarfboy at gmail.com  Fri May 23 11:14:31 2008
From: scarfboy at gmail.com (Bart)
Date: Fri May 23 11:14:40 2008
Subject: [mod_python] Question about get_basic_auth_pw()
In-Reply-To: <5213E58D85BC414998FA553C701E386C0EF281C8A0@SGBD012511.dlrmail.ad.delarue.com>
References: <5213E58D85BC414998FA553C701E386C0EF281C8A0@SGBD012511.dlrmail.ad.delarue.com>
Message-ID: <b71082d80805230814n7256ea80k1d9fa1b33fd44b1d@mail.gmail.com>

2008/5/23  <Dominique.Holzwarth@ch.delarue.com>:
> Hi all
>
> Does anyone have an idea how the function "get_basic_auth_pw()" manages to
> decrypt the user password stored as MD5 inside the auth-file into its clear
> text version?
> I'm asking cause I maybe have to convert the MD5 passwords into the clear
> texts passwords myself and wondering how this is possible as normaly those
> passwords shouldn't be decryptable (i think) and authentication should be
> done by matching 2 MD5? =)

You may be thinking of Digest HTTP authentication.
Basic HTTP authentication sends passwords in (base64'd, IIRC) plain text.

Regards,
--Bart

From seb_k at arcor.de  Fri May 23 16:51:05 2008
From: seb_k at arcor.de (SebK)
Date: Fri May 23 16:51:19 2008
Subject: [mod_python] Authorization cache?
Message-ID: <200805232251.10685.seb_k@arcor.de>

Hello, 
i'm new at this list.
I'am programming Python for two years.

I am using mod_python PythonAuthHandler for an internal site.
The authentication is done via an pickled dict objec on the filesystem.
I've build in an password changing programm/script witch saves the changed 
dict to the file.
Problem: After changing the password the new password dosn't work but the old 
one remains working.

What could be wrong? Or what is missing?

thanks
sebastian
-- 
GPG Key: http://rynx.dyndns.org/~sebk/seb_k.asc
Fingerprint: 0CC0 BBB6 2916 95C1 563E 37DF EB14 7728 78A4 77D3
-------------- next part --------------
A non-text attachment was scrubbed...
Name: not available
Type: application/pgp-signature
Size: 189 bytes
Desc: This is a digitally signed message part.
Url : http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20080523/8bb7d406/attachment.bin
From graham.dumpleton at gmail.com  Fri May 23 17:04:03 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Fri May 23 17:04:09 2008
Subject: [mod_python] Authorization cache?
In-Reply-To: <200805232251.10685.seb_k@arcor.de>
References: <200805232251.10685.seb_k@arcor.de>
Message-ID: <88e286470805231404lda7da9bpee96e79b1af48455@mail.gmail.com>

2008/5/24 SebK <seb_k@arcor.de>:
> Hello,
> i'm new at this list.
> I'am programming Python for two years.
>
> I am using mod_python PythonAuthHandler for an internal site.
> The authentication is done via an pickled dict objec on the filesystem.
> I've build in an password changing programm/script witch saves the changed
> dict to the file.
> Problem: After changing the password the new password dosn't work but the old
> one remains working.
>
> What could be wrong? Or what is missing?

Do you cache the password database in memory after reading it for the
first time, or do you ensure you reread the database on every request?

The processes in mod_python persist across requests, so if you are
relying on cached database in memory this will be the behaviour you
see.

Graham
From graham.dumpleton at gmail.com  Fri May 23 23:41:32 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Fri May 23 23:41:39 2008
Subject: [mod_python] Authorization cache?
In-Reply-To: <200805232327.19930.seb_k@arcor.de>
References: <200805232251.10685.seb_k@arcor.de>
	<88e286470805231404lda7da9bpee96e79b1af48455@mail.gmail.com>
	<200805232327.19930.seb_k@arcor.de>
Message-ID: <88e286470805232041y26ae495en9beeaa9e28cd75d8@mail.gmail.com>

Please use reply-all and keep discussion on the list.

2008/5/24 SebK <seb_k@arcor.de>:
> Am Freitag, 23. Mai 2008 23:04:03 schrieben Sie:
>> 2008/5/24 SebK <seb_k@arcor.de>:
>> > Hello,
>> > i'm new at this list.
>> > I'am programming Python for two years.
>> >
>> > I am using mod_python PythonAuthHandler for an internal site.
>> > The authentication is done via an pickled dict objec on the filesystem.
>> > I've build in an password changing programm/script witch saves the
>> > changed dict to the file.
>> > Problem: After changing the password the new password dosn't work but the
>> > old one remains working.
>> >
>> > What could be wrong? Or what is missing?
>>
>> Do you cache the password database in memory after reading it for the
>> first time, or do you ensure you reread the database on every request?
>>
>> The processes in mod_python persist across requests, so if you are
>> relying on cached database in memory this will be the behaviour you
>> see.
>>
>> Graham
>
> My code is
>
> f = open(file, "r")
> db = load(f)
> f.close()
>
>>r_read = users.rights["read"]
>>
>>def authenhandler(req):
>>    pw = req.get_basic_auth_pw()
>>    user = req.user
>>    if user in db:
>>      pw = md5(pw).hexdigest()
>>      user = db[user]
>>      if pw == user.pw and user.hasRight(r_read):
>>        return apache.OK
>>    return apache.HTTP_UNAUTHORIZED
>
> so i guess it's saved in memory right?

Because you do it at global scope in the code file, yes.

Graham
From rahul.warhekar at edisphere.com  Sat May 24 01:48:44 2008
From: rahul.warhekar at edisphere.com (rahul)
Date: Sat May 24 01:53:22 2008
Subject: [mod_python] problem while fetching data from database
Message-ID: <FKEHLGFPCACLBKEEIEDFCEFECAAA.rahul.warhekar@edisphere.com>

hello sir,

Actually what is happening is

I have connected to oracle 10g using python and have trying to retrieve some
data from database.
But when i run query for fetching data on sql+ of oracle 10g interface it
giving me results in
just couple of seconds but when i use same query through python it consumes
more than 20 minutes
to display output in ui.ui is displaying only 25 messages at a time.

I look for following but found no problem
1) Execution plan for query.(it is good one)
2) chaeck for program(working fine)
3) No oracle problem

I am having 25 lacs messages in table

please help if any one have solution / Information regarding this problem

thanks

From graham.dumpleton at gmail.com  Sat May 24 03:17:51 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Sat May 24 03:17:55 2008
Subject: [mod_python] problem while fetching data from database
In-Reply-To: <FKEHLGFPCACLBKEEIEDFCEFECAAA.rahul.warhekar@edisphere.com>
References: <FKEHLGFPCACLBKEEIEDFCEFECAAA.rahul.warhekar@edisphere.com>
Message-ID: <88e286470805240017uadca67dm8fe8f2f7744bbf75@mail.gmail.com>

This list is for mod_python, and Apache module for running Python web
applications under Apache, not a general list for Python itself.

Perhaps try:

  http://groups.google.com/group/comp.lang.python/topics?lnk=lr

instead.

If you are trying to do this under mod_python, then first try it from
a standalone Python script and see if it works there. If it still
doesn't work, then again try the list above instead.

Graham

2008/5/24 rahul <rahul.warhekar@edisphere.com>:
> hello sir,
>
> Actually what is happening is
>
> I have connected to oracle 10g using python and have trying to retrieve some
> data from database.
> But when i run query for fetching data on sql+ of oracle 10g interface it
> giving me results in
> just couple of seconds but when i use same query through python it consumes
> more than 20 minutes
> to display output in ui.ui is displaying only 25 messages at a time.
>
> I look for following but found no problem
> 1) Execution plan for query.(it is good one)
> 2) chaeck for program(working fine)
> 3) No oracle problem
>
> I am having 25 lacs messages in table
>
> please help if any one have solution / Information regarding this problem
>
> thanks
>
> _______________________________________________
> Mod_python mailing list
> Mod_python@modpython.org
> http://mailman.modpython.org/mailman/listinfo/mod_python
>
From rpgfan3233 at gmail.com  Sat May 24 16:24:29 2008
From: rpgfan3233 at gmail.com (Dustin Boyd)
Date: Sat May 24 16:24:35 2008
Subject: [mod_python] Problems with Windows as usual.
Message-ID: <ef7a0f3a0805241324h6e3848b3nc24a282c5541e584@mail.gmail.com>

I recently upgraded to Python 2.5.2, Apache 2.2.8+OpenSSL 0.9.8g and
mod_python 3.3.1 on Windows XP SP2. I'm not sure why the configuration
broke just by upgrading, but it seems Python can't 'import site'
(site.py). I've tried things like setting PythonPath in httpd.conf,
and Apache's error log ends up with the following problems:
'import site' failed; use -v for traceback
ImportError: No module named mod_python.apache


I'm not sure what the problem is to be honest. If I was on a Linux
box, I'd have no problem according to the bits that I've read online
about this problem (just set PYTHONHOME to the correct directory and
things should be good). Unfortunately, that isn't the case. :(

Here is my httpd.conf file with only the Python bits in it:

LoadModule python_module modules/mod_python.so
# skipping some
<IfModule python_module>
  <Directory "C:/server/docs/python">
      AddHandler mod_python .py
      PythonHandler mod_python.publisher
      PythonDebug On
  </Directory>
</IfModule>

I run a "Hello World" test, and I get an HTTP 500 response code when I
do it. The errors above are logged each time I run it. My PATH
variable has no mention of my Python base installation directory
(C:\Python25), and I copied python25.dll to Apache's bin directory as
suggested. That fixed problems that I had with mod_python not loading
at all (couldn't find the DLL file), but now I have this issue. I've
searched my computer for other python*.dll files, and there are only
two - one in the Python base installation directory and one in
Apache's bin directory. I would think that it was a conflict except
that if either one disappears, things don't work correctly.

I ran depends.exe on mod_python.so as suggested in some other threads,
and it seems that it can't find a couple of DLL files in Apache's bin
directory (libapr-1.dll, libhttpd.dll and libaprutil-1.dll), though it
can find python25.dll.

I'd very much like to get this working, but if I can't then I guess
I'll need to find a different way to serve up Python files.

If the filenames of the installation packages are important, here they are:
httpd-2.2.8-win32-x86-ssl.zip (from Apache Lounge)
python-2.5.2.msi (from Python.org)
mod_python-3.3.1.win32-py2.5-Apache2.2.exe (from the mod_python site,
then redirected to Apache's site to download mod_python)

Thanks for any help or tips you can give!

-- 
Waiting patiently for Windows 7, XHTML 2.0, CSS 3.0, PHP 6.0, the
ratification of C++0x, and the day that I can code without logic
troubles.
From rahul.warhekar at edisphere.com  Sun May 25 03:57:36 2008
From: rahul.warhekar at edisphere.com (rahul)
Date: Sun May 25 04:02:27 2008
Subject: [mod_python] problems in browser
Message-ID: <FKEHLGFPCACLBKEEIEDFGEFGCAAA.rahul.warhekar@edisphere.com>

hello all

When i am using mozilla firefox browser my session variables are working
well
ie. when i delete data from session variable it gets properly deleted but
when i use

Internet Explorer at first data get deleted but for second time it wont
works
so if any on has any information regarding this  will be greatly appreciated

thanks and regards
rahul

From graham.dumpleton at gmail.com  Sun May 25 06:55:18 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Sun May 25 06:55:24 2008
Subject: [mod_python] Problems with Windows as usual.
In-Reply-To: <ef7a0f3a0805241324h6e3848b3nc24a282c5541e584@mail.gmail.com>
References: <ef7a0f3a0805241324h6e3848b3nc24a282c5541e584@mail.gmail.com>
Message-ID: <88e286470805250355p1ad92cddwe71e9498d940cd61@mail.gmail.com>

Try reading:

  http://www.modpython.org/pipermail/mod_python/2008-March/025022.html

Graham

2008/5/25 Dustin Boyd <rpgfan3233@gmail.com>:
> I recently upgraded to Python 2.5.2, Apache 2.2.8+OpenSSL 0.9.8g and
> mod_python 3.3.1 on Windows XP SP2. I'm not sure why the configuration
> broke just by upgrading, but it seems Python can't 'import site'
> (site.py). I've tried things like setting PythonPath in httpd.conf,
> and Apache's error log ends up with the following problems:
> 'import site' failed; use -v for traceback
> ImportError: No module named mod_python.apache
>
>
> I'm not sure what the problem is to be honest. If I was on a Linux
> box, I'd have no problem according to the bits that I've read online
> about this problem (just set PYTHONHOME to the correct directory and
> things should be good). Unfortunately, that isn't the case. :(
>
> Here is my httpd.conf file with only the Python bits in it:
>
> LoadModule python_module modules/mod_python.so
> # skipping some
> <IfModule python_module>
>  <Directory "C:/server/docs/python">
>      AddHandler mod_python .py
>      PythonHandler mod_python.publisher
>      PythonDebug On
>  </Directory>
> </IfModule>
>
> I run a "Hello World" test, and I get an HTTP 500 response code when I
> do it. The errors above are logged each time I run it. My PATH
> variable has no mention of my Python base installation directory
> (C:\Python25), and I copied python25.dll to Apache's bin directory as
> suggested. That fixed problems that I had with mod_python not loading
> at all (couldn't find the DLL file), but now I have this issue. I've
> searched my computer for other python*.dll files, and there are only
> two - one in the Python base installation directory and one in
> Apache's bin directory. I would think that it was a conflict except
> that if either one disappears, things don't work correctly.
>
> I ran depends.exe on mod_python.so as suggested in some other threads,
> and it seems that it can't find a couple of DLL files in Apache's bin
> directory (libapr-1.dll, libhttpd.dll and libaprutil-1.dll), though it
> can find python25.dll.
>
> I'd very much like to get this working, but if I can't then I guess
> I'll need to find a different way to serve up Python files.
>
> If the filenames of the installation packages are important, here they are:
> httpd-2.2.8-win32-x86-ssl.zip (from Apache Lounge)
> python-2.5.2.msi (from Python.org)
> mod_python-3.3.1.win32-py2.5-Apache2.2.exe (from the mod_python site,
> then redirected to Apache's site to download mod_python)
>
> Thanks for any help or tips you can give!
>
> --
> Waiting patiently for Windows 7, XHTML 2.0, CSS 3.0, PHP 6.0, the
> ratification of C++0x, and the day that I can code without logic
> troubles.
> _______________________________________________
> Mod_python mailing list
> Mod_python@modpython.org
> http://mailman.modpython.org/mailman/listinfo/mod_python
>
From graham.dumpleton at gmail.com  Sun May 25 06:58:48 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Sun May 25 06:58:56 2008
Subject: [mod_python] problems in browser
In-Reply-To: <FKEHLGFPCACLBKEEIEDFGEFGCAAA.rahul.warhekar@edisphere.com>
References: <FKEHLGFPCACLBKEEIEDFGEFGCAAA.rahul.warhekar@edisphere.com>
Message-ID: <88e286470805250358i48524d4eob4a22ad3fe4c399@mail.gmail.com>

For starters, post small self contained example of code which triggers
the issue.

Second, explain what your Apache/mod_python setup is. Ie.,
Windows/UNIX, winnt/prefork/worker MPM.

Third show any debugging output you have which helps to explain the problem.

Without stuff like that, anyone trying to help would just be guessing.

Graham

2008/5/25 rahul <rahul.warhekar@edisphere.com>:
> hello all
>
> When i am using mozilla firefox browser my session variables are working
> well
> ie. when i delete data from session variable it gets properly deleted but
> when i use
>
> Internet Explorer at first data get deleted but for second time it wont
> works
> so if any on has any information regarding this  will be greatly appreciated
>
> thanks and regards
> rahul
>
> _______________________________________________
> Mod_python mailing list
> Mod_python@modpython.org
> http://mailman.modpython.org/mailman/listinfo/mod_python
>
From rahul.warhekar at edisphere.com  Sun May 25 07:28:56 2008
From: rahul.warhekar at edisphere.com (rahul)
Date: Sun May 25 07:33:38 2008
Subject: [mod_python] problems in browser
In-Reply-To: <88e286470805250358i48524d4eob4a22ad3fe4c399@mail.gmail.com>
Message-ID: <FKEHLGFPCACLBKEEIEDFIEFHCAAA.rahul.warhekar@edisphere.com>

I am having Apache/2.0.55 (Win32) and mod_python 3.2.8 and i am using
windows xp with Internet explorer 7.0.5730.11
and mozilla 2.0.0.14

actually what i am doing

i ahve one variable as session['filter'] and on click of button i am
deleting data of that session variable.
and construct is on button click i call submitform("path") and do
session['filter']="" and go back to previous page
where i am displaying variables value
but internet explorer only does it once after that it do not clear the
displayed value while mozilla do it


-----Original Message-----
From: Graham Dumpleton [mailto:graham.dumpleton@gmail.com]
Sent: Sunday, May 25, 2008 4:29 PM
To: rahul
Cc: mod_python@modpython.org
Subject: Re: [mod_python] problems in browser


For starters, post small self contained example of code which triggers
the issue.

Second, explain what your Apache/mod_python setup is. Ie.,
Windows/UNIX, winnt/prefork/worker MPM.

Third show any debugging output you have which helps to explain the problem.

Without stuff like that, anyone trying to help would just be guessing.

Graham

2008/5/25 rahul <rahul.warhekar@edisphere.com>:
> hello all
>
> When i am using mozilla firefox browser my session variables are working
> well
> ie. when i delete data from session variable it gets properly deleted but
> when i use
>
> Internet Explorer at first data get deleted but for second time it wont
> works
> so if any on has any information regarding this  will be greatly
appreciated
>
> thanks and regards
> rahul
>
> _______________________________________________
> Mod_python mailing list
> Mod_python@modpython.org
> http://mailman.modpython.org/mailman/listinfo/mod_python
>

From graham.dumpleton at gmail.com  Sun May 25 07:59:38 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Sun May 25 07:59:46 2008
Subject: [mod_python] problems in browser
In-Reply-To: <FKEHLGFPCACLBKEEIEDFIEFHCAAA.rahul.warhekar@edisphere.com>
References: <88e286470805250358i48524d4eob4a22ad3fe4c399@mail.gmail.com>
	<FKEHLGFPCACLBKEEIEDFIEFHCAAA.rahul.warhekar@edisphere.com>
Message-ID: <88e286470805250459n4ea2d5f5y66505cb9268b88fc@mail.gmail.com>

Suggest you upgrade to mod_python 3.3.1.

Also, as already requested, please post small self contained example
of code which triggers the issue. It is not sufficient to give an
english description of what you are doing as that isn't the same as
the actual code. Your code could have a readily identifiable mistake
in it, but we cannot tell you what it is if you will not show the
code.

Graham

2008/5/25 rahul <rahul.warhekar@edisphere.com>:
> I am having Apache/2.0.55 (Win32) and mod_python 3.2.8 and i am using
> windows xp with Internet explorer 7.0.5730.11
> and mozilla 2.0.0.14
>
> actually what i am doing
>
> i ahve one variable as session['filter'] and on click of button i am
> deleting data of that session variable.
> and construct is on button click i call submitform("path") and do
> session['filter']="" and go back to previous page
> where i am displaying variables value
> but internet explorer only does it once after that it do not clear the
> displayed value while mozilla do it
>
>
> -----Original Message-----
> From: Graham Dumpleton [mailto:graham.dumpleton@gmail.com]
> Sent: Sunday, May 25, 2008 4:29 PM
> To: rahul
> Cc: mod_python@modpython.org
> Subject: Re: [mod_python] problems in browser
>
>
> For starters, post small self contained example of code which triggers
> the issue.
>
> Second, explain what your Apache/mod_python setup is. Ie.,
> Windows/UNIX, winnt/prefork/worker MPM.
>
> Third show any debugging output you have which helps to explain the problem.
>
> Without stuff like that, anyone trying to help would just be guessing.
>
> Graham
>
> 2008/5/25 rahul <rahul.warhekar@edisphere.com>:
>> hello all
>>
>> When i am using mozilla firefox browser my session variables are working
>> well
>> ie. when i delete data from session variable it gets properly deleted but
>> when i use
>>
>> Internet Explorer at first data get deleted but for second time it wont
>> works
>> so if any on has any information regarding this  will be greatly
> appreciated
>>
>> thanks and regards
>> rahul
>>
>> _______________________________________________
>> Mod_python mailing list
>> Mod_python@modpython.org
>> http://mailman.modpython.org/mailman/listinfo/mod_python
>>
>
>
From Dominique.Holzwarth at ch.delarue.com  Mon May 26 04:43:01 2008
From: Dominique.Holzwarth at ch.delarue.com (Dominique.Holzwarth@ch.delarue.com)
Date: Mon May 26 04:43:32 2008
Subject: [mod_python] Question about get_basic_auth_pw()
In-Reply-To: <b71082d80805230814n7256ea80k1d9fa1b33fd44b1d@mail.gmail.com>
Message-ID: <5213E58D85BC414998FA553C701E386C0EF281CB66@SGBD012511.dlrmail.ad.delarue.com>

Yes you're right, the password is sent to the server in plain text. But isn't the password just send only ONCE (when you log in)? Or is it stored inside a cookie and send with every request? Because the "get_basic_auth_pw()" can receive the password for every single request (not just the first one). That's why I thought it get's the data from the auth file...

The whole procedure I was thinking about is the following:
1. user provides login & pw (login screen)
2. data is sent to the client
3. pw is MD5 encrypted by apache and matched with the already encrypted pw inside the auth file
4. get_basic_auth_pw() reads the pw from the auth file

But that's not the case as it seems... Only other way I can imagine is the use of a cookie for resending the password with every request. But that's rather stupid imo... =)

Dominique

-----Original Message-----
From: Bart [mailto:scarfboy@gmail.com]
Sent: Freitag, 23. Mai 2008 17:15
To: mod_python@modpython.org
Subject: Re: [mod_python] Question about get_basic_auth_pw()

2008/5/23  <Dominique.Holzwarth@ch.delarue.com>:
> Hi all
>
> Does anyone have an idea how the function "get_basic_auth_pw()"
> manages to decrypt the user password stored as MD5 inside the
> auth-file into its clear text version?
> I'm asking cause I maybe have to convert the MD5 passwords into the
> clear texts passwords myself and wondering how this is possible as
> normaly those passwords shouldn't be decryptable (i think) and
> authentication should be done by matching 2 MD5... =)

You may be thinking of Digest HTTP authentication.
Basic HTTP authentication sends passwords in (base64'd, IIRC) plain text.

Regards,
--Bart



*****************************************************************************
This e-mail and any files attached are strictly confidential, may be legally
privileged and are intended solely for the addressee. If you are not the
intended recipient please notify the sender immediately by return email and
then delete the e-mail and any attachments immediately.

The views and or opinions expressed in this e-mail are not necessarily the
views of De La Rue plc or any of its subsidiaries and the De La Rue Group
of companies, their directors, officers and employees make no representation
about and accept no liability for its accuracy or completeness.

You should ensure that you have adequate virus protection as the De La Rue
Group of companies do not accept liability for any viruses.

De La Rue plc Registered No.3834125, De La Rue Holdings plc Registered
No 58025 and De La Rue International Limited Registered No 720284 are all
registered in England with their registered office at:
De La Rue House, Jays Close, Viables, Hampshire RG22 4BS
*****************************************************************************


From graham.dumpleton at gmail.com  Mon May 26 05:48:55 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Mon May 26 05:49:01 2008
Subject: [mod_python] Question about get_basic_auth_pw()
In-Reply-To: <5213E58D85BC414998FA553C701E386C0EF281CB66@SGBD012511.dlrmail.ad.delarue.com>
References: <b71082d80805230814n7256ea80k1d9fa1b33fd44b1d@mail.gmail.com>
	<5213E58D85BC414998FA553C701E386C0EF281CB66@SGBD012511.dlrmail.ad.delarue.com>
Message-ID: <88e286470805260248q790b0deatb4a45f57d626329f@mail.gmail.com>

There is no MD5 or cookies involved. As already pointed out it is
base64 only and it gets sent by the browser on every request.

See:

  http://www.ietf.org/rfc/rfc2617.txt

Graham

2008/5/26  <Dominique.Holzwarth@ch.delarue.com>:
> Yes you're right, the password is sent to the server in plain text. But isn't the password just send only ONCE (when you log in)? Or is it stored inside a cookie and send with every request? Because the "get_basic_auth_pw()" can receive the password for every single request (not just the first one). That's why I thought it get's the data from the auth file...
>
> The whole procedure I was thinking about is the following:
> 1. user provides login & pw (login screen)
> 2. data is sent to the client
> 3. pw is MD5 encrypted by apache and matched with the already encrypted pw inside the auth file
> 4. get_basic_auth_pw() reads the pw from the auth file
>
> But that's not the case as it seems... Only other way I can imagine is the use of a cookie for resending the password with every request. But that's rather stupid imo... =)
>
> Dominique
>
> -----Original Message-----
> From: Bart [mailto:scarfboy@gmail.com]
> Sent: Freitag, 23. Mai 2008 17:15
> To: mod_python@modpython.org
> Subject: Re: [mod_python] Question about get_basic_auth_pw()
>
> 2008/5/23  <Dominique.Holzwarth@ch.delarue.com>:
>> Hi all
>>
>> Does anyone have an idea how the function "get_basic_auth_pw()"
>> manages to decrypt the user password stored as MD5 inside the
>> auth-file into its clear text version?
>> I'm asking cause I maybe have to convert the MD5 passwords into the
>> clear texts passwords myself and wondering how this is possible as
>> normaly those passwords shouldn't be decryptable (i think) and
>> authentication should be done by matching 2 MD5... =)
>
> You may be thinking of Digest HTTP authentication.
> Basic HTTP authentication sends passwords in (base64'd, IIRC) plain text.
>
> Regards,
> --Bart
>
>
>
> *****************************************************************************
> This e-mail and any files attached are strictly confidential, may be legally
> privileged and are intended solely for the addressee. If you are not the
> intended recipient please notify the sender immediately by return email and
> then delete the e-mail and any attachments immediately.
>
> The views and or opinions expressed in this e-mail are not necessarily the
> views of De La Rue plc or any of its subsidiaries and the De La Rue Group
> of companies, their directors, officers and employees make no representation
> about and accept no liability for its accuracy or completeness.
>
> You should ensure that you have adequate virus protection as the De La Rue
> Group of companies do not accept liability for any viruses.
>
> De La Rue plc Registered No.3834125, De La Rue Holdings plc Registered
> No 58025 and De La Rue International Limited Registered No 720284 are all
> registered in England with their registered office at:
> De La Rue House, Jays Close, Viables, Hampshire RG22 4BS
> *****************************************************************************
>
>
> _______________________________________________
> Mod_python mailing list
> Mod_python@modpython.org
> http://mailman.modpython.org/mailman/listinfo/mod_python
>
From rahul.warhekar at edisphere.com  Mon May 26 09:18:11 2008
From: rahul.warhekar at edisphere.com (rahul)
Date: Mon May 26 09:22:50 2008
Subject: [mod_python] regarding data retrieval
Message-ID: <FKEHLGFPCACLBKEEIEDFEEGECAAA.rahul.warhekar@edisphere.com>

upto what size we can store characters into python variable.

because i am getting following error when data retrieved from database goes
beyond 2048 characters.
field in msaccess is memo.
error:-

b.recno,b.recordid,b.folderid,b.senderid,b.receiverid,b.intctrlno,b.funcgctr
lno,b.tsetctrlno,b.inlogkey,b.fglogkey,b.appmsgkey,b.tpagreementkey,b.messag
eid,b.messagetype,b.inputfilename,b.outputfilename,b.isassodatapresent,b.dat
e_time,b.messagestate,b.ackstate,b.ackexpiretime,b.errorcode,b.ackkeyb.error
code,b.ackkeyb.errorcode,b.ackkeyb.errorcode,b.ackkeyb.errorcode,ackkeyb.err
orcode,b.ackkeyyb.errorcode,b.ackkeyb.errorcode,ackkeyb.errorcode,b.ackkeyyb
.errorcode,b.ackkeyb.errorcode,ackkeyb.errorcode,b.ackkey???????????????????
??? ????7? ASSAMESE???????????????????????0????8?
GUJARATI????????????????????????????9?MARATHI????????????????????????????
?:?PUNJABI????????????????????????$????;?BANGLA??????????????????????????
????<?AZERBAIJANI?????????????????????????=?
MACEDONIAN??????????????????????????>?CYRILLIC
SERBIAN??????????????????????LATIN
SERBIAN??????????????????l????@?CYRILLIC
UZBEK??????????????????????A?LATIN
UZBEK?????????????????????????B?CYRILLIC
KAZAKH????????????????p????AMERICA????????????????????????P????UNITE
D
KINGDOM?????????????????L????GERMANY????????????????????????D????FRA
NCE?????????????????????????????CANADA????????????????????????
????CANADA???????????????????????%`????SPAIN???????????????????????
???8????ITALY??????????????????????????d????THE
NETHERLANDS????????????????X??? ?SWEDEN?????????????????????????h???
?NORWAY?????????????????????????T???
?DENMARK????????????????????????`????FINLAND???????????????????????\?
???FINLAND??????????????????????h???
?ICELAND????????????????????????T????GREECE?????????????????????????t?
???
PORTUGAL???????????????????????`????TURKEY?????????????????????????p??
??BRAZIL??????????????????????????????MEXICO?????????????????????????T
????CIS????????????????????????????@????CROATIA?????????????????????
???L????POLAND?????????????????????????d????HUNGARY?????????????????
???????4????CZECHOSLOVAKIA?????????????????d????
LITHUANIA??????????????????????T????ISRAEL?????????????????????????\??
??
BULGARIA????????????????????????????ALGERIA???????????????????????????
?
?BAHRAIN????????????????????????D???
?
CATALONIA??????????????????????????
?EGYPT???????????????????????????
????IRAQ???????????????????????????????
?JORDAN?????????????????????????????!?KUWAIT??????????????????????????
???"?LEBANON????????

OK

The server encountered an internal error or misconfiguration and was unable
to complete your request.

Please contact the server administrator, webmaster@localhost and inform them
of the time the error occurred, and anything you might have done that may
have caused the error.

More information about this error may be available in the server error log.
Apache/2.0.55 (Win32) PHP/5.1.2 mod_python/3.2.8 Python/2.4.3 Server at
localhost Port 80

From scarfboy at gmail.com  Mon May 26 10:29:48 2008
From: scarfboy at gmail.com (Bart)
Date: Mon May 26 10:29:54 2008
Subject: [mod_python] regarding data retrieval
In-Reply-To: <FKEHLGFPCACLBKEEIEDFEEGECAAA.rahul.warhekar@edisphere.com>
References: <FKEHLGFPCACLBKEEIEDFEEGECAAA.rahul.warhekar@edisphere.com>
Message-ID: <b71082d80805260729q37ec031y1f1555ed75117731@mail.gmail.com>

On Mon, May 26, 2008 at 3:18 PM, rahul <rahul.warhekar@edisphere.com> wrote:
> upto what size we can store characters into python variable.
>
> because i am getting following error when data retrieved from database goes
> beyond 2048 characters.

That's not a limitation of Python itself.

It's hard to say from your description (there's basically no error
there, other than the generic error page that apache hid the real
error with - try logging it?), but if this is not caused by the
database schema that is causing truncation when the data is entered
(and I assume you've checked that), I'd suspect it's some other
limitation of MS Access (or possibly some bad assumption in its
libraries). From what I've read about and used (both fairly little) of
Access, it seems full of limitations that immediately scare me off and
make me use a somewhat more serious database instead.

(By the way, since this is unrelated to mod_python, you should
probably try in a more general python mailing list, you'ld get more
answers.)

Regards,
--Bart
From joe at incomps.com  Tue May 27 11:05:55 2008
From: joe at incomps.com (Joseph Bernhardt)
Date: Tue May 27 11:06:35 2008
Subject: [mod_python] Apache User Profile
Message-ID: <00a201c8c00b$3c0b0eb0$b4212c10$@com>

This may not have much to do with mod_python, but I suspect that some of you
may have run into the same problem as I have.

 

I am using mod_python to execute a script from a remote client via a web
request.  For example: 

 

import subprocess

 

def index(req):

                subprocess.Popen(['scriptName'])

                return "success"

 

So that when a request is made to www.mysite.com/startScript it will execute
scriptName on the server.  I have many global variables that are defined
within /etc/profile that are required for scriptName to function properly.
When I log into the shell, I can execute scriptName without error.
Unfortunately, when the web request is made and the process is started under
the apache user, the global variables do not exist and the script fails.  

 

Does the apache user not recognize /etc/profile?  If not, where can I set
these global variables (besides within the script itself)?  

 

Thanks for any help!

 

Joseph Bernhardt 

 

-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20080527/9d25bdc2/attachment.html
From elias.collas at gulfstream.com  Tue May 27 15:01:21 2008
From: elias.collas at gulfstream.com (elias.collas@gulfstream.com)
Date: Tue May 27 15:01:55 2008
Subject: [mod_python] Apache User Profile
In-Reply-To: <00a201c8c00b$3c0b0eb0$b4212c10$@com>
Message-ID: <OF4635DCD3.97A25CA2-ON85257456.00682975-85257456.00687E80@zeus.git.gulfaero.com>


I don't know about reading all of your environment variables, but you may
define (redefine) the necessary ones in your Apache configuration files
with the PassEnv directive. I'll refer you to the Apache docs for the
details.

Elias Collas



                                                                           
             "Joseph                                                       
             Bernhardt"                                                    
             <joe@incomps.com>                                          To 
             Sent by:                  <mod_python@modpython.org>          
             mod_python-bounce                                          cc 
             s@modpython.org                                               
                                                                   Subject 
                                       [mod_python] Apache User Profile    
             05/27/2008 11:05                                              
             AM                                                            
                                                                           
                                                                           
                                                                           
                                                                           




This may not have much to do with mod_python, but I suspect that some of
you may have run into the same problem as I have.

I am using mod_python to execute a script from a remote client via a web
request.  For example:

import subprocess

def index(req):
                subprocess.Popen([?scriptName?])
                return ?success?

So that when a request is made to www.mysite.com/startScript it will
execute scriptName on the server.  I have many global variables that are
defined within /etc/profile that are required for scriptName to function
properly.  When I log into the shell, I can execute scriptName without
error.  Unfortunately, when the web request is made and the process is
started under the apache user, the global variables do not exist and the
script fails.

Does the apache user not recognize /etc/profile?  If not, where can I set
these global variables (besides within the script itself)?

Thanks for any help!

Joseph Bernhardt
 _______________________________________________
Mod_python mailing list
Mod_python@modpython.org
http://mailman.modpython.org/mailman/listinfo/mod_python

From joe at incomps.com  Tue May 27 15:40:27 2008
From: joe at incomps.com (Joseph Bernhardt)
Date: Tue May 27 15:40:37 2008
Subject: [mod_python] Apache User Profile
In-Reply-To: <OF4635DCD3.97A25CA2-ON85257456.00682975-85257456.00687E80@zeus.git.gulfaero.com>
References: <00a201c8c00b$3c0b0eb0$b4212c10$@com>
	<OF4635DCD3.97A25CA2-ON85257456.00682975-85257456.00687E80@zeus.git.gulfaero.com>
Message-ID: <00b601c8c031$8464fb00$8d2ef100$@com>

Thanks Elias,

Rob Shinn had also written to me personally on how to edit the httpd.conf file to define the environment upon apache startup.  It worked like a charm.  Thanks again.

Joseph Bernhardt

> -----Original Message-----
> From: mod_python-bounces@modpython.org [mailto:mod_python-
> bounces@modpython.org] On Behalf Of elias.collas@gulfstream.com
> Sent: Tuesday, May 27, 2008 1:01 PM
> To: mod_python@modpython.org
> Subject: Re: [mod_python] Apache User Profile
> 
> 
> I don't know about reading all of your environment variables, but you
> may
> define (redefine) the necessary ones in your Apache configuration files
> with the PassEnv directive. I'll refer you to the Apache docs for the
> details.
> 
> Elias Collas
> 
> 
> 



From graham.dumpleton at gmail.com  Tue May 27 16:31:31 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Tue May 27 16:31:37 2008
Subject: [mod_python] Apache User Profile
In-Reply-To: <OF4635DCD3.97A25CA2-ON85257456.00682975-85257456.00687E80@zeus.git.gulfaero.com>
References: <00a201c8c00b$3c0b0eb0$b4212c10$@com>
	<OF4635DCD3.97A25CA2-ON85257456.00682975-85257456.00687E80@zeus.git.gulfaero.com>
Message-ID: <88e286470805271331t24081856qefb0ac7af0db643f@mail.gmail.com>

I somewhat doubt PassEnv will help. It would apply only to CGI scripts
and not processes created from Python code.

Graham

2008/5/28  <elias.collas@gulfstream.com>:
>
> I don't know about reading all of your environment variables, but you may
> define (redefine) the necessary ones in your Apache configuration files
> with the PassEnv directive. I'll refer you to the Apache docs for the
> details.
>
> Elias Collas
>
>
>
>
>             "Joseph
>             Bernhardt"
>             <joe@incomps.com>                                          To
>             Sent by:                  <mod_python@modpython.org>
>             mod_python-bounce                                          cc
>             s@modpython.org
>                                                                   Subject
>                                       [mod_python] Apache User Profile
>             05/27/2008 11:05
>             AM
>
>
>
>
>
>
>
>
> This may not have much to do with mod_python, but I suspect that some of
> you may have run into the same problem as I have.
>
> I am using mod_python to execute a script from a remote client via a web
> request.  For example:
>
> import subprocess
>
> def index(req):
>                subprocess.Popen(['scriptName'])
>                return "success"
>
> So that when a request is made to www.mysite.com/startScript it will
> execute scriptName on the server.  I have many global variables that are
> defined within /etc/profile that are required for scriptName to function
> properly.  When I log into the shell, I can execute scriptName without
> error.  Unfortunately, when the web request is made and the process is
> started under the apache user, the global variables do not exist and the
> script fails.
>
> Does the apache user not recognize /etc/profile?  If not, where can I set
> these global variables (besides within the script itself)?
>
> Thanks for any help!
>
> Joseph Bernhardt
>  _______________________________________________
> Mod_python mailing list
> Mod_python@modpython.org
> http://mailman.modpython.org/mailman/listinfo/mod_python
>
> _______________________________________________
> Mod_python mailing list
> Mod_python@modpython.org
> http://mailman.modpython.org/mailman/listinfo/mod_python
>
From rahul.warhekar at edisphere.com  Wed May 28 07:29:16 2008
From: rahul.warhekar at edisphere.com (rahul)
Date: Wed May 28 07:33:57 2008
Subject: [mod_python] problems in browser
In-Reply-To: <88e286470805250459n4ea2d5f5y66505cb9268b88fc@mail.gmail.com>
Message-ID: <FKEHLGFPCACLBKEEIEDFKEGPCAAA.rahul.warhekar@edisphere.com>

my code is in list.psp as

<input style="Z-INDEX ;WIDTH :112px ;HEIGHT = 25px; background-color:
#666699; color: #ffffff;" type="submit" name="new_filter" value="Clear
Filter" class="buttonstyle"
onclick=submitForm('/edi/modules/reports/new.psp',myform,'mf');>

if (session['my']=='my'):
	session['my_filter'] = ""
	session['user_query'] = ""
	session['sql'] = ""
	session['my'] = ""
	session.save()
and the code in new.psp is,

<%@ include file="../../config.psp" %>
<%
import Session
session['my']="my"
session['con'] = " where "
session['bool']="false"
session.save()
%>
still it is not working properly with internet explorer.
Does upgrading to mod_python 3.3.1. will solve the issue.


-----Original Message-----
From: Graham Dumpleton [mailto:graham.dumpleton@gmail.com]
Sent: Sunday, May 25, 2008 5:30 PM
To: rahul
Cc: mod_python@modpython.org
Subject: Re: [mod_python] problems in browser


Suggest you upgrade to mod_python 3.3.1.

Also, as already requested, please post small self contained example
of code which triggers the issue. It is not sufficient to give an
english description of what you are doing as that isn't the same as
the actual code. Your code could have a readily identifiable mistake
in it, but we cannot tell you what it is if you will not show the
code.

Graham

2008/5/25 rahul <rahul.warhekar@edisphere.com>:
> I am having Apache/2.0.55 (Win32) and mod_python 3.2.8 and i am using
> windows xp with Internet explorer 7.0.5730.11
> and mozilla 2.0.0.14
>
> actually what i am doing
>
> i ahve one variable as session['filter'] and on click of button i am
> deleting data of that session variable.
> and construct is on button click i call submitform("path") and do
> session['filter']="" and go back to previous page
> where i am displaying variables value
> but internet explorer only does it once after that it do not clear the
> displayed value while mozilla do it
>
>
> -----Original Message-----
> From: Graham Dumpleton [mailto:graham.dumpleton@gmail.com]
> Sent: Sunday, May 25, 2008 4:29 PM
> To: rahul
> Cc: mod_python@modpython.org
> Subject: Re: [mod_python] problems in browser
>
>
> For starters, post small self contained example of code which triggers
> the issue.
>
> Second, explain what your Apache/mod_python setup is. Ie.,
> Windows/UNIX, winnt/prefork/worker MPM.
>
> Third show any debugging output you have which helps to explain the
problem.
>
> Without stuff like that, anyone trying to help would just be guessing.
>
> Graham
>
> 2008/5/25 rahul <rahul.warhekar@edisphere.com>:
>> hello all
>>
>> When i am using mozilla firefox browser my session variables are working
>> well
>> ie. when i delete data from session variable it gets properly deleted but
>> when i use
>>
>> Internet Explorer at first data get deleted but for second time it wont
>> works
>> so if any on has any information regarding this  will be greatly
> appreciated
>>
>> thanks and regards
>> rahul
>>
>> _______________________________________________
>> Mod_python mailing list
>> Mod_python@modpython.org
>> http://mailman.modpython.org/mailman/listinfo/mod_python
>>
>
>

From graham.dumpleton at gmail.com  Wed May 28 07:45:04 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Wed May 28 07:45:11 2008
Subject: [mod_python] problems in browser
In-Reply-To: <FKEHLGFPCACLBKEEIEDFKEGPCAAA.rahul.warhekar@edisphere.com>
References: <88e286470805250459n4ea2d5f5y66505cb9268b88fc@mail.gmail.com>
	<FKEHLGFPCACLBKEEIEDFKEGPCAAA.rahul.warhekar@edisphere.com>
Message-ID: <88e286470805280445o52f4af9ew549b56ac81e29a67@mail.gmail.com>

You are not deleting data from session, you are setting it to empty
string. That is not the same thing. Do you perhaps mean to use Python
'del' operator on session dictionary.

Also, that isn't really a complete self contained example as I cant
even see how you are validating whether it is doing what you want or
not and thus how your criteria for success is being determined. So not
really enough information to be able to help.

BTW, using mod_python 3.3 probably will not help much, but it is
always better to be using most up to date version. Older versions do
have various bugs.

Graham

2008/5/28 rahul <rahul.warhekar@edisphere.com>:
> my code is in list.psp as
>
> <input style="Z-INDEX ;WIDTH :112px ;HEIGHT = 25px; background-color:
> #666699; color: #ffffff;" type="submit" name="new_filter" value="Clear
> Filter" class="buttonstyle"
> onclick=submitForm('/edi/modules/reports/new.psp',myform,'mf');>
>
> if (session['my']=='my'):
>        session['my_filter'] = ""
>        session['user_query'] = ""
>        session['sql'] = ""
>        session['my'] = ""
>        session.save()
> and the code in new.psp is,
>
> <%@ include file="../../config.psp" %>
> <%
> import Session
> session['my']="my"
> session['con'] = " where "
> session['bool']="false"
> session.save()
> %>
> still it is not working properly with internet explorer.
> Does upgrading to mod_python 3.3.1. will solve the issue.
>
>
> -----Original Message-----
> From: Graham Dumpleton [mailto:graham.dumpleton@gmail.com]
> Sent: Sunday, May 25, 2008 5:30 PM
> To: rahul
> Cc: mod_python@modpython.org
> Subject: Re: [mod_python] problems in browser
>
>
> Suggest you upgrade to mod_python 3.3.1.
>
> Also, as already requested, please post small self contained example
> of code which triggers the issue. It is not sufficient to give an
> english description of what you are doing as that isn't the same as
> the actual code. Your code could have a readily identifiable mistake
> in it, but we cannot tell you what it is if you will not show the
> code.
>
> Graham
>
> 2008/5/25 rahul <rahul.warhekar@edisphere.com>:
>> I am having Apache/2.0.55 (Win32) and mod_python 3.2.8 and i am using
>> windows xp with Internet explorer 7.0.5730.11
>> and mozilla 2.0.0.14
>>
>> actually what i am doing
>>
>> i ahve one variable as session['filter'] and on click of button i am
>> deleting data of that session variable.
>> and construct is on button click i call submitform("path") and do
>> session['filter']="" and go back to previous page
>> where i am displaying variables value
>> but internet explorer only does it once after that it do not clear the
>> displayed value while mozilla do it
>>
>>
>> -----Original Message-----
>> From: Graham Dumpleton [mailto:graham.dumpleton@gmail.com]
>> Sent: Sunday, May 25, 2008 4:29 PM
>> To: rahul
>> Cc: mod_python@modpython.org
>> Subject: Re: [mod_python] problems in browser
>>
>>
>> For starters, post small self contained example of code which triggers
>> the issue.
>>
>> Second, explain what your Apache/mod_python setup is. Ie.,
>> Windows/UNIX, winnt/prefork/worker MPM.
>>
>> Third show any debugging output you have which helps to explain the
> problem.
>>
>> Without stuff like that, anyone trying to help would just be guessing.
>>
>> Graham
>>
>> 2008/5/25 rahul <rahul.warhekar@edisphere.com>:
>>> hello all
>>>
>>> When i am using mozilla firefox browser my session variables are working
>>> well
>>> ie. when i delete data from session variable it gets properly deleted but
>>> when i use
>>>
>>> Internet Explorer at first data get deleted but for second time it wont
>>> works
>>> so if any on has any information regarding this  will be greatly
>> appreciated
>>>
>>> thanks and regards
>>> rahul
>>>
>>> _______________________________________________
>>> Mod_python mailing list
>>> Mod_python@modpython.org
>>> http://mailman.modpython.org/mailman/listinfo/mod_python
>>>
>>
>>
>
>
From rahul.warhekar at edisphere.com  Wed May 28 07:56:43 2008
From: rahul.warhekar at edisphere.com (rahul)
Date: Wed May 28 08:01:23 2008
Subject: [mod_python] problems in browser
In-Reply-To: <88e286470805280445o52f4af9ew549b56ac81e29a67@mail.gmail.com>
Message-ID: <FKEHLGFPCACLBKEEIEDFCEHACAAA.rahul.warhekar@edisphere.com>

will deleting data from session['my_filter'] as i am using it will solve the
problem of not able to remove value from session variable.

-----Original Message-----
From: Graham Dumpleton [mailto:graham.dumpleton@gmail.com]
Sent: Wednesday, May 28, 2008 5:15 PM
To: rahul
Cc: mod_python@modpython.org
Subject: Re: [mod_python] problems in browser


You are not deleting data from session, you are setting it to empty
string. That is not the same thing. Do you perhaps mean to use Python
'del' operator on session dictionary.

Also, that isn't really a complete self contained example as I cant
even see how you are validating whether it is doing what you want or
not and thus how your criteria for success is being determined. So not
really enough information to be able to help.

BTW, using mod_python 3.3 probably will not help much, but it is
always better to be using most up to date version. Older versions do
have various bugs.

Graham

2008/5/28 rahul <rahul.warhekar@edisphere.com>:
> my code is in list.psp as
>
> <input style="Z-INDEX ;WIDTH :112px ;HEIGHT = 25px; background-color:
> #666699; color: #ffffff;" type="submit" name="new_filter" value="Clear
> Filter" class="buttonstyle"
> onclick=submitForm('/edi/modules/reports/new.psp',myform,'mf');>
>
> if (session['my']=='my'):
>        session['my_filter'] = ""
>        session['user_query'] = ""
>        session['sql'] = ""
>        session['my'] = ""
>        session.save()
> and the code in new.psp is,
>
> <%@ include file="../../config.psp" %>
> <%
> import Session
> session['my']="my"
> session['con'] = " where "
> session['bool']="false"
> session.save()
> %>
> still it is not working properly with internet explorer.
> Does upgrading to mod_python 3.3.1. will solve the issue.
>
>
> -----Original Message-----
> From: Graham Dumpleton [mailto:graham.dumpleton@gmail.com]
> Sent: Sunday, May 25, 2008 5:30 PM
> To: rahul
> Cc: mod_python@modpython.org
> Subject: Re: [mod_python] problems in browser
>
>
> Suggest you upgrade to mod_python 3.3.1.
>
> Also, as already requested, please post small self contained example
> of code which triggers the issue. It is not sufficient to give an
> english description of what you are doing as that isn't the same as
> the actual code. Your code could have a readily identifiable mistake
> in it, but we cannot tell you what it is if you will not show the
> code.
>
> Graham
>
> 2008/5/25 rahul <rahul.warhekar@edisphere.com>:
>> I am having Apache/2.0.55 (Win32) and mod_python 3.2.8 and i am using
>> windows xp with Internet explorer 7.0.5730.11
>> and mozilla 2.0.0.14
>>
>> actually what i am doing
>>
>> i ahve one variable as session['filter'] and on click of button i am
>> deleting data of that session variable.
>> and construct is on button click i call submitform("path") and do
>> session['filter']="" and go back to previous page
>> where i am displaying variables value
>> but internet explorer only does it once after that it do not clear the
>> displayed value while mozilla do it
>>
>>
>> -----Original Message-----
>> From: Graham Dumpleton [mailto:graham.dumpleton@gmail.com]
>> Sent: Sunday, May 25, 2008 4:29 PM
>> To: rahul
>> Cc: mod_python@modpython.org
>> Subject: Re: [mod_python] problems in browser
>>
>>
>> For starters, post small self contained example of code which triggers
>> the issue.
>>
>> Second, explain what your Apache/mod_python setup is. Ie.,
>> Windows/UNIX, winnt/prefork/worker MPM.
>>
>> Third show any debugging output you have which helps to explain the
> problem.
>>
>> Without stuff like that, anyone trying to help would just be guessing.
>>
>> Graham
>>
>> 2008/5/25 rahul <rahul.warhekar@edisphere.com>:
>>> hello all
>>>
>>> When i am using mozilla firefox browser my session variables are working
>>> well
>>> ie. when i delete data from session variable it gets properly deleted
but
>>> when i use
>>>
>>> Internet Explorer at first data get deleted but for second time it wont
>>> works
>>> so if any on has any information regarding this  will be greatly
>> appreciated
>>>
>>> thanks and regards
>>> rahul
>>>
>>> _______________________________________________
>>> Mod_python mailing list
>>> Mod_python@modpython.org
>>> http://mailman.modpython.org/mailman/listinfo/mod_python
>>>
>>
>>
>
>

From rahul.warhekar at edisphere.com  Thu May 29 00:15:07 2008
From: rahul.warhekar at edisphere.com (rahul)
Date: Thu May 29 00:19:48 2008
Subject: [mod_python] problems in browser
In-Reply-To: <FKEHLGFPCACLBKEEIEDFCEHACAAA.rahul.warhekar@edisphere.com>
Message-ID: <FKEHLGFPCACLBKEEIEDFOEHFCAAA.rahul.warhekar@edisphere.com>

hello all,

what is the difference between deleting data from session variables and
setting it to empty
string?

and if there is a difference then How to delete data from a session variable
in mod_python.

thanks

-----Original Message-----
From: mod_python-bounces@modpython.org
[mailto:mod_python-bounces@modpython.org]On Behalf Of rahul
Sent: Wednesday, May 28, 2008 5:27 PM
To: Graham Dumpleton
Cc: mod_python@modpython.org
Subject: RE: [mod_python] problems in browser


will deleting data from session['my_filter'] as i am using it will solve the
problem of not able to remove value from session variable.

-----Original Message-----
From: Graham Dumpleton [mailto:graham.dumpleton@gmail.com]
Sent: Wednesday, May 28, 2008 5:15 PM
To: rahul
Cc: mod_python@modpython.org
Subject: Re: [mod_python] problems in browser


You are not deleting data from session, you are setting it to empty
string. That is not the same thing. Do you perhaps mean to use Python
'del' operator on session dictionary.

Also, that isn't really a complete self contained example as I cant
even see how you are validating whether it is doing what you want or
not and thus how your criteria for success is being determined. So not
really enough information to be able to help.

BTW, using mod_python 3.3 probably will not help much, but it is
always better to be using most up to date version. Older versions do
have various bugs.

Graham

2008/5/28 rahul <rahul.warhekar@edisphere.com>:
> my code is in list.psp as
>
> <input style="Z-INDEX ;WIDTH :112px ;HEIGHT = 25px; background-color:
> #666699; color: #ffffff;" type="submit" name="new_filter" value="Clear
> Filter" class="buttonstyle"
> onclick=submitForm('/edi/modules/reports/new.psp',myform,'mf');>
>
> if (session['my']=='my'):
>        session['my_filter'] = ""
>        session['user_query'] = ""
>        session['sql'] = ""
>        session['my'] = ""
>        session.save()
> and the code in new.psp is,
>
> <%@ include file="../../config.psp" %>
> <%
> import Session
> session['my']="my"
> session['con'] = " where "
> session['bool']="false"
> session.save()
> %>
> still it is not working properly with internet explorer.
> Does upgrading to mod_python 3.3.1. will solve the issue.
>
>
> -----Original Message-----
> From: Graham Dumpleton [mailto:graham.dumpleton@gmail.com]
> Sent: Sunday, May 25, 2008 5:30 PM
> To: rahul
> Cc: mod_python@modpython.org
> Subject: Re: [mod_python] problems in browser
>
>
> Suggest you upgrade to mod_python 3.3.1.
>
> Also, as already requested, please post small self contained example
> of code which triggers the issue. It is not sufficient to give an
> english description of what you are doing as that isn't the same as
> the actual code. Your code could have a readily identifiable mistake
> in it, but we cannot tell you what it is if you will not show the
> code.
>
> Graham
>
> 2008/5/25 rahul <rahul.warhekar@edisphere.com>:
>> I am having Apache/2.0.55 (Win32) and mod_python 3.2.8 and i am using
>> windows xp with Internet explorer 7.0.5730.11
>> and mozilla 2.0.0.14
>>
>> actually what i am doing
>>
>> i ahve one variable as session['filter'] and on click of button i am
>> deleting data of that session variable.
>> and construct is on button click i call submitform("path") and do
>> session['filter']="" and go back to previous page
>> where i am displaying variables value
>> but internet explorer only does it once after that it do not clear the
>> displayed value while mozilla do it
>>
>>
>> -----Original Message-----
>> From: Graham Dumpleton [mailto:graham.dumpleton@gmail.com]
>> Sent: Sunday, May 25, 2008 4:29 PM
>> To: rahul
>> Cc: mod_python@modpython.org
>> Subject: Re: [mod_python] problems in browser
>>
>>
>> For starters, post small self contained example of code which triggers
>> the issue.
>>
>> Second, explain what your Apache/mod_python setup is. Ie.,
>> Windows/UNIX, winnt/prefork/worker MPM.
>>
>> Third show any debugging output you have which helps to explain the
> problem.
>>
>> Without stuff like that, anyone trying to help would just be guessing.
>>
>> Graham
>>
>> 2008/5/25 rahul <rahul.warhekar@edisphere.com>:
>>> hello all
>>>
>>> When i am using mozilla firefox browser my session variables are working
>>> well
>>> ie. when i delete data from session variable it gets properly deleted
but
>>> when i use
>>>
>>> Internet Explorer at first data get deleted but for second time it wont
>>> works
>>> so if any on has any information regarding this  will be greatly
>> appreciated
>>>
>>> thanks and regards
>>> rahul
>>>
>>> _______________________________________________
>>> Mod_python mailing list
>>> Mod_python@modpython.org
>>> http://mailman.modpython.org/mailman/listinfo/mod_python
>>>
>>
>>
>
>

_______________________________________________
Mod_python mailing list
Mod_python@modpython.org
http://mailman.modpython.org/mailman/listinfo/mod_python

From graham.dumpleton at gmail.com  Thu May 29 00:38:22 2008
From: graham.dumpleton at gmail.com (Graham Dumpleton)
Date: Thu May 29 00:38:29 2008
Subject: [mod_python] problems in browser
In-Reply-To: <FKEHLGFPCACLBKEEIEDFOEHFCAAA.rahul.warhekar@edisphere.com>
References: <FKEHLGFPCACLBKEEIEDFCEHACAAA.rahul.warhekar@edisphere.com>
	<FKEHLGFPCACLBKEEIEDFOEHFCAAA.rahul.warhekar@edisphere.com>
Message-ID: <88e286470805282138w126d4c49nb6da82f96a735149@mail.gmail.com>

Session dictionaries should be similar to Python dictionaries. So what
you do in Python, you do in mod_python.

  d = { "a": "b" }

  del d["a"]

Refer to Python documentation.

Graham

2008/5/29 rahul <rahul.warhekar@edisphere.com>:
> hello all,
>
> what is the difference between deleting data from session variables and
> setting it to empty
> string?
>
> and if there is a difference then How to delete data from a session variable
> in mod_python.
>
> thanks
>
> -----Original Message-----
> From: mod_python-bounces@modpython.org
> [mailto:mod_python-bounces@modpython.org]On Behalf Of rahul
> Sent: Wednesday, May 28, 2008 5:27 PM
> To: Graham Dumpleton
> Cc: mod_python@modpython.org
> Subject: RE: [mod_python] problems in browser
>
>
> will deleting data from session['my_filter'] as i am using it will solve the
> problem of not able to remove value from session variable.
>
> -----Original Message-----
> From: Graham Dumpleton [mailto:graham.dumpleton@gmail.com]
> Sent: Wednesday, May 28, 2008 5:15 PM
> To: rahul
> Cc: mod_python@modpython.org
> Subject: Re: [mod_python] problems in browser
>
>
> You are not deleting data from session, you are setting it to empty
> string. That is not the same thing. Do you perhaps mean to use Python
> 'del' operator on session dictionary.
>
> Also, that isn't really a complete self contained example as I cant
> even see how you are validating whether it is doing what you want or
> not and thus how your criteria for success is being determined. So not
> really enough information to be able to help.
>
> BTW, using mod_python 3.3 probably will not help much, but it is
> always better to be using most up to date version. Older versions do
> have various bugs.
>
> Graham
>
> 2008/5/28 rahul <rahul.warhekar@edisphere.com>:
>> my code is in list.psp as
>>
>> <input style="Z-INDEX ;WIDTH :112px ;HEIGHT = 25px; background-color:
>> #666699; color: #ffffff;" type="submit" name="new_filter" value="Clear
>> Filter" class="buttonstyle"
>> onclick=submitForm('/edi/modules/reports/new.psp',myform,'mf');>
>>
>> if (session['my']=='my'):
>>        session['my_filter'] = ""
>>        session['user_query'] = ""
>>        session['sql'] = ""
>>        session['my'] = ""
>>        session.save()
>> and the code in new.psp is,
>>
>> <%@ include file="../../config.psp" %>
>> <%
>> import Session
>> session['my']="my"
>> session['con'] = " where "
>> session['bool']="false"
>> session.save()
>> %>
>> still it is not working properly with internet explorer.
>> Does upgrading to mod_python 3.3.1. will solve the issue.
>>
>>
>> -----Original Message-----
>> From: Graham Dumpleton [mailto:graham.dumpleton@gmail.com]
>> Sent: Sunday, May 25, 2008 5:30 PM
>> To: rahul
>> Cc: mod_python@modpython.org
>> Subject: Re: [mod_python] problems in browser
>>
>>
>> Suggest you upgrade to mod_python 3.3.1.
>>
>> Also, as already requested, please post small self contained example
>> of code which triggers the issue. It is not sufficient to give an
>> english description of what you are doing as that isn't the same as
>> the actual code. Your code could have a readily identifiable mistake
>> in it, but we cannot tell you what it is if you will not show the
>> code.
>>
>> Graham
>>
>> 2008/5/25 rahul <rahul.warhekar@edisphere.com>:
>>> I am having Apache/2.0.55 (Win32) and mod_python 3.2.8 and i am using
>>> windows xp with Internet explorer 7.0.5730.11
>>> and mozilla 2.0.0.14
>>>
>>> actually what i am doing
>>>
>>> i ahve one variable as session['filter'] and on click of button i am
>>> deleting data of that session variable.
>>> and construct is on button click i call submitform("path") and do
>>> session['filter']="" and go back to previous page
>>> where i am displaying variables value
>>> but internet explorer only does it once after that it do not clear the
>>> displayed value while mozilla do it
>>>
>>>
>>> -----Original Message-----
>>> From: Graham Dumpleton [mailto:graham.dumpleton@gmail.com]
>>> Sent: Sunday, May 25, 2008 4:29 PM
>>> To: rahul
>>> Cc: mod_python@modpython.org
>>> Subject: Re: [mod_python] problems in browser
>>>
>>>
>>> For starters, post small self contained example of code which triggers
>>> the issue.
>>>
>>> Second, explain what your Apache/mod_python setup is. Ie.,
>>> Windows/UNIX, winnt/prefork/worker MPM.
>>>
>>> Third show any debugging output you have which helps to explain the
>> problem.
>>>
>>> Without stuff like that, anyone trying to help would just be guessing.
>>>
>>> Graham
>>>
>>> 2008/5/25 rahul <rahul.warhekar@edisphere.com>:
>>>> hello all
>>>>
>>>> When i am using mozilla firefox browser my session variables are working
>>>> well
>>>> ie. when i delete data from session variable it gets properly deleted
> but
>>>> when i use
>>>>
>>>> Internet Explorer at first data get deleted but for second time it wont
>>>> works
>>>> so if any on has any information regarding this  will be greatly
>>> appreciated
>>>>
>>>> thanks and regards
>>>> rahul
>>>>
>>>> _______________________________________________
>>>> Mod_python mailing list
>>>> Mod_python@modpython.org
>>>> http://mailman.modpython.org/mailman/listinfo/mod_python
>>>>
>>>
>>>
>>
>>
>
> _______________________________________________
> Mod_python mailing list
> Mod_python@modpython.org
> http://mailman.modpython.org/mailman/listinfo/mod_python
>
>
From joe at incomps.com  Thu May 29 11:23:57 2008
From: joe at incomps.com (Joseph Bernhardt)
Date: Thu May 29 11:24:15 2008
Subject: [mod_python] Expat-like parseString error
Message-ID: <010101c8c1a0$0383b330$0a8b1990$@com>

I am experiencing an issue very similar to the one found here:

 

http://mail.python.org/pipermail/python-list/2007-January/424015.html

 

whereas as mod_python application will return a blank screen upon the
calling of parseString.  Example:

 

from xml.dom.minidom import parseString

 

def index(req):

    parseString("<info>stuff</info>")

    return "blah"

 

The funny thing is, I am using Python 2.5 with expat 2.0.0, and therefore
the expat bug should not apply, correct?  Apache is using expat 1.95.7.
Would that make a difference?   Perhaps it is something completely
different.  Also, importing expat works just fine:

 

import pyexpat

 

def index(req):

    return "blah"

 

and it returns what it should.  What else can I try to narrow down the
issue?  Or, is there some other documentation that someone can point me to?
I can't seem to find anything else.

 

Thanks in advance!

 

Joseph Bernhardt

-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20080529/253ebd52/attachment.html
From joe at incomps.com  Thu May 29 15:17:20 2008
From: joe at incomps.com (Joseph Bernhardt)
Date: Thu May 29 15:17:39 2008
Subject: [mod_python] Expat-like parseString error
In-Reply-To: <010101c8c1a0$0383b330$0a8b1990$@com>
References: <010101c8c1a0$0383b330$0a8b1990$@com>
Message-ID: <011801c8c1c0$9e3da1e0$dab8e5a0$@com>

I see that minidom actually uses the xml.parsers.expat module.  The version
information of this on my system is 1.95.8 and when imported in a mod_python
application will return a blank page:

 

from xml.parsers import expat

 

def index(req):

    return "blah"

 

Which is starting to make sense now, and that it is the conflict between
this version and the version that apache is trying to use.  My new question:
Is there any way to force minidom to use a different version of expat
(either 2.0.0 or 1.95.7, either of which I would assume would work)?  I
noticed there was an optional 'Parser' argument to the parseString function.
Is this something that would be helpful?  If not, I could probably update
apache.  At any rate, this is probably not a mod_python issue anymore, but I
still thank you in advance for any help you may provide.

 

Graham - thank you again for the documentation you provide in your websites.
They have been of great help so far.

 

Joe

 

 

I am experiencing an issue very similar to the one found here:

 

http://mail.python.org/pipermail/python-list/2007-January/424015.html

 

whereas as mod_python application will return a blank screen upon the
calling of parseString.  Example:

 

from xml.dom.minidom import parseString

 

def index(req):

    parseString("<info>stuff</info>")

    return "blah"

 

The funny thing is, I am using Python 2.5 with expat 2.0.0, and therefore
the expat bug should not apply, correct?  Apache is using expat 1.95.7.
Would that make a difference?   Perhaps it is something completely
different.  Also, importing expat works just fine:

 

import pyexpat

 

def index(req):

    return "blah"

 

and it returns what it should.  What else can I try to narrow down the
issue?  Or, is there some other documentation that someone can point me to?
I can't seem to find anything else.

 

Thanks in advance!

 

Joseph Bernhardt

-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20080529/9211e47d/attachment.html
From joe at incomps.com  Thu May 29 17:32:42 2008
From: joe at incomps.com (Joseph Bernhardt)
Date: Thu May 29 17:33:04 2008
Subject: [mod_python] Expat-like parseString error
In-Reply-To: <011801c8c1c0$9e3da1e0$dab8e5a0$@com>
References: <010101c8c1a0$0383b330$0a8b1990$@com>
	<011801c8c1c0$9e3da1e0$dab8e5a0$@com>
Message-ID: <012601c8c1d3$87f4d990$97de8cb0$@com>

Ok, after several hours I have solved my own problem.  Looking over the
contents of the xml.parsers.expat module, I discovered that all it does is
imports pyexpat.  Hhmm, so how could it give a lower version number than
importing pyexpat directly?  Well, I came to find out that there were two
versions of pyexpat in my sys.path, the older being supplied by PyXML
(http://pyxml.sourceforge.net/).  Since I never use PyXML anyway, I've
simply removed the reference.  

 

It works now.

 

Thanks for tuning in.

 

Joe

 

From: mod_python-bounces@modpython.org
[mailto:mod_python-bounces@modpython.org] On Behalf Of Joseph Bernhardt
Sent: Thursday, May 29, 2008 1:17 PM
To: mod_python@modpython.org
Subject: RE: [mod_python] Expat-like parseString error

 

I see that minidom actually uses the xml.parsers.expat module.  The version
information of this on my system is 1.95.8 and when imported in a mod_python
application will return a blank page:

 

from xml.parsers import expat

 

def index(req):

    return "blah"

 

Which is starting to make sense now, and that it is the conflict between
this version and the version that apache is trying to use.  My new question:
Is there any way to force minidom to use a different version of expat
(either 2.0.0 or 1.95.7, either of which I would assume would work)?  I
noticed there was an optional 'Parser' argument to the parseString function.
Is this something that would be helpful?  If not, I could probably update
apache.  At any rate, this is probably not a mod_python issue anymore, but I
still thank you in advance for any help you may provide.

 

Graham - thank you again for the documentation you provide in your websites.
They have been of great help so far.

 

Joe

 

 

I am experiencing an issue very similar to the one found here:

 

http://mail.python.org/pipermail/python-list/2007-January/424015.html

 

whereas as mod_python application will return a blank screen upon the
calling of parseString.  Example:

 

from xml.dom.minidom import parseString

 

def index(req):

    parseString("<info>stuff</info>")

    return "blah"

 

The funny thing is, I am using Python 2.5 with expat 2.0.0, and therefore
the expat bug should not apply, correct?  Apache is using expat 1.95.7.
Would that make a difference?   Perhaps it is something completely
different.  Also, importing expat works just fine:

 

import pyexpat

 

def index(req):

    return "blah"

 

and it returns what it should.  What else can I try to narrow down the
issue?  Or, is there some other documentation that someone can point me to?
I can't seem to find anything else.

 

Thanks in advance!

 

Joseph Bernhardt

-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20080529/8a5c4c9f/attachment.html
From jeddahbill at gmail.com  Sat May 31 13:50:22 2008
From: jeddahbill at gmail.com (William Chapman)
Date: Sat May 31 13:50:24 2008
Subject: [mod_python] Windows performance problem
Message-ID: <6543521a0805311050n75794f45x46711e82226136c8@mail.gmail.com>

Skipped content of type multipart/alternative-------------- next part --------------
[Fri May 30 17:38:57 2008] [error] python_init: Python version mismatch, expected '2.5', found '2.5.2'.
[Fri May 30 17:38:58 2008] [error] python_init: Python executable found 'C:\\Program Files (x86)\\Apache Software Foundation\\Apache2.2\\bin\\httpd.exe'.
[Fri May 30 17:38:58 2008] [error] python_init: Python path being used 'C:\\WINDOWS\\system32\\python25.zip;C:\\Python25\\Lib;C:\\Python25\\DLLs;C:\\Python25\\Lib\\lib-tk;;C:\\Program Files (x86)\\Apache Software Foundation\\Apache2.2\\bin'.
