From cnewman at nngov.com  Mon Jan 24 09:51:50 2011
From: cnewman at nngov.com (Newman, Courtney D.)
Date: Mon Jan 24 09:52:02 2011
Subject: [mod_python] Intermittent Page Load Problem with mod_python
Message-ID: <B5D106B9E75D1145A258CEB9565046587981F56ACF@03s-exch01.nngov.local>

Hi,

I've inherited a server running a mod_python application written circa 2004-2005.  It is used as part of another application that we plan on retiring in the not too distant future.  The server is running Debian 3.1 which has been out of support for some time now.  I've been attempting to migrate the system to CentOS 5.5 so that I can receive regular OS security updates.  Also we are trying to standardize on 64-bit Linux and the old Debian system is 32-bit.

The mod_python application is having intermittent page load problems on the new server.  Most of the time it loads fine, but occasionally a blank screen is returned, usually at very inopportune times (e.g. after someone has entered login information, now they have to enter it a second time).  When I say the screen is blank, I mean absolutely no HTML is returned.  The Apache access log shows a 200 is returned.  There is nothing in the Apache error log.

CentOS comes with mod_python 3.2.8 (I think) pre-built.  I've updated it the final mod_python release on this system.  I've spent hours on Google looking for results.  I found one post on stack overflow (http://stackoverflow.com/questions/1508406/mod-python-produces-no-output) which suggests a problem with mod_python.cgi, but I've not been able to confirm this is the problem.  None of my configuration files for Apache appear to do anything with CGI.  I've also searched this mailing list via Google.  It's possible that this has been answered by someone on this list, but I have not been able to find it.

My Apache configuration for mod_python is pretty plain.  I'm posting it below:

<Directory "/var/www/html/psp/">
DirectoryIndex login.psp
AddHandler mod_python .psp
PythonHandler mod_python.psp
PythonPath "['/var/www/html/psp/common/modules'] + sys.path"
PythonDebug On
</Directory>

I'm not sure what other information would be helpful.  I'd really prefer not to have to re-write this application especially if there is an easy fix for this.

Thanks,

Courtney

-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20110124/6c6761ec/attachment.html
From jmaurer at hawaii.edu  Wed Jan 26 20:56:01 2011
From: jmaurer at hawaii.edu (John Maurer, IV)
Date: Wed Jan 26 20:56:09 2011
Subject: [mod_python] exit signal Segmentation fault (11)
Message-ID: <fba7a5672f4cf.4d404411@hawaii.edu>

Hi All,
I installed mod_python 3.3.1 today but cannot get the simple "Hello world!" test to work listed in the manual: http://www.modpython.org/live/mod_python-3.3.1/doc-html/inst-testing.html. When I restarted Apache after the installation, here is the line form Apache's error_log so you can see what version of things I am running:

[Wed Jan 26 15:32:24 2011] [notice] Apache/2.2.8 (Unix) mod_ssl/2.2.8 OpenSSL/0.9.8b PHP/5.2.6 mod_python/3.3.1 Python/2.7 configured -- resuming normal operations

Each time I access the test url from my web server, I get a blank page and Apache's error_log gives another line like the following:

[Wed Jan 26 15:32:33 2011] [notice] child pid 30058 exit signal Segmentation fault (11)

Subsequent access to the test page will give a similar line but with a different pid; e.g.:

[Wed Jan 26 15:32:33 2011] [notice] child pid 30061 exit signal Segmentation fault (11)

As per the manual test case, I have the following in my httpd.conf:

LoadModule python_module /usr/local/apache/modules/mod_python.so
PythonOption mod_python.mutex_locks 32

<Directory /usr/local/apache/htdocs/test>
    AddHandler mod_python .py
    PythonHandler mptest
    PythonDebug On
</Directory>

And /usr/local/apache/htdocs/test/mptest.py contains the following:

from mod_python import apache

def handler(req):
    req.content_type = 'text/plain'
    req.write("Hello World!")
    return apache.OK

A simple text file in the same directory can be accessed just fine, so there are not permissions problems.

My Python 2.7 was not configured with any options. I can import mod_python successfully in an interactive session and run mod_python.version to get back '3.3.1'.

I also tried a few older mod_python versions to see if that would solve the problem, but all give the same error message in the Apache error_log when I access my test page: mod_python 3.3.0b, 3.2.10, and 3.2.8.

Any ideas what's causing this problem? Hoping to get mod_python up and running but this hang up has me baffled.
Thanks!,
John Maurer

P.S. My 64-bit OS info:
>> cat /proc/version
Linux version 2.6.18-92.1.22.el5 (mockbuild@builder10.centos.org) (gcc version 4.1.2 20071124 (Red Hat 4.1.2-42)) #1 SMP Tue Dec 16 11:57:43 EST 2008


-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://mm_cfg_has_not_been_edited_to_set_host_domains/pipermail/mod_python/attachments/20110126/f92f8c2e/attachment.html
