From grisha at modpython.org  Fri Dec 20 22:55:25 2013
From: grisha at modpython.org (Grisha Trubetskoy)
Date: Fri, 20 Dec 2013 17:55:25 -0500
Subject: [mod_python] python3.3.3 -> make -> Error with apxs (OSX
	10.6.8) (#21)
In-Reply-To: <grisha/mod_python/issues/21@github.com>
References: <grisha/mod_python/issues/21@github.com>
Message-ID: <CAHb_syvFQ3i9fbNzP-facsUz4ize5USYM==TDXv7ZGWut_7_0Q@mail.gmail.com>

My guess is it's not liking the blanks in /Volumes/Mac OS
X/Users/tobias/Downloads/mod_python_git/mod_python/src/include...

This may actually be a bug with the ./configure script - it should
perhaps be wrapping paths in quotes, not sure. As a quick work-around,
I'd try creating a symlink to Users that contains no spaces.

Mind you - I remember having to compile Python 3.3.3rc1 manually on
OSX (with ./configure --enable-shared), the binary package from
python.org as well as brew version weren't quite working on Mavericks,
but this may be fixed now.

Grisha

On Fri, Dec 20, 2013 at 5:08 PM, Tobias Paar <notifications at github.com> wrote:
> Hi, I am trying to get mod_python with python3.3.3 working on my machine. It
> works well with python2, but with python3 I get this error:
>
> sh-3.2# make
>
> Building mod_python.so.
>
> /usr/sbin/apxs -I/Volumes/Mac OS
> X/Users/tobias/Downloads/mod_python_git/mod_python/src/include
> -I/Library/Frameworks/Python.framework/Versions/3.3/include/python3.3m
> -DNDEBUG -Wc,'-arch x86_64' -Wc,'-arch i386' -Wc,'-arch ppc7400' -c
> mod_python.c _apachemodule.c requestobject.c tableobject.c util.c
> serverobject.c connobject.c filterobject.c hlist.c hlistobject.c
> finfoobject.c version.c include/_apachemodule.h  include/filterobject.h
> include/hlist.h include/mod_python.h  include/psp_flex.h
> include/psp_parser.h include/requestobject.h include/tableobject.h
> include/connobject.h include/finfoobject.h include/hlistobject.h
> include/mp_version.h include/_pspmodule.h  include/psp_string.h
> include/serverobject.h include/util.h -arch x86_64 -arch i386 -arch ppc7400
> -Wl,-F/Library/Frameworks -framework Python -framework CoreFoundation  -ldl
> -framework CoreFoundation
> Usage: apxs -g [-S <var>=<val>] -n <modname>
>        apxs -q [-S <var>=<val>] <query> ...
>        apxs -c [-S <var>=<val>] [-o <dsofile>] [-D <name>[=<value>]]
>                [-I <incdir>] [-L <libdir>] [-l <libname>] [-Wc,<flags>]
>                [-Wl,<flags>] [-p] <files> ...
>        apxs -i [-S <var>=<val>] [-a] [-A] [-n <modname>] <dsofile> ...
>        apxs -e [-S <var>=<val>] [-a] [-A] [-n <modname>] <dsofile> ...
> make[1]: *** [mod_python.so] Error 1
> make: *** [do_dso] Error 2
>
> ?
> Reply to this email directly or view it on GitHub.


From grisha at modpython.org  Fri Dec 20 23:02:05 2013
From: grisha at modpython.org (Grisha Trubetskoy)
Date: Fri, 20 Dec 2013 18:02:05 -0500
Subject: [mod_python] python3.3.3 -> make -> Error with apxs (OSX
	10.6.8) (#21)
In-Reply-To: <grisha/mod_python/issues/21/31047305@github.com>
References: <grisha/mod_python/issues/21@github.com>
	<grisha/mod_python/issues/21/31047305@github.com>
Message-ID: <CAHb_syt80j5HmOinstboPPdNkaMVC5bcKTVGsjuq1UxBXAv2hA@mail.gmail.com>

That would be a bug... should be easy enough to fix, I created an issue for
it:

https://github.com/grisha/mod_python/issues/22

Grisha


On Fri, Dec 20, 2013 at 5:43 PM, Tobias Paar <notifications at github.com>wrote:

> Ok my fault :/
> I removed the blanks from the name of my Hard Disk - it now works like a
> charm! :-)
>
> except for one thing:
>
> sh-3.2# mod_python
>   File "/usr/local/bin/mod_python", line 95
>     print "\nCreated! Please look over %s." % `conf_path`
>                                           ^
> SyntaxError: invalid synta
>
> ?
> Reply to this email directly or view it on GitHub<https://github.com/grisha/mod_python/issues/21#issuecomment-31047305>
> .
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mailman.modpython.org/pipermail/mod_python/attachments/20131220/c62ddf8f/attachment.html>

