<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] Potential bug with util.py or mpservlet and upload
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20Potential%20bug%20with%20util.py%20or%20mpservlet%20and%20upload&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="016330.html">
   <LINK REL="Next"  HREF="016353.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[mod_python] Potential bug with util.py or mpservlet and upload</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>Vinj Vinj</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20Potential%20bug%20with%20util.py%20or%20mpservlet%20and%20upload&In-Reply-To="
       TITLE="[mod_python] Potential bug with util.py or mpservlet and upload">vinjvinj at yahoo.com
       </A><BR>
    <I>Fri Sep  3 16:19:39 EDT 2004</I>
    <P><UL>
        <LI>Previous message: <A HREF="016330.html">[mod_python] Servlets, cookies and redirect
</A></li>
        <LI>Next message: <A HREF="016353.html">[mod_python] Potential bug with util.py or mpservlet and upload
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#16349">[ date ]</a>
              <a href="thread.html#16349">[ thread ]</a>
              <a href="subject.html#16349">[ subject ]</a>
              <a href="author.html#16349">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>I get the following error when I try to upload a form
which has two files. I get this exception when I have
a file upload and the file upload variables are
specified in the query_vars or fields.

I'm currently getting the file
self.form['file'].file.read()

I'm getting this with the new util.py version from cvs
which fixes the other bug where I was getting a string
object back for file uploads. 

This took me a good part of 2 hours to figure out :-&lt;

This seems like an important enough patch (the updated
util.py) that should warrant a new mod_python release.



  self.__load_vars()

  File
&quot;C:\Python23\lib\site-packages\mod_python\servlet.py&quot;,
line 366, in __load_vars
    val = self.form.getfirst(name, default).strip()

  File
&quot;C:\Python23\lib\site-packages\mod_python\util.py&quot;,
line 64, in __getattr__
    raise AttributeError, name

AttributeError: strip

</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="016330.html">[mod_python] Servlets, cookies and redirect
</A></li>
	<LI>Next message: <A HREF="016353.html">[mod_python] Potential bug with util.py or mpservlet and upload
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#16349">[ date ]</a>
              <a href="thread.html#16349">[ thread ]</a>
              <a href="subject.html#16349">[ subject ]</a>
              <a href="author.html#16349">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script type="text/javascript"><!--
google_ad_client = "pub-9718360309690383";
google_ad_width = 120;
google_ad_height = 600;
google_ad_format = "120x600_as";
google_color_border = "CCCCCC";
google_color_bg = "FFFFFF";
google_color_link = "000000";
google_color_url = "666666";
google_color_text = "333333";
//--></script>
<script type="text/javascript"
  src="DISABLEhttp://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
