<tt>
&lt;!DOCTYPE&nbsp;html&nbsp;PUBLIC&nbsp;'-//W3C//DTD&nbsp;HTML&nbsp;4.01&nbsp;Transitional//EN'&gt;<br>
&lt;html&gt;<br>
&lt;head&gt;<br>
&nbsp;&lt;meta&nbsp;http-equiv='Content-Type'&nbsp;content='text/html;charset=us-ascii'&gt;<br>
&nbsp;&lt;style&gt;BODY{font:10pt&nbsp;Tahoma,&nbsp;Verdana,&nbsp;sans-serif;}&lt;/style&gt;<br>
&lt;/head&gt;<br>
&lt;body&gt;<br>
Hey&nbsp;all,&lt;br&gt;&lt;br&gt;I'm&nbsp;running&nbsp;into&nbsp;a&nbsp;problem&nbsp;trying&nbsp;to&nbsp;build&nbsp;Mod&nbsp;Python&nbsp;3.1.4&nbsp;on&nbsp;a&nbsp;Fedora&nbsp;4&nbsp;system.&nbsp;I'm&nbsp;building&nbsp;it&nbsp;because&nbsp;I&nbsp;need&nbsp;to&nbsp;to&nbsp;run&nbsp;Python&nbsp;2.3,&nbsp;which&nbsp;has&nbsp;already&nbsp;been&nbsp;installed&nbsp;on&nbsp;the&nbsp;system&nbsp;and&nbsp;appears&nbsp;to&nbsp;be&nbsp;working&nbsp;properly.&lt;br&gt;&lt;br&gt;So,&nbsp;I&nbsp;downloaded&nbsp;and&nbsp;extracted&nbsp;Mod&nbsp;Python&nbsp;3.1.4,&nbsp;and&nbsp;ran&nbsp;&quot;./configure&nbsp;--with-python=/usr/local/bin/python2.3&quot;&nbsp;to&nbsp;build&nbsp;it&nbsp;against&nbsp;the&nbsp;correct&nbsp;version.&nbsp;Ok,&nbsp;it&nbsp;detects&nbsp;Python&nbsp;2.3&nbsp;and&nbsp;creates&nbsp;the&nbsp;make&nbsp;file.&nbsp;&lt;br&gt;&lt;br&gt;Next,&nbsp;I&nbsp;run&nbsp;make.&nbsp;After&nbsp;a&nbsp;minute,&nbsp;the&nbsp;make&nbsp;fails&nbsp;with&nbsp;this&nbsp;error:&lt;br&gt;&lt;br&gt;------------------------------------------&lt;br&gt;/usr/bin/ld:&nbsp;/usr/local/lib/python2.3/config/libpython2.3.a(abstract.o):&nbsp;relocation&nbsp;R_X86_64_32S&nbsp;against&nbsp;`_Py_NotImplementedStruct'&nbsp;can&nbsp;not&nbsp;be&nbsp;used&nbsp;when&nbsp;making&nbsp;a&nbsp;shared&nbsp;object;&nbsp;recompile&nbsp;with&nbsp;-fPIC&lt;br&gt;/usr/local/lib/python2.3/config/libpython2.3.a:&nbsp;could&nbsp;not&nbsp;read&nbsp;symbols:&nbsp;Bad&nbsp;value&lt;br&gt;collect2:&nbsp;ld&nbsp;returned&nbsp;1&nbsp;exit&nbsp;status&lt;br&gt;apxs:Error:&nbsp;Command&nbsp;failed&nbsp;with&nbsp;rc=65536&lt;br&gt;.&lt;br&gt;make[1]:&nbsp;***&nbsp;[mod_python.so]&nbsp;Error&nbsp;1&lt;br&gt;make[1]:&nbsp;Leaving&nbsp;directory&nbsp;`/root/mod_python-3.1.4/src'&lt;br&gt;make:&nbsp;***&nbsp;[do_dso]&nbsp;Error&nbsp;2&lt;br&gt;------------------------------------------&lt;br&gt;&lt;br&gt;I've&nbsp;reinstalled&nbsp;Fedora&nbsp;twice&nbsp;now,&nbsp;just&nbsp;to&nbsp;be&nbsp;sure,&nbsp;and&nbsp;have&nbsp;been&nbsp;met&nbsp;with&nbsp;this&nbsp;same&nbsp;result&nbsp;both&nbsp;times.&nbsp;I&nbsp;have&nbsp;no&nbsp;idea&nbsp;where&nbsp;to&nbsp;go&nbsp;from&nbsp;here,&nbsp;or&nbsp;how&nbsp;to&nbsp;get&nbsp;this&nbsp;to&nbsp;build&nbsp;properly.&nbsp;&lt;br&gt;&lt;br&gt;Anyone&nbsp;seen&nbsp;this&nbsp;before,&nbsp;or&nbsp;know&nbsp;of&nbsp;a&nbsp;way&nbsp;to&nbsp;get&nbsp;around&nbsp;it?&lt;br&gt;&lt;br&gt;Thanks,&lt;br&gt;Brandon&lt;br&gt;&lt;/body&gt;&lt;/html&gt;
</tt>
